// Word Chain — valid words indexed by first letter for fast lookup
export const CHAIN_WORDS: readonly string[] = [
  // A
  "ABLE","ACID","AGED","ALSO","ANGEL","ANGLE","ANGRY","ANNEX","APPLE","APPLY",
  "ARCH","AREA","ARMY","ARISE","ARMOR","ASIDE","ATLAS","ATONE","AVOID","AWAKE",
  "AWARE","AGAIN","AGREE","AHEAD","ALARM","ALERT","ALONE","ALONG","ALTER","AMEND",
  // B
  "BACK","BADE","BAKE","BALD","BAND","BANE","BARK","BARN","BARE","BASH",
  "BATH","BEAD","BEAM","BEAN","BEAR","BEAT","BEEF","BELL","BELT","BEND",
  "BILL","BITE","BOLD","BONE","BOOK","BOOM","BORE","BORN","BRED","BREW",
  "BULK","BULL","BUMP","BURN","BUSH","BUSY","BLADE","BLAME","BLANK","BLAST",
  // C
  "CAGE","CAKE","CALL","CAME","CAPE","CARD","CARE","CART","CAVE","CELL",
  "CHIP","CHOP","CITY","CLAY","CLIP","CLUB","CLUE","COAL","COAT","COIN",
  "COLD","COME","CONE","COOK","COOL","COPE","CORE","CORN","COST","CREW",
  "CROP","CUBE","CURE","CAMEL","CANDY","CARRY","CATCH","CAUSE","CEASE","CHAIR",
  // D
  "DAMP","DARE","DARK","DASH","DATA","DATE","DAWN","DEAD","DEAL","DEAR",
  "DECK","DEEP","DEER","DEFT","DENY","DESK","DIAL","DICE","DINE","DIRT",
  "DOME","DONE","DOOM","DOOR","DOVE","DOWN","DRAG","DRAW","DRIP","DROP",
  "DRUM","DUCK","DUMP","DUSK","DUST","DANCE","DEATH","DRAFT","DREAM","DRESS",
  // E
  "EACH","EARL","EARN","EASE","EDGE","EMIT","ENVY","EPIC","EVEN","EVER",
  "EVIL","EXAM","EAGER","EARLY","EARTH","EXACT","EXIST","EXTRA","EAGLE","ELECT",
  // F
  "FACE","FACT","FADE","FAIL","FAIR","FAKE","FALL","FAME","FARE","FARM",
  "FAST","FEEL","FELL","FELT","FILE","FILL","FILM","FINE","FIRM","FISH",
  "FIST","FLAG","FLAT","FLEE","FLEX","FLIP","FOLK","FOND","FONT","FOOL",
  "FOOT","FORK","FORM","FORT","FOWL","FUEL","FULL","FURY","FUSE","FEAST",
  // G
  "GALE","GAME","GANG","GATE","GAZE","GEAR","GILL","GIRL","GLAD","GLOW",
  "GLUE","GOAL","GOAT","GOLF","GOOD","GRAB","GRAY","GREW","GRIN","GRIP",
  "GUST","GRACE","GRADE","GRAIN","GRANT","GRASP","GRASS","GREAT","GRIEF","GROUP",
  // H
  "HACK","HAIL","HAIR","HALF","HALL","HALT","HAND","HANG","HARD","HARE",
  "HARM","HARP","HASH","HAUL","HAWK","HEAD","HEAL","HEAP","HEAR","HEAT",
  "HEEL","HELP","HERB","HIGH","HILL","HIRE","HOLD","HOLE","HOME","HOOD",
  "HOOK","HOPE","HORN","HUGE","HULL","HUNG","HUNT","HURT","HEART","HEAVY",
  // I
  "IDEA","IDLE","INCH","IRON","ISLE","ITCH","ITEM","IMAGE","INDEX","INNER",
  // J
  "JADE","JAIL","JOKE","JOLT","JUMP","JUST","JUDGE","JUICE","JOINT","JEWEL",
  // K
  "KEEN","KEEP","KICK","KILL","KILN","KIND","KING","KITE","KNOW","KNIFE",
  // L
  "LACE","LACK","LAKE","LAMB","LAMP","LAND","LANE","LAST","LATE","LEAF",
  "LEAN","LEAP","LEFT","LESS","LIKE","LILY","LIME","LINE","LINK","LION",
  "LIVE","LOAD","LOAN","LOCK","LOFT","LONE","LOOK","LOSE","LOUD","LURE",
  "LARGE","LASER","LATER","LEARN","LEAVE","LEVEL","LIGHT","LIMIT","LOCAL","LOVER",
  // M
  "MACE","MAIL","MAIN","MAKE","MALE","MALL","MALT","MANY","MARK","MASH",
  "MAZE","MEAL","MEAN","MEAT","MELT","MEND","MILD","MILK","MILL","MINT",
  "MIST","MOCK","MOLE","MOON","MOOR","MOSS","MOTH","MOVE","MUCK","MULE",
  "MAGIC","MAKER","MARCH","MEDAL","METAL","MIGHT","MINOR","MODEL","MONEY","MUSIC",
  // N
  "NAIL","NEAR","NECK","NEED","NINE","NODE","NORM","NOTE","NOSE","NAVY",
  "NERVE","NIGHT","NOBLE","NOISE","NORTH","NOVEL","NERVE","NUDGE","NURSE","NICHE",
  // O
  "OAST","OATH","OBOE","ONCE","ONLY","OPEN","OVER","OVAL","OVEN","OWED",
  "ORBIT","ORDER","OFFER","OFTEN","OCCUR","OZONE","OUTDO","OUTGO","ONION","OCEAN",
  // P
  "PACE","PACK","PACT","PAIR","PALE","PALM","PAVE","PAWN","PEAL","PEEL",
  "PEER","PILL","PINE","PINK","PIPE","PLAN","PLAY","PLOT","PLOW","PLUG",
  "PLUM","PLUS","POEM","POLE","POLL","POND","PORE","PORT","POUR","PRAY",
  "PUFF","PULL","PUMP","PANDA","PANIC","PAPER","PATCH","PEACE","PEARL","PHASE",
  // Q
  "QUAY","QUIP","QUIZ","QUEEN","QUEST","QUICK","QUIET","QUITE","QUOTA","QUOTE",
  // R
  "RACE","RACK","RAFT","RAGE","RAID","RAIL","RAIN","RAKE","RAMP","RANG",
  "RANK","RANT","RASP","RAZE","RICH","RIDE","RIFF","RING","RIOT","RISE",
  "ROAM","ROAR","ROBE","RODE","ROLF","ROLL","ROOK","ROPE","ROSE","RUIN",
  "RUSH","RUSE","RAISE","RALLY","RANGE","RAPID","REACH","REALM","REBEL","RIDER",
  // S
  "SACK","SAFE","SAGE","SAIL","SAKE","SALE","SAND","SANE","SANK","SASH",
  "SEAL","SEAM","SEAT","SEED","SEEK","SEER","SELF","SELL","SHED","SHIN",
  "SHIP","SHOE","SHOP","SHOT","SHOW","SHUT","SICK","SILT","SING","SINK",
  "SITE","SKID","SLIM","SLIP","SLUG","SLUM","SLUR","SNAG","SNAP","SNOB",
  "SNOW","SNUG","SOAK","SOAP","SOAR","SOCK","SOIL","SOLE","SOME","SORT",
  "SOUL","SOUP","SOUR","SPAN","SPAR","SPIN","SPIT","SPOT","SPUR","STEM",
  "STEP","STEW","STOP","STUB","SUCK","SUIT","SULK","SUMP","SWORD","SWAM",
  "SWAM","SWAN","SWAP","SWAY","SWEAR","SHAPE","SHARE","SHARP","SHELF","SHIFT",
  // T
  "TACK","TALE","TALK","TALL","TAME","TAUT","TEAM","TEAR","TEAT","TENT",
  "TERM","THAN","THAT","THEN","THEY","THIN","THIS","THOU","TICK","TIDE",
  "TIDY","TILT","TINT","TINY","TOAD","TOLL","TOMB","TOME","TONG","TOOK",
  "TOOL","TORN","TOSS","TOUR","TRIM","TRIO","TRIP","TROD","TROY","TRUE",
  "TUCK","TUFT","TUNE","TUSK","TWIN","TWIST","TASTE","TEACH","TIGER","TIGHT",
  // U
  "UGLY","UNDO","UPON","USED","UTTER","UNCLE","UNDER","UNITY","UNTIL","UPPER",
  // V
  "VAIN","VALE","VANE","VARY","VEAL","VERB","VIEW","VILE","VISE","VOID",
  "VOLE","VOLT","VOTE","VEIL","VALUE","VERSE","VIDEO","VIGOR","VIRAL","VITAL",
  // W
  "WADE","WAGE","WAIL","WAIT","WALK","WALL","WANE","WARD","WARM","WARP",
  "WART","WARY","WAVE","WEAL","WEAN","WEAR","WEED","WEEK","WELD","WELL",
  "WELT","WEND","WEST","WHIM","WHIP","WIDE","WILT","WINK","WIRE","WISE",
  "WISH","WISP","WOKE","WOLF","WOMB","WORE","WORM","WORN","WOVE","WRAP",
  "WREN","WRIT","WHILE","WHITE","WHOLE","WATCH","WASTE","WATER","MIGHT","WORLD",
  // Y
  "YARD","YARN","YAWN","YEAR","YELL","YORE","YOUNG","YIELD","YEAST","YACHT",
  // Z
  "ZEAL","ZERO","ZEST","ZONE","ZOOM","ZINGY","ZEBRA","ZIPPER","ZEALOT","ZENITH",
] as const;

const WORD_SET = new Set(CHAIN_WORDS.map(w => w.toUpperCase()));

export function isValidChainWord(word: string): boolean {
  return WORD_SET.has(word.toUpperCase());
}
