import type { GamePlugin, SettingsOf, HintTarget } from "../../platform/game-plugin/types.js";
import type { DivisionDrillState, DivisionDrillAction } from "./state.js";
import { initialState, reducer, isTerminal } from "./state.js";
import { DivisionDrillGame } from "./Game.js";

export const divisionDrillSettings = {
  tables: {
    kind: "enum" as const,
    label: "Tables",
    options: ["1-5", "1-10", "1-12"] as const,
    default: "1-10" as const,
  },
  questions: {
    kind: "enum" as const,
    label: "Questions",
    options: ["10", "20", "50"] as const,
    default: "10" as const,
  },
} as const;

type DivisionDrillSettingsType = SettingsOf<typeof divisionDrillSettings>;

export const divisionDrillPlugin: GamePlugin<DivisionDrillState, DivisionDrillAction, typeof divisionDrillSettings> = {
  id: "division-drill",
  title: "Division Drill",
  category: "board",
  players: { min: 1, max: 1, multiplayer: false },
  description: "Drill division facts. Every problem divides evenly — no remainders. Type your answer and press Enter.",
  howToPlay: `Division Drill reinforces your ability to quickly recall division facts. Each problem shows a dividend and a divisor — for example 56 ÷ 8 = ? — and you type the whole-number answer, then press Enter or click the button to submit.

Every problem divides evenly: answers are always whole numbers with no remainders. The problems are generated by starting with two numbers within the selected tables range and multiplying them, then asking you to reverse the operation. This guarantees clean answers every time.

Each correct answer earns 10 points. A wrong answer scores zero but still advances you to the next question. A running score, correct count, and progress bar keep you informed throughout.

The Tables setting controls the size of the divisors and quotients: "1–5" stays small and beginner-friendly, "1–10" uses the standard multiplication grid, and "1–12" extends to the full 12×12 range.

Tips: Division is the inverse of multiplication, so if you know your times tables cold, you already know your division facts. When you see 72 ÷ 9, think "9 times what equals 72?" The 9s trick also works in reverse: 81 ÷ 9 = 9, 72 ÷ 9 = 8, etc. Practice the hardest facts (7s and 8s) separately until they are automatic.`,
  settings: divisionDrillSettings,
  initialState: (seed: number, settings: DivisionDrillSettingsType) => initialState(seed, settings),
  reducer,
  isTerminal,
  hint: (state: DivisionDrillState): HintTarget | null => (state.phase === "playing" ? { selector: '[data-testid="hint-target-division-drill-primary"]', pulses: 3 } : null),
  component: DivisionDrillGame,
};
