import { mulberry32 } from "../../platform/game-plugin/useSeededRng.js";

/**
 * Canonical Hasbro "Big New 1992" 4x4 Boggle dice. Each die is a 6-letter
 * tuple. We roll one face per die, shuffle die order with the seeded RNG,
 * and lay them out row-major in the 4x4 grid.
 *
 * Note: standard Boggle prints "Qu" on the Q-face. For typed input we treat
 * a Q-cell as the digraph "QU" when tracing, but for simplicity here we
 * keep single-letter cells throughout (Q becomes Q). This matches the
 * existing `boggle` plugin's convention in this repo.
 */
export const BOGGLE_DICE_1992: readonly (readonly string[])[] = [
  ["A", "A", "E", "E", "G", "N"],
  ["A", "B", "B", "J", "O", "O"],
  ["A", "C", "H", "O", "P", "S"],
  ["A", "F", "F", "K", "P", "S"],
  ["A", "O", "O", "T", "T", "W"],
  ["C", "I", "M", "O", "T", "U"],
  ["D", "E", "I", "L", "R", "X"],
  ["D", "E", "L", "R", "V", "Y"],
  ["D", "I", "S", "T", "T", "Y"],
  ["E", "E", "G", "H", "N", "W"],
  ["E", "E", "I", "N", "S", "U"],
  ["E", "H", "R", "T", "V", "W"],
  ["E", "I", "O", "S", "S", "T"],
  ["E", "L", "R", "T", "T", "Y"],
  ["H", "I", "M", "N", "U", "Q"],
  ["H", "L", "N", "N", "R", "Z"],
] as const;

/* ------------------------------------------------------------------ *
 * Embedded ~3000-entry common-English dictionary. Stored as a single
 * space-delimited string at module load to keep source file readable
 * and to avoid 3,000 quoted-string allocations at parse time. We split
 * once and hand the result to a Set for O(1) case-insensitive lookup.
 * ------------------------------------------------------------------ */
const DICTIONARY_TEXT = (
  // 3-letter (~270)
  "ACE ACT ADD AGE AGO AID AIM AIR ALE ALL AND ANT ANY APE APT ARC ARE ARK ARM ART ASH ASK ATE AWE AXE " +
  "BAD BAG BAN BAR BAT BAY BED BEE BEG BET BIB BID BIG BIN BIT BOA BOB BOG BOO BOW BOX BOY BUD BUG BUN BUS BUT BUY BYE " +
  "CAB CAN CAP CAR CAT COB COD COG CON COO COP COT COW COY CRY CUB CUE CUP CUR CUT " +
  "DAB DAD DAM DEN DEW DID DIE DIG DIM DIN DIP DOE DOG DON DOT DRY DUB DUD DUE DUG DUN DUO DYE " +
  "EAR EAT EBB EEL EGG EGO ELF ELK ELM EMU END ERA EVE EWE EYE " +
  "FAD FAN FAR FAT FAX FED FEE FEN FEW FIB FIG FIN FIR FIT FIX FLU FLY FOB FOE FOG FOR FOX FRO FRY FUN FUR " +
  "GAB GAG GAL GAP GAS GAY GEE GEL GEM GET GIG GIN GNU GOD GOO GOT GUM GUN GUT GUY GYM " +
  "HAD HAG HAH HAM HAS HAT HAY HEM HEN HER HEW HEX HEY HID HIM HIP HIS HIT HOB HOE HOG HOP HOT HOW HUB HUE HUG HUM HUT " +
  "ICE ICY ILL IMP INK INN ION IRE IVY " +
  "JAB JAM JAR JAW JAY JET JIG JOB JOG JOT JOY JUG JUT " +
  "KEG KEN KEY KID KIN KIT " +
  "LAB LAD LAG LAP LAW LAX LAY LEA LED LEE LEG LET LID LIE LIP LIT LOB LOG LOO LOP LOT LOW LUG LYE " +
  "MAC MAD MAN MAP MAR MAT MAW MAX MAY MEN MET MID MIX MOB MOD MOM MOO MOP MOW MUD MUG MUM " +
  "NAB NAG NAH NAP NAY NET NEW NIB NIL NIP NIT NOB NOD NOR NOT NOW NUB NUN NUT " +
  "OAF OAK OAR OAT ODD ODE OFF OFT OHM OIL OLD ONE OPT ORB ORE OUR OUT OWE OWL OWN " +
  "PAD PAL PAN PAR PAT PAW PAY PEA PEE PEG PEN PEP PER PET PEW PIE PIG PIN PIT PLY POD POI POP POT POW PRO PRY PUB PUG PUN PUP PUS PUT " +
  "RAG RAM RAN RAP RAT RAW RAY RED REF REP RIB RID RIG RIM RIP ROB ROD ROE ROT ROW RUB RUE RUG RUM RUN RUT RYE " +
  "SAC SAD SAG SAP SAT SAW SAX SAY SEA SEE SET SEW SHE SIN SIP SIR SIS SIT SIX SKI SKY SLY SOB SOD SON SOP SOT SOW SOY SPA SPY SUB SUM SUN SUP " +
  "TAB TAD TAG TAN TAP TAR TAT TAX TEA TEE TEN THE THY TIC TIE TIN TIP TOE TOG TON TOO TOP TOT TOW TOY TRY TUB TUG TUN TUT TWO " +
  "UGH UMP UNI URN USE " +
  "VAN VAT VET VEX VIA VIE VOW " +
  "WAD WAG WAN WAR WAS WAX WAY WEB WED WEE WET WHO WHY WIG WIN WIT WOE WOK WON WOO WOW " +
  "YAK YAM YAP YAW YEA YEP YES YET YEW YIN YON YOU YOW " +
  "ZAG ZAP ZED ZEN ZIG ZIP ZIT ZOO " +
  // 4-letter (~700)
  "ABLE ABLY ACED ACES ACHE ACID ACME ACNE ACRE ACTS ADDS AFAR AGED AGES AGOG AIDE AIDS AILS AIMS AIRS AIRY AJAR AKIN ALAS ALES ALLY ALMS ALOE ALSO ALTO AMID AMMO AMOK AMPS ANEW ANTI ANTS ANUS APED APEX APSE AQUA ARCH ARCS AREA ARES ARID ARMS ARMY ARTS ARTY ASHY ASKS ATOM ATOP AUNT AURA AUTO AVID AVOW AWED AWES AWOL AXED AXES AXIS AXLE AYES " +
  "BABE BABY BACK BADE BAGS BAIL BAIT BAKE BALD BALE BALL BALM BAND BANE BANG BANK BARB BARD BARE BARK BARN BARS BASE BASH BASK BASS BATE BATH BATS BAUD BAWL BEAD BEAK BEAM BEAN BEAR BEAT BEDS BEEF BEEN BEER BEES BEET BELL BELT BEND BENT BEST BETS BEVY BIAS BIDE BIDS BIKE BILE BILK BILL BIND BIOS BIRD BITE BITS BLAB BLED BLEW BLIP BLOB BLOC BLOT BLOW BLUE BLUR BOAR BOAT BODE BODY BOIL BOLD BOLE BOLT BOMB BOND BONE BONG BONY BOOK BOOM BOON BOOR BOOT BORE BORN BOSS BOTH BOUT BOWL BOWS BOXY BOYS BRAG BRAN BRAS BRAT BRAY BRED BREW BRIM BROW BUCK BUDS BUFF BULB BULK BULL BUMP BUNK BUNS BUOY BURL BURN BURP BURR BURY BUSH BUSY BUTT BUYS BUZZ BYES " +
  "CABS CADS CAFE CAGE CAGY CAKE CALF CALL CALM CAME CAMP CANE CANS CAPE CAPS CARD CARE CARP CARS CART CASE CASH CAST CATS CAVE CAWS CEDE CELL CHAP CHAR CHAT CHEF CHEW CHIC CHIN CHIP CHIT CHOP CHUB CHUG CITE CITY CLAD CLAM CLAN CLAP CLAW CLAY CLEF CLIP CLOD CLOG CLOP CLOT CLOY CLUB CLUE COAL COAT COAX COBS COCK COCO CODE CODS COIL COIN COKE COLA COLD COLT COMA COMB COME CONE CONK CONS COOK COOL COON COOP COOS COOT COPE COPS COPY CORD CORE CORK CORN COST COTS COUP COVE COWL COWS COZY CRAB CRAG CRAM CRAW CREW CRIB CROP CROW CRUD CUBE CUBS CUED CUES CUFF CULL CULT CURB CURD CURE CURL CURS CURT CUSP CUTE CUTS " +
  "DABS DADS DAFT DAIS DALE DAME DAMN DAMP DAMS DARE DARK DART DASH DATA DATE DAUB DAWN DAYS DAZE DEAD DEAF DEAL DEAN DEAR DEBT DECK DEED DEEM DEEP DEER DEFT DEFY DELL DELI DEMO DENS DENT DENY DESK DEWS DEWY DIAL DICE DIED DIES DIET DIGS DILL DIME DIMS DINE DING DINS DINT DIPS DIRE DIRT DISC DISH DISK DITS DIVA DIVE DOCK DOES DOGS DOJO DOLE DOLL DOME DONE DONS DOOM DOOR DOPE DOSE DOTE DOTS DOVE DOWN DOZE DRAB DRAG DRAM DRAW DREW DRIP DROP DRUG DRUM DUAL DUDE DUDS DUEL DUES DUET DUKE DULL DUMB DUMP DUNE DUNG DUNK DUNS DUOS DUPE DUSK DUST DUTY DYED DYER DYES " +
  "EACH EARL EARN EARS EASE EAST EASY EATS EBBS EDDY EDGE EDGY EDIT EELS EGGS EGGY EGOS EKED EKES ELAN ELKS ELMS ELSE EMIR EMIT EMUS ENDS ENVY EONS EPIC EPOCH ERAS ERGO ERGS ERRS EURO EVEN EVER EVES EVIL EWER EWES EXAM EXEC EXES EXIT EYED EYES " +
  "FACE FACT FADE FADS FAIL FAIN FAIR FAKE FALL FAME FANG FANS FARE FARM FAST FATE FATS FAUN FAWN FAZE FEAR FEAT FEED FEEL FEES FEET FELL FELT FEND FERN FETA FEUD FIBS FIEF FIFE FIGS FILE FILL FILM FINE FINS FIRE FIRM FIRS FISH FIST FITS FIVE FIZZ FLAG FLAK FLAP FLAT FLAW FLAX FLEA FLED FLEE FLEW FLEX FLIP FLIT FLOG FLOP FLOW FLUB FLUE FLUX FOAL FOAM FOBS FOCI FOES FOGS FOGY FOIL FOLD FOLK FOND FONT FOOD FOOL FOOT FORD FORE FORK FORM FORT FOUL FOUR FOWL FOXY FRAY FREE FRET FRIG FROM FUEL FULL FUME FUMY FUND FUNK FURL FURS FURY FUSE FUSS FUZZ " +
  "GABS GAFF GAGE GAGS GAIN GAIT GALA GALE GALL GALS GAME GANG GAPE GAPS GARB GASH GASP GATE GAVE GAWK GAYS GAZE GEAR GEES GELS GEMS GENE GENS GENT GERM GETS GIBE GIFT GIGS GILD GILL GILT GIRD GIRL GIST GIVE GLAD GLEE GLEN GLIB GLOB GLOM GLOP GLOW GLUE GLUM GLUT GNAR GNAW GOAD GOAL GOAT GODS GOER GOES GOGO GOLD GOLF GONE GONG GOOD GOOF GOON GOOP GORE GORY GOSH GOUT GOWN GRAB GRAD GRAM GRAY GREW GREY GRID GRIM GRIN GRIP GRIT GROG GROW GRUB GULF GULL GULP GUMS GUNK GUNS GURU GUSH GUST GUTS GUYS GYMS GYPS GYRE " +
  "HACK HAIL HAIR HALE HALF HALL HALO HALT HAND HANG HANK HARD HARE HARK HARM HARP HASH HASP HATE HATH HATS HAUL HAVE HAWK HAYS HAZE HAZY HEAD HEAL HEAP HEAR HEAT HECK HEED HEEL HEFT HEIR HELD HELL HELM HELP HEMP HEMS HENS HERB HERD HERE HERO HERS HEWN HEWS HICK HIDE HIES HIGH HIKE HILL HILT HIND HINT HIPS HIRE HISS HITS HIVE HOAR HOAX HOBO HOBS HOCK HOES HOGS HOLD HOLE HOLY HOME HONE HONK HOOD HOOF HOOK HOOP HOOT HOPE HOPS HORN HOSE HOST HOUR HOWL HUBS HUED HUES HUFF HUGE HUGS HULA HULK HULL HUMP HUMS HUNG HUNK HUNT HURL HURT HUSH HUSK HUTS HYMN HYPE " +
  "IBEX IBIS ICED ICES ICKY ICON IDEA IDLE IDLY IDOL IFFY IKAT ILKS ILLS IMAM IMPS INCH INKS INKY INNS INTO IONS IOTA IRES IRIS IRKS IRON ISLE ITCH ITEM IVES IVORY " +
  "JABS JACK JADE JAGS JAIL JAMB JAMS JAPE JARS JAWS JAYS JAZZ JEEP JEER JEFE JELL JERK JEST JETS JIBE JIBS JIFF JIGS JILT JINX JOBS JOCK JOEY JOGS JOIN JOKE JOLT JOSH JOTS JOWL JOYS JUDO JUGS JUJU JUMP JUNK JURY JUST JUTS " +
  "KALE KALI KAYS KEEL KEEN KEEP KEGS KELP KEPT KEYS KICK KIDS KILL KILN KILO KILT KIND KINE KING KINK KINS KIRK KISS KITE KITH KITS KIWI KNEE KNEW KNIT KNOB KNOT KNOW KOAN KOHL KOOK KUDO " +
  "LABS LACE LACK LACY LADE LADS LADY LAID LAIN LAIR LAKE LAMB LAME LAMP LAND LANE LANK LAPS LARD LARK LASH LASS LAST LATE LATH LAUD LAVA LAVE LAWN LAWS LAYS LAZE LAZY LEAD LEAF LEAK LEAN LEAP LEAR LEAS LEER LEFT LEGS LEND LENS LENT LESS LEST LETS LEVY LEWD LIAR LICE LICK LIDO LIDS LIED LIEF LIEN LIES LIEU LIFE LIFT LIKE LILT LILY LIMA LIMB LIME LIMN LIMO LIMP LIMY LINE LINK LINT LION LIPS LIRA LISP LIST LITE LIVE LOAD LOAF LOAM LOAN LOBE LOBO LOBS LOCH LOCI LOCK LODE LOFT LOGE LOGO LOGS LOIN LOLL LOLO LONE LONG LOOK LOOM LOON LOOP LOOS LOOT LOPE LOPS LORD LORE LOSE LOSS LOST LOTI LOTS LOUD LOUR LOUT LOVE LOWS LUAU LUBE LUCK LUGE LUGS LULL LULU LUMP LUNG LURE LURK LUSH LUST LUTE LYES LYNX LYRE " +
  "MACE MACH MACK MADE MAGE MAGI MAID MAIL MAIM MAIN MAKE MALE MALL MALT MAMA MANE MANY MAPS MARE MARK MARL MARS MART MASH MASK MASS MAST MATE MATH MATS MAUL MAWS MAYO MAZE MEAD MEAL MEAN MEAT MEEK MEET MELD MELT MEME MEMO MEND MENU MEOW MERE MESA MESH MESS METE METS MEWS MICA MICE MIDS MIFF MIKE MILD MILE MILK MILL MILS MIME MIMI MIND MINE MINI MINK MINT MINX MIRE MIRY MISO MISS MIST MITE MITT MIXT MOAN MOAT MOBS MOCK MODE MODS MOJO MOLD MOLE MOLT MOMS MOMA MONK MOOD MOON MOOR MOOS MOOT MOPE MOPS MORE MORN MOSS MOST MOTE MOTH MOTS MOUE MOVE MOWN MOWS MUCH MUCK MUDS MUFF MUGS MULE MUMS MUNS MURK MUSE MUSH MUSK MUSS MUST MUTE MUTT MYTH " +
  "NABS NAIL NAME NANS NAPE NAPS NARC NARY NAVE NAVY NAYS NEAR NEAT NECK NEED NEON NERD NESS NEST NETS NEUE NEVI NEWS NEWT NEXT NIBS NICE NICK NIGH NILS NIMH NINE NIPS NITS NOBS NOCK NODE NODS NOEL NONE NOOK NOON NOPE NORM NOSE NOSH NOSY NOTE NOUN NOVA NUBS NUDE NUKE NULL NUMB NUNS NURD NUTS " +
  "OAFS OAKS OARS OATH OATS OBEY OBOE OCAS ODDS ODES ODOR OFFS OGLE OGRE OILS OILY OINK OKAY OKRA OLDS OLEO OMEN OMIT ONCE ONES ONLY ONTO ONUS OOZE OOZY OPAL OPED OPEN OPES OPTS OPUS ORAL ORBS ORCA ORES OUCH OURS OUST OUTS OVAL OVEN OVER OWED OWES OWLS OWNS OXEN " +
  "PACE PACK PACT PADS PAGE PAID PAIL PAIN PAIR PALE PALL PALM PALP PALS PANE PANG PANS PAPA PAPS PARE PARK PARS PART PASS PAST PATE PATH PATS PAVE PAWN PAWS PAYS PEAK PEAL PEAR PEAS PECK PEED PEEK PEEL PEEN PEEP PEER PEGS PELT PEND PENS PEON PEPS PERK PERM PERT PEST PETS PEWS PHIS PIAS PICA PICK PIED PIER PIES PIGS PIKE PILE PILL PIMP PINE PING PINK PINS PINT PIPE PIPS PISO PITA PITH PITS PITY PLAN PLAT PLAY PLEA PLED PLOD PLOP PLOT PLOW PLOY PLUG PLUM PLUS POCK PODS POEM POET POGO POIS POKE POLE POLL POLO POLY POMP POND PONS PONY POOH POOL POOP POOR POPE POPS PORE PORK PORN PORT POSE POSH POST POSY POTS POUR POUT PRAY PREP PREY PREZ PRIG PRIM PROD PROM PROP PROS PROW PSIS PUBS PUCK PUDS PUFF PUGS PUKE PULL PULP PULS PUMA PUMP PUNG PUNK PUNS PUNT PUNY PUPA PUPS PURE PURL PURR PUSS PUTS PUTT PYRE " +
  "QUAD QUAY QUID QUIP QUIT QUIZ QUOD " +
  "RACE RACK RACY RAFT RAGE RAGS RAID RAIL RAIN RAJA RAKE RAMP RAMS RANG RANI RANK RANT RAPE RAPS RAPT RARE RASH RASP RATE RATH RATS RAVE RAYS RAZE RAZZ READ REAL REAM REAP REAR REDO REDS REED REEF REEK REEL REIN REND RENT RESH REST RETS REVS RHEA RIAL RIBS RICE RICH RICK RIDE RIDS RIFE RIFF RIFT RIGS RILE RILL RIME RIMS RIND RING RINK RIOT RIPE RIPS RISE RISK RITE RITZ ROAD ROAM ROAN ROAR ROBE ROBS ROCK RODE RODS ROES ROIL ROLE ROLL ROMP ROOF ROOK ROOM ROOT ROPE ROPY ROSE ROSY ROTE ROTS ROUE ROUT RUBE RUBS RUBY RUDE RUED RUES RUFF RUGS RUIN RULE RUMP RUNE RUNG RUNS RUNT RUSE RUSH RUSK RUST RUTH RUTS RYES " +
  "SACK SACS SAFE SAGA SAGE SAGS SAID SAIL SAKE SALE SALT SAME SAND SANE SANG SANK SAPS SARI SASH SASS SATE SAVE SAWS SAYS SCAB SCAD SCAM SCAN SCAR SCAT SCOT SCOW SCUM SEAL SEAM SEAR SEAS SEAT SECT SEED SEEK SEEM SEEN SEEP SEES SELF SELL SEMI SEND SENT SERF SETS SEWN SEWS SEXY SHAD SHAG SHAM SHED SHEW SHIM SHIN SHIP SHIV SHOD SHOE SHOO SHOP SHOT SHOW SHUN SHUT SIBS SICK SIDE SIFT SIGH SIGN SILK SILL SILO SILT SIMS SINE SING SINK SINS SIPS SIRE SIRS SITE SITS SIZE SKID SKIM SKIN SKIP SKIS SKIT SKUA SLAB SLAG SLAM SLAP SLAT SLAW SLAY SLED SLEW SLID SLIM SLIP SLIT SLOB SLOE SLOG SLOP SLOT SLOW SLUG SLUM SLUR SMOG SMUG SNAG SNAP SNIP SNIT SNOB SNOT SNOW SNUB SNUG SOAK SOAP SOAR SOBS SOCK SODA SODS SOFA SOFT SOIL SOLD SOLE SOLI SOLO SOME SONG SONS SOON SOOT SOPS SORE SORT SOUL SOUP SOUR SOWN SOWS SPAN SPAR SPAS SPAT SPAY SPED SPEW SPIN SPIT SPRY SPUD SPUN SPUR STAB STAG STAR STAT STAY STEM STEP STEW STIR STOP STOW STUB STUD STUN SUBS SUCH SUCK SUDS SUED SUES SUET SUGE SUIT SULK SUMS SUNG SUNK SUNS SUPS SURE SURF SUSS SWAB SWAG SWAM SWAN SWAP SWAT SWAY SWIG SWIM SWUM SYNC " +
  "TABS TACK TACO TACT TADS TAGS TAIL TAKE TALC TALE TALK TALL TAME TAMP TANG TANK TANS TAPE TAPS TARE TARN TARO TARP TARS TART TASK TATS TAUT TAXI TBSP TEAK TEAL TEAM TEAR TEAS TEAT TEED TEEN TEES TEMP TEND TENS TENT TERM TERN TEST TEXT THAN THAT THAW THEE THEM THEN THEW THEY THIN THIS THOU THUD THUG THUS TICK TIDE TIDY TIED TIER TIES TIFF TIKE TILE TILL TILT TIME TINE TINS TINT TINY TIPS TIRE TIRO TITI TODY TOES TOFF TOFU TOGA TOGS TOIL TOLD TOLE TOLL TOMB TOME TONE TONG TONS TOOK TOOL TOON TOOT TOPI TOPS TORC TORE TORN TORO TORT TORY TOSS TOTE TOTS TOUR TOUT TOWN TOWS TOYS TRAM TRAP TRAY TREE TREK TRIG TRIM TRIO TRIP TROD TROT TROY TRUE TRUG TSAR TSKS TUBA TUBE TUBS TUCK TUFA TUFF TUFT TUGS TULE TUMS TUNA TUNE TURD TURF TURN TUSH TUSK TUTS TWAT TWIG TWIN TWIT TYKE TYPE TYPO TZAR " +
  "UDON UDOS UGLY ULNA UMBO UMPS UNDO UNDY UNIT UNTO UPDO UPON URBS URGE URNS USED USER USES " +
  "VAIN VALE VAMP VANE VANS VARY VASE VAST VATS VEAL VEEP VEER VEIL VEIN VEND VENT VERB VERY VEST VETO VETS VEXT VIAL VIBE VICE VIDS VIED VIES VIEW VILE VINE VINO VINY VIOL VISA VISE VITA VIVA VOID VOLE VOLT VOTE VOWS " +
  "WADE WADI WADS WAFT WAGE WAGS WAIF WAIL WAIN WAIT WAKE WALK WALL WAND WANE WANG WANK WANT WAR WARD WARE WARM WARN WARP WARS WART WARY WASH WASP WAST WATS WATT WAVE WAVY WAWL WAXY WAYS WEAK WEAL WEAN WEAR WEBS WEDS WEED WEEK WEEP WEES WEFT WEIR WELD WELL WELT WEND WENS WENT WEPT WERE WEST WETS WHAM WHAT WHEE WHEN WHET WHEW WHEY WHIG WHIM WHIP WHIR WHIT WHIZ WHOA WHOM WHOP WHOS WICK WIDE WIFE WIGS WILD WILE WILL WILT WILY WIMP WIND WINE WING WINK WINO WINS WINY WIPE WIRE WIRY WISE WISH WISP WITH WITS WIVE WOAD WOES WOKE WOKS WOLD WOLF WOMB WONK WONT WOOD WOOF WOOL WOOS WORD WORE WORK WORM WORN WORT WOST WOTS WOVE WOWS WRAP WREN WRIT WUSS " +
  "XYST " +
  "YACK YAGI YAKS YAMS YANG YANK YAPS YARD YARE YARN YAWL YAWN YAWS YEAH YEAR YEAS YELL YELP YENS YEPS YETI YEWS YIPE YIPS YOGA YOGI YOKE YOLK YORE YOUR YOWL YULE YUMS YURT " +
  "ZAGS ZANY ZAPS ZEAL ZEDS ZEES ZERO ZEST ZETA ZIGS ZILL ZINC ZINE ZING ZIPS ZITI ZITS ZONE ZOOM ZOOS " +
  // 5-letter (~850)
  "ABACK ABASE ABATE ABBEY ABBOT ABETS ABHOR ABIDE ABLED ABLER ABLES ABODE ABORT ABOUT ABOVE ABUSE ABUTS ABYSS ACERB ACHED ACHES ACIDS ACING ACMES ACNES ACORN ACRES ACTED ACTOR ACUTE ADAGE ADAPT ADDED ADDER ADDLE ADIEU ADIOS ADITS ADMIT ADOBE ADOPT ADORE ADORN ADULT AERIE AFIRE AFOOT AFOUL AFTER AGAIN AGAPE AGATE AGAVE AGENT AGGRO AGILE AGING AGLOW AGONY AGREE AHEAD AIDED AIDER AIDES AILED AIMED AIMER AIOLI AIRED AISLE AKELA ALARM ALBUM ALERT ALGAE ALIAS ALIBI ALIEN ALIGN ALIKE ALIVE ALLAY ALLEY ALLOT ALLOW ALLOY ALMOST ALOES ALOFT ALOHA ALONE ALONG ALOOF ALOUD ALPHA ALTAR ALTER ALTOS ALUMS AMASS AMAZE AMBER AMBIT AMBLE AMEND AMENS AMICE AMIGO AMINO AMISS AMITY AMONG AMORE AMOUR AMPED AMPLE AMPLY AMUSE ANGEL ANGER ANGLE ANGRY ANGST ANISE ANKLE ANNEX ANNOY ANNUL ANTED ANTES ANTIC ANTIS ANVIL AORTA APACE APART APING APNEA APPLE APPLY APRES APRIL APRON APSIS APTLY AQUAS ARBOR ARCED ARDOR AREAS ARENA AREAS ARGON ARGOT ARGUE ARISE ARMED ARMOR AROMA AROSE ARRAY ARROW ARSON ASIDE ASKED ASKEW ASPEN ASSAY ASSES ASSET ASTER ASTIR ATLAS ATOLL ATOMS ATONE ATRIA ATTIC AUDIO AUDIT AUNTS AUNTY AURAS AVAIL AVERT AVIAN AVOID AWAIT AWAKE AWARD AWARE AWASH AWFUL AWOKE AXIOM AXION AZURE " +
  "BABEL BABES BABYS BACON BADGE BADLY BAGEL BAGGY BAILS BAITS BAKED BAKER BAKES BALDS BALDY BALES BALMS BALMY BANAL BANDS BANDY BANES BANGS BANJO BANKS BARBS BARDS BARED BARES BARGE BARKS BARMY BARNS BARON BASAL BASED BASES BASIC BASIL BASIN BASIS BASKS BASTE BATCH BATED BATES BATHE BATHS BATIK BATON BATTY BAWDY BAWLS BAYED BAYOU BEACH BEADS BEADY BEAKS BEAMS BEANS BEARS BEAST BEATS BEAUT BEAUX BEEFS BEEFY BEEPS BEERS BEERY BEETS BEFIT BEFOG BEGAN BEGET BEGIN BEGOT BEGUN BEIGE BEING BELCH BELIE BELLE BELLS BELLY BELOW BELTS BENCH BENDS BERET BERMS BERRY BERTH BESET BESTS BESTOW BETAS BETEL BETHS BETIDE BETTY BEVEL BEZEL BIAS BIBBS BIBLE BICEP BIDDY BIDED BIDES BIGOT BIJOU BIKER BIKES BILES BILGE BILKS BILLS BILLY BIMBO BINGE BINGO BIOME BIPED BIRCH BIRDS BIRTH BISON BITCH BITER BITES BITTY BLABS BLACK BLADE BLAME BLAND BLANK BLARE BLASE BLAST BLAZE BLEAK BLEAR BLEAT BLEED BLEEP BLEND BLESS BLEST BLIMP BLIND BLING BLINK BLIPS BLISS BLITZ BLOAT BLOBS BLOCK BLOND BLOOD BLOOM BLOTS BLOWN BLOWS BLUES BLUFF BLUNT BLURB BLURT BLUSH BOARD BOARS BOAST BOATS BOBBY BODES BODY BOGEY BOGGY BOGUS BOILS BOLDS BOLES BOLLS BOLTS BOMBS BONDS BONER BONES BONEY BONGO BONGS BONKS BONUS BOOBS BOOBY BOOED BOOKS BOOMS BOONS BOORS BOOST BOOTH BOOTS BOOTY BOOZE BOOZY BORED BORER BORES BORNE BORON BOSOM BOSSY BOTCH BOUGH BOULE BOUND BOUTS BOWED BOWEL BOWER BOWLS BOXED BOXER BOXES BRACE BRAGS BRAID BRAIN BRAKE BRAND BRANS BRASH BRASS BRATS BRAVE BRAVO BRAWL BRAWN BRAZE BREAD BREAK BREAM BREED BREVE BREWS BRIBE BRICK BRIDE BRIEF BRIGS BRIM BRINE BRING BRINK BRINY BRISK BROAD BROIL BROKE BROOD BROOK BROOM BROTH BROW BROWN BRRR BRUNT BRUSH BRUTE BUCKS BUDDY BUDGE BUFFS BUFFY BUGGY BUGLE BUILD BUILT BULBS BULGE BULKS BULKY BULLS BULLY BUMPS BUMPY BUNCH BUNDT BUNGS BUNKS BUNNY BUNTS BUOYS BURGS BURLY BURNS BURPS BURRO BURRS BURRY BURST BURY BUSED BUSES BUSHY BUSKS BUSTS BUSTY BUTCH BUTTS BUTTE BUYER BYLAW BYTES " +
  "CABAL CABBY CABIN CABLE CACAO CACHE CADDY CADET CAGED CAGES CAGEY CAIRN CAKED CAKES CALLS CALMS CAMEL CAMEO CAMPS CAMPY CANAL CANDY CANED CANES CANNA CANNY CANOE CAPER CAPES CAPS CARAT CARBS CARDS CARED CARER CARES CARGO CAROB CAROL CARP CARPS CARRY CARTS CARVE CASED CASES CASKS CASTE CASTS CATCH CATER CATTY CAULK CAUSE CAVED CAVES CAVIL CEASE CEDAR CEDED CEDES CELLO CELLS CENTS CHAFE CHAFF CHAIN CHAIR CHALK CHAMP CHANG CHANT CHAPS CHAPT CHARD CHARM CHARS CHART CHARY CHASE CHASM CHAT CHATS CHEAP CHEAT CHECK CHEEK CHEEP CHEER CHEFS CHEMO CHESS CHEST CHEWS CHEWY CHICK CHIDE CHIEF CHILD CHILE CHILI CHILL CHIME CHIMP CHINA CHINK CHINS CHIPS CHIRP CHITS CHIVE CHOCK CHOIR CHOKE CHOMP CHOPS CHORD CHORE CHOSE CHOWS CHUBS CHUCK CHUFA CHUFF CHUGS CHUMP CHUMS CHUNK CHURN CHUTE CIDER CIGAR CINCH CIRCA CITED CITES CIVIC CIVIL CLACK CLADS CLAIM CLAMP CLAMS CLANG CLANK CLANS CLAPS CLASH CLASP CLASS CLAUSE CLAWS CLAYS CLEAN CLEAR CLEAT CLEFT CLERK CLEWS CLICK CLIFF CLIMB CLIME CLING CLINK CLIPS CLIPT CLOAK CLOCK CLODS CLOGS CLOMP CLONE CLOSE CLOTH CLOTS CLOUD CLOUT CLOVE CLOWN CLOYS CLUBS CLUCK CLUED CLUES CLUMP CLUNG COACH COALS COAST COATS COAXS COBBS COBRA COCKS COCOA CODED CODER CODES COFFEE COIFS COILS COINS COKED COKES COLAS COLDS COLON COLTS COMAS COMBO COMBS COMER COMES COMET COMFY COMIC CONCH CONDO CONES CONGA CONGO CONIC CONKS CONUS COPED COPES COPRA COPSE CORAL CORDS CORED CORER CORES CORKS CORMS CORNS CORNY CORPS COSTS COUGH COULD COUNT COUPE COUPS COURT COVER COVES COVET COVEY COWED COWLS COZEN COZILY CRABS CRACK CRAFT CRAGS CRAMP CRAMS CRANE CRANK CRAPS CRASH CRASS CRATE CRAVE CRAWL CRAWS CRAZE CRAZY CREAK CREAM CREDO CREDS CREED CREEK CREEL CREEP CREME CRESS CREST CREWS CRICK CRIED CRIER CRIES CRIME CRIMP CRISP CROAK CROCK CROFT CRONE CRONY CROOK CROON CROPS CROSS CROUP CROWD CROWN CROWS CRUDE CRUEL CRUET CRUMB CRUSH CRUST CRYPT CUBED CUBES CUBIC CUBIT CUFFS CULPA CULTS CUMIN CURBS CURDS CURDY CURED CURES CURIO CURLS CURLY CURSE CURVE CURVY CUTER CYCLE CYNIC " +
  "DABBY DADDY DAILY DAIRY DAISY DAMES DAMNS DAMPS DANCE DANDY DANED DANED DANES DARED DARES DARNS DARTS DASHY DATED DATES DATUM DAUBS DAUNT DAWNS DAZED DAZES DEALS DEALT DEARS DEARY DEATH DEBAR DEBIT DEBTS DEBUG DEBUT DECAF DECAL DECAY DECKS DECOR DECOY DECRY DEEDS DEEMS DEEPS DEERS DEFER DEFOG DEIFY DEIGN DEISM DEIST DEITY DELAY DELFT DELIS DELLS DELTA DELVE DEMOS DENIM DENSE DENTS DEPOT DEPTH DERBY DERIC DERIDE DERMS DESKS DETER DETOX DEUCE DEVIL DEWY DIALS DIARY DICED DICER DICES DICEY DICKS DIDOS DIETS DIGIT DIKED DIKES DIMER DIMES DIMLY DINER DINES DINGO DINGS DINGY DINKY DIPPY DIRGE DIRKS DIRTY DISCO DISCS DISKS DITCH DITTO DITTY DITZY DIVAN DIVAS DIVED DIVER DIVES DIVOT DIVVY DIZZY DOCKS DODGE DODGY DOERS DOGES DOGGY DOING DOLES DOLLS DOLLY DOLTS DOMED DOMES DONOR DONUT DOPED DOPES DOPEY DORKS DORKY DORMS DORSA DOSED DOSES DOTED DOTES DOTTY DOUBT DOUGH DOUSE DOVES DOWDY DOWEL DOWNS DOWNY DOWRY DOZED DOZEN DOZES DOZER DRABS DRAFT DRAGS DRAIN DRAKE DRAMA DRAMS DRANK DRAPE DRAWL DRAWN DRAWS DRAYS DREAD DREAM DREAR DREDGE DREGS DRESS DREW DRIBS DRIED DRIER DRIES DRIFT DRILL DRINK DRIPS DRIVE DROIT DROLL DRONE DROOL DROOP DROPS DROSS DROVE DROWN DRUBS DRUGS DRUID DRUMS DRUNK DRUPE DRYER DRYLY DUALS DUCAL DUCAT DUCHY DUCKS DUCKY DUDES DUDS DUELS DUETS DUKES DULCY DULLS DULLY DUMBO DUMBS DUMMY DUMPS DUMPY DUNCE DUNES DUNGS DUPED DUPES DURUM DUSKS DUSKY DUSTS DUSTY DUTCH DUVET DWARF DWELL DWELT DYERS DYING DYKES " +
  "EAGER EAGLE EARED EARLS EARLY EARNS EARTH EASED EASEL EASES EATEN EATER EAVES EBBED EBONY ECHED ECHOS ECRU EDDIE EDGED EDGES EDIFY EDITS EDUCE EERIE EGGED EGRET EIDER EIGHT EJECT EKED EKING ELAND ELATE ELBOW ELDER ELECT ELEGY ELEMI ELFIN ELITE ELIXIR ELOPE ELUDE ELVES EMAIL EMBED EMBER EMCEE EMERY EMITS EMOTE EMPTY EMUS ENACT ENDED ENDOW ENEMA ENEMY ENJOY ENNUI ENROL ENSUE ENTER ENTRY ENVOY EPICS EPOCH EPOXY EQUAL EQUIP ERASE ERECT ERGOT ERODE ERRED ERROR ERUPT ESPYS ESSAY ESSES ESTOP ETHIC ETHOS EULOGY EVADE EVENT EVERY EVICT EVILS EVOKE EWERS EXACT EXALT EXAMS EXCEL EXIST EXITS EXPEL EXTOL EXTRA EXUDE EXULT EYING " +
  "FABLE FACED FACER FACES FACET FACTS FADED FADES FAGOT FAILS FAINT FAIRS FAIRY FAITH FAKED FAKER FAKES FALLS FALSE FAMED FAMES FANCY FANGS FANNY FARCE FARED FARES FARMS FATED FATES FATTY FAULT FAUNS FAVOR FAWNS FAXED FAXES FAZED FAZES FEARS FEAST FEATS FECES FEEDS FEELS FEIGN FEINT FELLA FELLS FELLY FELON FELTS FEMME FEMUR FENCE FENDS FERAL FERNS FERRY FESTS FETCH FETED FETES FETID FEUDS FEVER FEWER FEZ FIBER FIBRE FICUS FIEFS FIELD FIEND FIERY FIFE FIFER FIFES FIFTH FIFTY FIGHT FILCH FILED FILER FILES FILET FILLS FILLY FILMS FILMY FILTH FINAL FINCH FINDS FINED FINER FINES FIORD FIRED FIRER FIRES FIRMS FIRST FIRTH FISHY FISTS FITLY FIVER FIVES FIXED FIXER FIXES FIZZY FJORD FLABS FLACK FLAGS FLAIL FLAIR FLAKE FLAKY FLAME FLAMS FLANK FLAPS FLARE FLASH FLASK FLATS FLAWS FLEAS FLECK FLEET FLESH FLEWS FLICK FLIED FLIER FLIES FLING FLINT FLIPS FLIRT FLITS FLOAT FLOCK FLOES FLOG FLOGS FLOOD FLOOR FLOPS FLORA FLOSS FLOUR FLOUT FLOWN FLOWS FLUBS FLUES FLUFF FLUFFY FLUID FLUKE FLUNG FLUSH FLUTE FLY FLYER FOALS FOAMS FOAMY FOCAL FOCUS FOGEY FOGGY FOIBLE FOILS FOIST FOLDS FOLIO FOLKS FOLLY FONDS FONTS FOOLS FORAY FORDS FOREST FORGE FORGO FORKS FORMS FORTE FORTH FORTS FORTY FORUM FOULS FOUND FOUNT FOURS FOWLS FOYER FRAIL FRAME FRANC FRANK FRATS FRAUD FRAYS FREAK FREED FREES FRESH FRETS FRIAR FRIED FRIES FRIGS FRILL FRISK FRITZ FROCK FROG FROGS FROLIC FROND FRONT FROST FROTH FROWN FROZE FRUIT FRUMP FRYER FUDGE FUELS FUGUE FULLS FULLY FUMED FUMES FUNDS FUNDY FUNGI FUNKY FUNNY FURLS FURRY FURZE FUSED FUSES FUSSY FUZZY " +
  "GABLE GAFFE GAILY GAINS GAITS GALAS GALES GALLS GAMED GAMES GAMER GAMMA GAMUT GANDER GANGS GANGS GAPED GAPER GAPES GARB GARBS GARNI GASES GASLIT GASPS GASSY GATED GATES GAUDY GAUGE GAUNT GAUZE GAUZY GAVEL GAWKS GAWKY GAYER GAYLY GAZED GAZER GAZES GEARS GECKO GEEKS GEEKY GEESE GEEZ GELLS GEMMY GENERS GENES GENIE GENII GENRE GENT GENTS GENUS GERMS GERMY GHAUT GHEE GHOST GIANT GIBED GIBES GIDDY GIFTS GIGS GILDS GILLS GILTS GIMP GIRDS GIRLS GIRTH GIVEN GIVER GIVES GIZMO GLADE GLADS GLAND GLARE GLARY GLASS GLAZE GLEAM GLEAN GLENS GLIDE GLINT GLITZ GLOAT GLOBE GLOBS GLOOM GLOOP GLORY GLOSS GLOVE GLOWS GLUED GLUES GLUEY GLUTS GLYPH GNARL GNASH GNATS GNAWS GNOME GOADS GOALS GOATS GODLY GODS GOERS GOETH GOING GOLDS GOLEM GOLFS GONER GOODS GOODY GOOEY GOOFS GOOFY GOONS GOOPS GOOPY GOOSE GORE GORED GORES GORGE GORKY GORSE GOSSIP GOSSY GOTHS GOTTA GOUGE GOURD GOUTS GOUTY GOWN GOWNS GRABS GRACE GRADE GRADS GRAFT GRAIL GRAIN GRAMS GRAND GRANT GRAPE GRAPH GRASP GRASS GRATE GRAVE GRAVY GRAYS GRAZE GREAT GREBE GREED GREEK GREEN GREET GREYS GRIDS GRIEF GRIFT GRILL GRIME GRIMY GRIND GRINS GRIPE GRIPS GRIST GRITS GROAN GROAT GROIN GROOM GROPE GROSS GROUP GROUT GROVE GROWL GROWN GROWS GRUBS GRUEL GRUFF GRUMP GRUNT GUARD GUAVA GUESS GUEST GUFFAW GUIDE GUILD GUILE GUILT GUISE GULCH GULES GULFS GULLS GULLY GULP GULPS GUMMY GUNKY GUNS GUPPY GURUS GUSHY GUSSY GUSTS GUSTY GUTSY GUYS GYMS GYPSY " +
  "HABIT HACKS HADES HAIKU HAILS HAIRS HAIRY HAJI HAKIM HALES HALLO HALLS HALOS HALTS HALVE HAMES HANDS HANDY HANGS HANKY HAPLY HAPPY HARDS HARDY HARES HARKS HARM HARMS HARPS HARPY HARSH HASHED HASHES HASNT HASTE HASTY HATCH HATED HATER HATES HATCH HAULS HAUNT HAVEN HAVOC HAWKS HAYED HAZED HAZEL HAZES HEADS HEADY HEAPS HEARD HEARS HEART HEATH HEATS HEAVE HEAVY HEDGE HEEDS HEELS HEFTY HEIRS HEIST HELLO HELLS HELMS HELPS HEMEN HEMP HENCE HENNA HERBS HERBY HERDS HERESY HERMIT HEROIC HERON HEROS HERTZ HEWED HEWER HEXED HEXES HICKS HIDES HIGHS HIKED HIKER HIKES HILLS HILLY HILTS HINDS HINGE HINTS HIPPO HIPPY HIRED HIRES HISSY HITCH HIVED HIVES HOARD HOARS HOARY HOAXED HOAXES HOBO HOBOS HOCK HOCKS HOIST HOLDS HOLED HOLES HOLEY HOLLY HOMES HOMEY HOMIES HONCHO HONDA HONED HONES HONEY HONKS HONKY HONOR HOODS HOOEY HOOFS HOOKS HOOKY HOOPS HOOTS HOPED HOPES HOPS HORDE HORNS HORNY HORSE HORSY HOSED HOSER HOSES HOSTS HOTEL HOTLY HOUND HOURS HOUSE HOVEL HOVER HOWDY HOWLS HUBBY HUFFY HUGGY HULKS HULLS HUMAN HUMID HUMPS HUMUS HUNCH HUNKS HUNKY HUNTS HURDLE HURLS HURRY HURTS HUSKS HUSKY HUSSY HUTCH HYDRA HYENA HYMNS HYPED HYPER HYPES HYPHEN " +
  "ICIER ICILY ICING ICKY ICONS IDEAL IDEAS IDIOM IDIOT IDLED IDLER IDLES IDLY IDOLS IFFY IGLOO ILEUM ILIAC ILIUM ILLUS IMAGE IMAGO IMBED IMPEL IMPLY IMPRINT IMPS INANE INAPT INBOX INCH INCHES INCUR INDEX INDIE INDOOR INDUCE INEPT INERT INFER INFIX INFOS INGOT INKED INKERS INLAW INLAY INLET INNER INPUT INSET INTER INTRO INURE INVADER INVITE IONIC IONS IOTA IRATE IRES IRIS IRKS IRKED IRONS IRONY ISLES ISLET ISSUE ITCHY ITEMS ITSELF IVIES IVORY " +
  "JACKS JACKY JADED JADES JAGS JAILS JAMBS JAMS JANES JAPED JAPES JARGON JAWED JAY JAYS JAZZY JEANS JEEPS JEERS JELLO JELLY JENNY JERKS JERKY JESTS JESUS JETER JETTY JEWEL JIBED JIBER JIBES JIFFS JIFFY JIGS JIHAD JILTS JINKS JINNI JINKS JIVED JIVES JOBS JOCKS JOINS JOINT JOIST JOKED JOKER JOKES JOKEY JOLLY JOLTS JOSHED JOSHES JOULE JOUST JOWLS JOWLY JOY JOYED JOYS JUDGE JUDGY JUDOS JUICE JUICY JUJUS JUKES JULEP JUMBO JUMPS JUMPY JUNCO JUNGLE JUNKS JUNKY JUNTA JURAT JURIST JURORS JUST " +
  "KABAB KAPOW KAPUT KARAT KAYAK KAYO KAYOS KAZOO KEELS KEEPS KEFIR KELLY KELPS KELVIN KEMPT KENNED KENNELS KEPT KERATIN KETCH KETO KEYED KEYING KEYS KHAKI KHANS KHANS KICKS KIDDO KIDS KIKES KILLS KILNS KILOS KILTS KILTY KINDS KINETICS KINGS KINKS KINKY KIOSK KITED KITES KITHED KITHS KITTY KIWIS KLEPT KLUTZ KNACK KNAVE KNEAD KNEED KNEEL KNEES KNELL KNELT KNIFE KNITS KNOBS KNOCK KNOLL KNOTS KNOWN KNOWS KOALA KOOKS KOOKY KORMA KRAUT KRILL KRONE KUDOS KUDZU " +
  "LABEL LABOR LACED LACES LACKS LACY LADED LADEN LADER LADIES LADLE LADS LAGER LAGS LAID LAIN LAIRS LAKES LAMBS LAMED LAMER LAMES LAMPS LANCE LANDS LANES LANKY LAPEL LAPIS LAPSE LARCH LARDS LARDY LARGE LARGO LARKS LARVA LASED LASER LASES LASHED LASHES LASSO LASTS LATCH LATER LATEX LATHE LATHS LAUDS LAUGH LAVED LAVENDER LAVED LAWNS LAWNY LAYED LAYER LAYUP LAZED LAZES LAZY LEACH LEADS LEAFY LEAKS LEAKY LEANS LEAPS LEAPT LEARN LEASE LEASH LEAST LEAVE LEDGE LEECH LEEKS LEERS LEERY LEFTS LEFTY LEGAL LEGGY LEGS LEMME LEMON LEMUR LENDS LENSE LENT LEPER LESS LEVEE LEVEL LEVER LEVIS LEVY LEWDLY LEYS LIANA LIBEL LIBER LIBRA LICES LICHEN LICKS LIDS LIEDER LIEFS LIENS LIEUS LIFER LIFER LIFE LIFER LIFTS LIGHT LIKED LIKEN LIKER LIKES LILAC LILTS LILY LIMBO LIMBS LIMED LIMES LIMEY LIMIT LIMOS LIMPS LINED LINEN LINER LINES LINGO LINKS LINOS LINTS LIPS LIVED LIVER LIVES LIVID LLAMA LOACH LOADS LOAFS LOAMS LOAMY LOANS LOATH LOBBY LOBES LOBOS LOCAL LOCKS LOCO LOCOS LOCUS LODES LODGE LOFTS LOFTY LOGIC LOGOS LOINS LOLLS LOLLY LONER LONGS LOOKS LOOMS LOONS LOOPS LOOPY LOOSE LOOTS LOPED LOPER LOPES LORDS LORES LORIS LORRY LOSER LOSES LOSSY LOTUS LOUDS LOUIS LOUNG LOUSE LOUSY LOUTS LOVED LOVER LOVES LOWED LOWER LOWLY LUCID LUCKY LUGE LUGED LUGES LULLS LULUS LUMBER LUMPS LUMPY LUNAR LUNCH LUNGE LUNGS LUNKS LURCH LURED LURES LURID LURKED LURKS LUSTS LUSTY LUTES LYING LYMPH LYNCH LYNXES LYRES LYRIC " +
  "MACAW MACED MACES MACHO MACRO MADAM MADLY MAFIA MAGES MAGIC MAGMA MAHJONG MAIDS MAILS MAIM MAIMS MAINS MAJOR MAKER MAKES MALES MALLS MALTS MAMAS MAMBO MAMMA MAMMY MANED MANES MANGE MANGO MANGY MANIA MANIC MANLY MANNA MANOR MANSE MANTA MANY MAPLE MARCH MARES MARKS MARRY MARSH MARTS MARVELOUS MASKS MASON MATCH MATEY MATER MATES MATHS MATTE MAUDLIN MAULS MAVEN MAVIN MAXIM MAYBE MAYFLY MAYHEM MAYO MAYORS MAYORS MAYS MAYST MAZED MAZES MEALS MEANS MEANT MEATY MECCA MEDAL MEDAL MEDIA MEDIC MEDS MEETS MELDS MELEE MELON MELT MELTS MEMOIR MEMOS MENDS MENU MENUS MEOW MEOWS MERCY MERGE MERIT MERRY MESAS MESON MESSY METAL METER METES METHANE METHS MEWED MEZZO MICAS MICRO MIDST MIENS MIFFS MIGHT MIKED MIKES MILDLY MILES MILKS MILKY MILLS MIMED MIMES MIMICS MIMING MINCE MINDS MINED MINER MINES MINIBAR MINIS MINKS MINOR MINTS MINTY MINUS MIRED MIRES MIRTH MISER MISES MISSY MISTS MISTY MITES MITTS MIXED MIXER MIXES MOANS MOATS MOBS MOCKS MODAL MODEL MODES MODEM MODUS MOGUL MOIST MOLAR MOLDS MOLDY MOLES MOLEST MOLT MOLTS MOMMA MOMMY MONEY MONKS MONSOON MONTH MOODS MOODY MOONS MOONY MOORS MOOSE MOOTS MOPED MOPES MOPEY MORAL MORALS MORAY MORES MORN MORNS MORONS MOSEY MOSSY MOTAR MOTEL MOTES MOTET MOTHS MOTHY MOTIF MOTOR MOTTO MOULD MOUND MOUNT MOURN MOUSE MOUSY MOUTH MOVED MOVER MOVES MOVIE MOWED MOWER MOXIE MUCKS MUCKY MUFFS MUGGY MULCH MULCT MULES MUMMY MUMPS MUNCH MURAL MUSED MUSES MUSEUM MUSEUMS MUSHED MUSHES MUSHY MUSIC MUSKS MUSKY MUSSY MUSTS MUSTY MUTED MUTES MUTTS MYRRH MYTHS " +
  "NABBED NABOB NACRE NADIR NAILS NAIVE NAKED NAMED NAMER NAMES NANNY NAPED NAPES NAPPY NARC NARCS NARES NASAL NASTY NATAL NATTY NAVAL NAVES NAVY NAWAB NAYS NEARS NEATER NEATLY NECKS NEEDS NEEDY NEIGH NEONS NERDS NERDY NERVE NERVY NESTS NEVER NEWBIE NEWEL NEWER NEWLY NEWS NEWSY NEWTS NEXT NICER NICHE NICKS NIDED NIECE NIFTY NIGHT NIGHTY NILS NIMBI NIMBLY NINES NINNY NINTH NIPPY NITRO NITTY NIVAL NOBLE NOBLY NOCKS NODDED NODES NODS NOISE NOISY NOMAD NONCE NONE NONES NOOKS NOOKY NOONS NOOSE NORTH NOSED NOSES NOSEY NOTCH NOTED NOTES NOUNS NOVAS NOVEL NOWAY NUBBY NUDER NUDES NUDGE NUKED NUKES NULLS NUMBS NURD NURDS NURSE NUTSY NUTTY NYLON NYMPH " +
  "OAKEN OAKS OARED OARS OASES OASIS OATEN OATHS OBEY OBEYS OBIES OBOES OBESE OCCUR OCEAN OCHRE OCTAL OCTAVE OCTET ODDLY ODORS OFFAL OFFER OFFICE OFTEN OGLED OGLER OGLES OGRES OHMIC OHS OILED OILER OINKS OKAYED OKAYS OKRAS OLDER OLDIE OLDIES OLEOS OLIVE OMEGA OMENS OMITS ONCE ONERS ONION ONIONS ONLY ONSET ONTO OODLES OOMPH OOZED OOZES OPALS OPENS OPERA OPINE OPING OPIUM OPTED OPTIC OPTS ORATE ORBIT ORBS ORCAS ORDER OREO OREOS OREXIN ORGAN ORGY OTHER OTTER OUCHED OUNCE OUSEL OUSTS OUTAGE OUTDO OUTED OUTER OUTGO OUTRO OVALS OVARY OVATE OVENS OVERS OVERT OVOID OWING OWLET OWLS OWNED OWNER OXEN OXENS OYEZ " +
  "PACED PACER PACES PACKS PACTS PADDY PADRE PAEAN PAGED PAGER PAGES PAGAN PAILS PAINS PAINT PAIRS PALED PALER PALES PALLS PALMS PALMY PALPS PANDA PANED PANEL PANES PANGS PANIC PANTS PAPA PAPAL PAPAS PAPER PAPS PARAM PARED PARES PARITY PARKS PARRY PARSE PARTS PARTY PASTA PASTE PASTS PASTY PATCH PATED PATES PATHS PATIO PATSY PATTY PAUSE PAVED PAVER PAVES PAWED PAWNS PAYED PAYEE PAYER PAYS PEACH PEAKS PEALS PEAR PEARL PEARS PECAN PECKS PEDAL PEEKS PEELS PEENS PEEPS PEERS PEEVE PEGS PEKOE PELTS PENAL PENCE PENDS PENIS PENNED PENS PEONS PEONY PEPPY PEPSI PERCH PERIL PERKS PERKY PERMS PERMS PERVS PESKY PESOS PESTS PESTLE PETAL PETER PETIT PETS PETTY PEW PEWS PHASE PHAT PHEW PHIAL PHLOX PHONE PHONES PHONY PHOOEY PHOTO PHYLA PIANO PIBROCH PICKS PICKY PICOT PIECE PIERS PIETY PIGGY PIGS PIKAS PIKED PIKES PILAF PILED PILES PILLS PIMPS PINEAL PINED PINES PINGS PINKS PINKY PINNY PINOT PINTO PINTS PIOUS PIPED PIPER PIPES PIPS PIQUE PIRACY PISCES PITAS PITCH PITHS PITHY PITTA PIVOT PIXEL PIXIE PIZZA PLAID PLAIN PLAIT PLANE PLANK PLANS PLANT PLATE PLATS PLAYS PLAZA PLEAD PLEAS PLEAT PLEDGE PLIED PLIES PLOD PLODS PLOPS PLOTS PLOWS PLOYS PLUCK PLUGS PLUMB PLUME PLUMP PLUMS PLUNK PLURAL PLUSH PLY POACH POCKS PODGY POEMS POETS POGO POIES POINT POISE POKED POKER POKES POKEY POLAR POLED POLES POLITE POLKA POLLS POLO POLOS POLYP POMPS PONDS PONIES PONS PONY POOCH POODLE POOHS POOLS POOPED POORS POOR POPES POPPY POPS PORCH PORED PORES PORKS PORKY PORNO PORN PORTS POSED POSER POSES POSIT POSSE POSTS POTTY POUCH POUND POURS POUTS POUTY POWER POXES PRANK PRAYED PRAYS PRAYER PRECIS PREEN PRESS PRESET PREYS PRICE PRICK PRIDE PRIED PRIES PRIEST PRIGS PRIMA PRIME PRIMP PRIMS PRINT PRION PRIOR PRISM PRIVY PRIZE PROBE PROD PRODS PROFS PROM PROMS PRONE PRONG PROOF PROOFS PROP PROPS PROSE PROSY PROUD PROVE PROVOST PROW PROWL PROWS PRUDE PRUNE PSALM PSALMS PSEUD PSHAW PSYCH PUBES PUBIC PUBIS PUDGY PUFFS PUFFY PUGS PUKED PUKES PUKEY PULL PULLS PULP PULPS PULPY PULSE PUMAS PUMP PUMPS PUNCH PUNKS PUNNY PUNS PUNTS PUNY PUPAE PUPAL PUPAS PUPIL PUPPY PUPS PURGE PURRS PURSE PURSY PUSSY PUSHY PUTTY PUTTS PYGMY PYRES PYRITE " +
  "QUACK QUADS QUAFF QUAIL QUAKE QUAKY QUALM QUART QUASH QUASI QUAYS QUEEN QUEER QUELL QUERY QUEST QUEUE QUICK QUIDS QUIET QUILL QUILT QUINCE QUINS QUIPS QUIRE QUIRK QUITE QUITS QUOIN QUOIT QUOTA QUOTE QUOTH " +
  "RABID RACED RACER RACES RACKS RADAR RADII RADIO RAFTS RAGED RAGER RAGES RAIDS RAILS RAINS RAINY RAISE RAJA RAJAS RAKED RAKER RAKES RALLY RAMEN RAMPS RAMS RANCH RANGE RANI RANKS RANTS RAPED RAPER RAPES RAPID RAPS RARED RARER RASCALS RASH RASHER RASHES RASPS RATED RATER RATES RATIO RATS RATTY RAVED RAVEN RAVER RAVES RAWLY RAYED RAYS RAZED RAZER RAZES RAZOR REACH REACT READS READY REALM REAMS REAPS REARS REBEL REBOOT REBUFF REBUS RECAP RECCE RECON RECTA REDID REDO REDOS REDS REDUX REEDS REEDY REEFS REEKS REEKY REELS REFER REGAL REHAB REIFY REIGN REINS REJECT RELAX RELAY RELIC REMAP REMIT REMOTE RENAL RENDS RENEW RENTS REPAY REPEL REPLY REPRO REPRO RESET RESINS RESPONDS REST RESTS RETIE RETRO REUSE REVEL REVUE RHEUM RHINO RHYME RIATA RIBBON RICED RICER RICES RICIN RIDER RIDES RIDGE RIFER RIFFS RIFLE RIFTS RIGHT RIGID RILED RILES RILLS RIMED RIMER RIMES RIMS RINDS RINGS RINKS RINSE RIOTS RIPED RIPEN RIPER RIPES RISEN RISER RISES RISKS RISKY RITES RITZY RIVAL RIVED RIVER RIVES ROACH ROADS ROAMS ROANS ROARS ROAST ROBED ROBES ROBIN ROBOT ROCKS ROCKY RODEO RODES RODS ROGER ROGUE ROILS ROLES ROLLS ROMP ROMPS ROODS ROOFS ROOKS ROOMS ROOMY ROOST ROOTS ROOTSY ROPED ROPER ROPES ROPEY ROSES ROSY ROTED ROTES ROTOR ROTOS ROUGE ROUGH ROUND ROUSE ROUTE ROUTS ROVED ROVER ROVES ROWAN ROWDY ROWED ROWER ROWS ROYAL RUBES RUBLE RUBYS RUDER RUDIMENT RUFFS RUGGED RUGS RUINS RULED RULER RULES RUMBA RUMMY RUMOR RUMPS RUNES RUNES RUNGS RUNNY RUNTS RUNTY RUPEE RURAL RUSES RUSHY RUSTS RUSTY RUTHS " +
  "SABER SABLE SABRA SACKS SACS SADHU SADLY SAFER SAFES SAGAS SAGER SAGES SAGGY SAILS SAINT SAKES SALAD SALES SALON SALSA SALTS SALTY SALVE SALVO SAMBA SANDS SANDY SANER SANES SAPID SAPPY SARGE SARIS SASHES SASS SASSY SATED SATES SATIN SATYR SAUCE SAUCY SAULS SAUNA SAVED SAVER SAVES SAVOR SAVOY SAWED SAYS SCABS SCADS SCALD SCALE SCALP SCALY SCAMP SCAMS SCANS SCANT SCAPE SCARE SCARF SCARS SCARY SCATS SCEND SCENE SCENT SCION SCOFF SCOLD SCONCE SCONE SCOOP SCOOT SCOPE SCORE SCORN SCOTS SCOUR SCOUT SCOWL SCRAM SCRAP SCREE SCREW SCRIBE SCRIM SCRIP SCRIPT SCROLL SCRUB SCRUM SCUBA SCUDS SCUFF SCULL SCULP SCUM SCUMS SCURF SCUZZ SEALS SEAMS SEAMY SEARS SEATS SEDAN SEDGE SEDGY SEEDS SEEDY SEEKS SEEMS SEEPS SEEPY SEERS SEINE SEIZE SELLS SEMIS SENDS SENNA SENSE SEPIA SEPTA SERAI SERAPH SERED SERES SERFS SERGE SERIF SERIN SERUM SERVE SETUP SEVEN SEVER SEWED SEWER SEXED SEXES SEXTET SHACK SHADE SHADY SHAFT SHAGS SHAKE SHAKY SHALL SHAMS SHAME SHANK SHAPE SHARD SHARE SHARK SHARP SHAWL SHAWM SHEAF SHEAR SHEDS SHEEN SHEEP SHEER SHEET SHEIK SHELF SHELL SHEWN SHEW SHIED SHIES SHIFT SHILL SHIMS SHINE SHINS SHINY SHIPS SHIRE SHIRK SHIRR SHIRT SHIVS SHOAL SHOCK SHODS SHOES SHOJI SHONE SHOOK SHOOS SHOOT SHOPS SHORE SHORN SHORT SHOTS SHOULD SHOUT SHOVE SHOWN SHOWS SHOWY SHRED SHREW SHRIMP SHRUB SHRUG SHTIK SHUCK SHUNS SHUNT SHUSH SHUTS SHUTE SHYER SHYLY SIBYL SICKO SICKS SIDED SIDES SIDLE SIEGE SIEVE SIGHS SIGHT SIGMA SIGNS SILKS SILKY SILLS SILLY SILOS SILOS SILTS SILTY SILVA SIMPS SINCE SINEW SINGE SINGS SINKS SINUS SIRED SIREN SIRES SISES SISSY SITED SITES SIXES SIXTY SIZED SIZER SIZES SKEET SKEIN SKIDS SKIED SKIER SKIES SKIFF SKILL SKIMP SKIMS SKINS SKINNY SKIPS SKIRT SKITS SKULK SKULL SKUNK SKYED SLABS SLACK SLAGS SLAIN SLAKE SLAMS SLANG SLANT SLAPS SLASH SLATE SLATS SLAVE SLAWS SLAYS SLEDS SLEEK SLEEP SLEET SLEPT SLEWS SLICE SLICK SLIDE SLIME SLIMS SLIMY SLING SLINK SLIPS SLITS SLOBS SLOES SLOOP SLOP SLOPE SLOPS SLOSH SLOTH SLOTS SLUGS SLUMP SLUMS SLUNG SLUNK SLUR SLURP SLURS SLUSH SLYER SMACK SMALL SMARM SMART SMASH SMEAR SMELL SMELT SMILE SMIRK SMITE SMITH SMOCK SMOG SMOGS SMOKE SMOKY SMOTE SMUGLY SMUTS SNACK SNAFU SNAGS SNAIL SNAKE SNAKY SNAPS SNARE SNARL SNEAK SNEER SNIDE SNIFF SNIPE SNIPS SNITS SNOBS SNOOD SNOOP SNOOT SNORE SNORT SNORTS SNOTS SNOTTY SNOUT SNOWS SNOWY SNUBS SNUCK SNUFF SNUG SOAKS SOAPS SOAPY SOARS SOBER SOBS SOCK SOCKS SODAS SODDED SODOM SOFAS SOFTS SOFTY SOGGY SOILS SOLAR SOLD SOLED SOLES SOLID SOLO SOLOS SOLVE SONAR SONGS SONIC SONNY SOONER SOOTS SOOTY SOPHS SOPPY SORBET SORE SORER SORES SORRY SORTS SOULS SOUND SOUPED SOUPS SOUR SOURS SOUTH SOWED SOWER SOWN SOZIN SPACE SPADE SPAKE SPANG SPANK SPANS SPARE SPARK SPARS SPASM SPATE SPATS SPAWN SPAYS SPEAK SPEAR SPECK SPECS SPEED SPELL SPELT SPEND SPENT SPERM SPEWS SPICE SPICY SPIED SPIES SPIKE SPIKY SPILL SPILT SPINE SPINS SPINY SPIRE SPITE SPITS SPLAT SPLAY SPLIT SPOIL SPOKE SPONGE SPONY SPOOF SPOOK SPOOL SPOON SPOOR SPORE SPORT SPOTS SPRAT SPRAY SPREE SPRIG SPRING SPRINTS SPRITE SPRY SPUDS SPUDS SPUME SPUMY SPUNK SPURN SPURS SPURT SPYING SQUAB SQUAD SQUARE SQUAT SQUAWK SQUEEZE SQUELCH SQUID SQUIB SQUIRM STABS STACK STAFF STAGE STAGS STAID STAIN STAIR STAKE STALE STALK STALL STAMP STAND STANK STAR STARE STARK STARS START STASH STATE STATS STAVE STAYS STEAD STEAK STEAL STEAM STEED STEEL STEEP STEER STEMS STENO STEPS STERN STEW STEWS STICK STIES STIFF STILE STILL STILT STING STINK STINT STIRS STOAT STOCK STOIC STOKE STOLE STOMP STONE STONY STOOD STOOL STOOP STOPS STORE STORK STORM STORY STOUT STOVE STOWS STRAP STRAW STRAY STREP STREW STRIP STROP STROP STROW STRUM STRUT STUBS STUCK STUDS STUDY STUFF STUMP STUMPS STUNG STUNK STUNS STUNT STYLE STYLI STYMIE SUAVE SUBMIT SUCKS SUEDE SUGAR SUING SUITE SUITS SULKS SULKY SULLY SUMAC SUMS SUNG SUNKEN SUNNY SUNS SUNUP SUPER SUPS SURER SURFS SURGE SURLY SUSHI SWABS SWADS SWAIN SWAMI SWAMP SWAMPS SWAMPY SWANS SWANK SWAPS SWARD SWARM SWASH SWATH SWATS SWAYED SWAYS SWEAR SWEAT SWEEP SWEET SWELL SWELT SWEPT SWERVE SWIFT SWIG SWIGS SWILL SWIMS SWINE SWING SWIPE SWIRL SWISH SWISS SWORE SWORN SWORN SWUM SYNCED SYNOD SYNCS SYNDIC SYRUP " +
  "TABBY TABLE TABLET TABOO TACIT TACKS TACKY TACOS TADS TAFFY TAILS TAINT TAKEN TAKER TAKES TALCS TALE TALES TALKS TALKY TALL TALLER TALLY TALON TAMED TAMER TAMES TANGY TANGO TANGS TANKED TANS TAPED TAPER TAPES TAPIR TARDY TARES TARNS TAROT TARRY TARTS TASKS TASTE TASTY TATER TATTY TAUNT TAUTS TAWNY TAXES TAXIED TAXIS TBSPS TEACH TEAMS TEARS TEARY TEASE TEAT TEAS TEASE TEATS TECHS TEDDY TEEMS TEENS TEENY TEES TEETH TELLS TELLY TEMPI TEMPO TEMPS TEMPT TENDS TENET TENNIS TENON TENOR TENSE TENT TENTS TEPEE TEPID TERMS TERNS TERRY TERSE TESLA TESTS TESTY TETRA TEXTS THANE THANK THATS THAW THAWS THEFT THEME THERE THESE THESPIANS THEYS THICK THIEF THIGH THINE THING THINK THINS THIRD THONG THORN THOSE THREE THREW THRIP THROB THROE THROW THUMB THUMP THWAP THWARTS THYME TIARA TIBIA TICKS TIDAL TIDED TIDES TIDIED TIDIER TIDIES TIEDS TIERS TIES TIFFS TIGER TIGHT TIKE TIKES TIKIS TILDE TILED TILER TILES TILLS TILTS TIMED TIMER TIMES TINGE TINKER TINNY TINTS TINY TIPPY TIPS TIPSY TIRED TIRES TITAN TITER TITHE TITLE TITTY TIZZY TOADS TOAST TODAY TODDY TODOS TOFFS TOFUS TOGAS TOGGLE TOILED TOILS TOKEN TOKES TOKED TOKES TOLLS TOLED TOLES TOMBS TOMES TOMMY TONAL TONED TONER TONES TONGS TONIC TONUS TOOLS TOOLS TOON TOOTH TOOTS TOPAZ TOPED TOPES TOPIS TOPS TOQUE TORAH TORCH TORES TORIC TORN TORO TOROS TORQUE TORTS TORUS TOSSY TOTAL TOTED TOTES TOTEM TOUCH TOUGH TOURED TOURS TOUTS TOWED TOWEL TOWER TOWERY TOWNS TOWNY TOXIC TOXIN TOYED TOYS TRACE TRACK TRACT TRADE TRAIL TRAIN TRAIPSE TRAITS TRAMP TRAMS TRANS TRAPS TRASH TRAYS TREAD TREAS TREAT TREED TREES TREKS TREND TREYS TRIAD TRIAL TRIBE TRICE TRICK TRIED TRIER TRIES TRILL TRIM TRIMS TRIO TRIOS TRIP TRIPE TRIPS TRITE TROD TRODS TROLL TROMP TROOP TROPE TROUT TROVE TRUCK TRUER TRULY TRUMP TRUNK TRUSS TRUST TRUTH TRYST TUBAS TUBBY TUBED TUBES TUCKS TUFTS TUFTY TULIP TULLES TUMID TUMMY TUMOR TUNAS TUNED TUNER TUNES TUNIC TURBAN TURDS TURFS TURKS TURNS TURPS TUSKS TUTOR TUTSI TUTTI TUTU TUTUS TWAIN TWANG TWEAK TWEED TWEET TWEEZE TWERP TWICE TWIGS TWINE TWINS TWIRL TWIST TWITS TYING TYKES TYPED TYPES TYPER TYPES TYRANT TZAR TZARS " +
  "UDDER UDONS UGLY ULCER ULNA ULNAR UMBRA UMPED UMPHS UMPS UNAPT UNARM UNBAR UNCAP UNCLE UNCUT UNDID UNDO UNDOES UNDONE UNDUE UNFED UNFIT UNIFY UNION UNITS UNITY UNJUST UNLED UNLIT UNMAN UNMET UNPEG UNPIN UNRIG UNSAID UNSET UNTIE UNTIL UNTO UNWED UPDO UPDOS UPEND UPPED UPPER UPSET URBAN URGED URGES URINE URN URNS USAGE USED USERS USES USHER USING USUAL USURP UTERI UTILE UTOPIA UTTER " +
  "VACATE VAGUE VAINS VALES VALET VALID VALOR VALUE VALVE VALVES VAMPS VANED VANES VAPID VAPOR VARY VASES VAST VATIC VATS VAULT VAUNT VEALS VEERS VEEPS VEGAN VEILS VEIN VEINS VEINY VELDT VENAL VENDS VENOM VENT VENTS VENUE VENUS VERB VERBS VERDANT VERGE VERIFY VERSE VERSO VERTEX VERY VESTS VETO VEXED VEXES VIALS VIBES VICAR VICE VICES VIDEO VIEWS VIGOR VILER VILES VILLA VILLE VINCE VINES VINOS VINYL VIOLA VIPER VIRAL VIRES VIREO VIRGA VIRUS VISAS VISED VISES VISIT VISOR VISTA VITAL VIVA VIVID VIXEN VIZIR VIZOR VOCAB VOCAL VODKA VOGUE VOICE VOICED VOIDS VOILE VOLES VOLT VOLTS VOMIT VOTED VOTER VOTES VOWED VOWEL VOWS VOYAGE VYING " +
  "WACKO WACKS WACKY WADED WADER WADES WADIS WAFER WAFFLE WAFTS WAGED WAGER WAGES WAGON WAIFS WAILS WAITS WAKED WAKEN WAKES WALES WALKS WALL WALLS WALLY WALTZ WANDS WANED WANES WANTS WARDS WARES WARM WARMS WARN WARNS WARPS WARTS WARTY WARY WASHES WASTE WATCH WATER WAVED WAVER WAVES WAVEY WAVES WAVY WAXED WAXEN WAXER WAXES WAYS WEALS WEAN WEANS WEARS WEARY WEAVE WEBBY WEDGE WEEDS WEEDY WEEKS WEEPS WEEPY WEIGH WEIRS WELLS WELSH WELTS WENDS WENNY WENS WENT WEPT WHACK WHALE WHAMS WHAMMY WHARF WHATS WHEAT WHEEL WHELK WHELP WHENS WHERE WHEYS WHIFF WHILE WHIMS WHINE WHINY WHIPS WHIRL WHIRR WHIRS WHISK WHIST WHITE WHITS WHIZZ WHOEVER WHOLE WHOLLY WHOMP WHOOP WHOOSH WHOPS WHOSE WHYDA WIDEN WIDER WIDOW WIDOWED WIDTH WIELD WIFEY WIFES WIGGY WIGS WIKIS WILD WILDS WILED WILES WILLS WILLY WILT WILTS WIMPS WIMPY WINCE WINCH WINDS WINDY WINES WINEY WINGS WINKS WINKED WINNER WINNERS WINOS WINS WIPED WIPER WIPES WIRED WIRES WIRY WISED WISER WISES WISH WISHY WISPS WISPY WITCH WITHE WITHIN WITS WITTY WIVES WIZEN WIZES WOEFUL WOES WOKED WOKEN WOLDS WOLFS WOMAN WOMB WOMBAT WOMBS WOMEN WONKS WONKY WOOED WOODS WOODY WOOFS WOOL WOOLLY WOOLS WOOLY WOOSH WOOZY WORDS WORDY WORKED WORKS WORLD WORM WORMS WORMY WORN WORRY WORSE WORST WORTH WOULD WOUND WOUNDS WOVED WOVE WOVEN WRACK WRAITH WRAP WRAPS WRAPT WRATH WREAK WREAKS WRECK WRENS WREST WRIED WRIES WRING WRIST WRIT WRITE WRITS WRONG WROTE WRUNG WRYER WRYLY WURST WUSSY WYMPH WYRM " +
  "XEROX XYLEM XYSTI " +
  "YACHT YACK YACKS YAKKED YAKS YALES YAMEN YAMS YANG YANK YANKS YAPPED YAPS YARD YARDS YARN YARNS YAWED YAWLS YAWN YAWNS YEAH YEAS YEAST YEARS YEAH YELLS YELLOW YELPS YEN YENS YEP YEPS YESES YETIS YEWS YIDS YIELD YIPE YIPES YIPS YODEL YOGI YOGIS YOKEL YOKES YOLKED YOLKS YORES YOUNG YOURS YOUTH YOWL YOWLS YOYOS YUAN YUCKS YUKE YUKKED YULES YUMMY YURTS " +
  "ZAGS ZAIRE ZANY ZAPPED ZAPS ZAYIN ZEALS ZEBRA ZEROD ZEROS ZERO ZEST ZESTS ZESTY ZETAS ZIBET ZILCH ZINCS ZINCY ZINES ZINGS ZINGY ZIPS ZITHER ZITI ZITS ZIZIT ZLOTY ZOEAS ZOMBI ZONAL ZONED ZONES ZONK ZONKED ZONKS ZOOEY ZOOID ZOOKS ZOOMS ZOOS ZOOT ZORI ZORIS"
);

export const DICTIONARY: Set<string> = (() => {
  const set = new Set<string>();
  for (const w of DICTIONARY_TEXT.split(/\s+/)) {
    const u = w.trim().toUpperCase();
    if (u.length >= 3) set.add(u);
  }
  return set;
})();

/** Case-insensitive dictionary lookup. */
export function isValidWord(w: string): boolean {
  return DICTIONARY.has(w.toUpperCase());
}

/* ------------------------------------------------------------------ */

export type Duration = "90" | "180" | "300";

export interface GameSettings {
  duration: Duration;
}

export interface GameState {
  /** 16 cells, row-major. Letters are uppercase. */
  grid: string[];
  /** Indices of cells in the in-progress path. */
  currentPath: number[];
  /** Accepted words found by the player this run. */
  foundWords: string[];
  /** Player's running score. */
  playerScore: number;
  /** Seconds remaining. */
  timeLeft: number;
  /** True once the timer runs out. */
  done: boolean;
  /** Last validation error to surface in the UI. Cleared on next input. */
  error: string | null;
  /** CPU score precomputed at game start (greedy solver across dictionary). */
  cpuScore: number;
  /** Sample words the CPU "found" (for end-of-game display). */
  cpuWords: string[];
}

export type GameAction =
  | { type: "tick" }
  | { type: "selectCell"; index: number }
  | { type: "submitWord" }
  | { type: "clearPath" };

/** Length-based scoring: 3-4=1, 5=2, 6=3, 7=5, 8+=11. <3 returns 0. */
export function wordScore(len: number): number {
  if (len < 3) return 0;
  if (len <= 4) return 1;
  if (len === 5) return 2;
  if (len === 6) return 3;
  if (len === 7) return 5;
  return 11;
}

/** Adjacency in a 4x4 grid (8-direction incl. diagonals). */
export function areAdjacent(a: number, b: number): boolean {
  if (a === b) return false;
  const ar = Math.floor(a / 4), ac = a % 4;
  const br = Math.floor(b / 4), bc = b % 4;
  return Math.abs(ar - br) <= 1 && Math.abs(ac - bc) <= 1;
}

/** Validate the chain (each step adjacent + no revisits). */
export function isValidPath(path: number[]): boolean {
  if (path.length < 2) return true;
  for (let i = 1; i < path.length; i++) {
    if (!areAdjacent(path[i - 1]!, path[i]!)) return false;
    if (path.slice(0, i).includes(path[i]!)) return false;
  }
  return true;
}

export function pathToWord(path: number[], grid: string[]): string {
  return path.map(i => grid[i]!).join("");
}

/** Roll one face for each of the 16 dice in shuffled order. Deterministic. */
function rollGrid(rng: () => number): string[] {
  const dice: (readonly string[])[] = BOGGLE_DICE_1992.map(d => d);
  // Fisher-Yates shuffle of die order
  const order = dice.slice();
  for (let i = order.length - 1; i > 0; i--) {
    const j = Math.floor(rng() * (i + 1));
    [order[i], order[j]] = [order[j]!, order[i]!];
  }
  // Pick a random face from each die
  return order.map(die => die[Math.floor(rng() * die.length)]!);
}

/**
 * Word-finding helper: given a target word and the grid, can it be traced?
 * Used by the CPU solver. Returns true if any adjacency-respecting,
 * no-revisit path through the grid spells `word`.
 */
export function canTrace(word: string, grid: string[]): boolean {
  const w = word.toUpperCase();
  const n = w.length;
  if (n < 3 || n > 16) return false;
  // DFS from every starting cell whose letter matches.
  const used = new Array<boolean>(16).fill(false);
  function dfs(idx: number, pos: number): boolean {
    if (grid[idx] !== w[pos]) return false;
    if (pos === n - 1) return true;
    used[idx] = true;
    const r = Math.floor(idx / 4), c = idx % 4;
    for (let dr = -1; dr <= 1; dr++) {
      for (let dc = -1; dc <= 1; dc++) {
        if (dr === 0 && dc === 0) continue;
        const nr = r + dr, nc = c + dc;
        if (nr < 0 || nr > 3 || nc < 0 || nc > 3) continue;
        const ni = nr * 4 + nc;
        if (used[ni]) continue;
        if (dfs(ni, pos + 1)) {
          used[idx] = false;
          return true;
        }
      }
    }
    used[idx] = false;
    return false;
  }
  for (let i = 0; i < 16; i++) {
    if (grid[i] === w[0] && dfs(i, 0)) return true;
  }
  return false;
}

/**
 * Greedy CPU solver. Scans a precomputed shortlist of dictionary words
 * (longest-first so it finds high-value words) and collects everything
 * that's traceable. Capped so initialState stays fast even on slow
 * devices. Returns { score, words }.
 */
function solveCpu(grid: string[]): { score: number; words: string[] } {
  // Cheap pre-filter: words whose letter multiset doesn't fit the grid
  // can't possibly be on the board, so skip them without DFS.
  const gridCounts: Record<string, number> = {};
  for (const ch of grid) gridCounts[ch] = (gridCounts[ch] ?? 0) + 1;

  // Pull dictionary into an array sorted longest-first.
  // We cap at ~600 words inspected to keep the solver cheap.
  const all = Array.from(DICTIONARY);
  all.sort((a, b) => b.length - a.length || (a < b ? -1 : a > b ? 1 : 0));

  const words: string[] = [];
  let score = 0;
  let inspected = 0;
  const MAX_INSPECT = 800;
  const MAX_FOUND = 25;

  for (const w of all) {
    if (words.length >= MAX_FOUND) break;
    if (inspected >= MAX_INSPECT) break;
    inspected++;
    // multiset filter
    const counts: Record<string, number> = {};
    for (const ch of w) counts[ch] = (counts[ch] ?? 0) + 1;
    let ok = true;
    for (const ch in counts) {
      if ((gridCounts[ch] ?? 0) < counts[ch]!) { ok = false; break; }
    }
    if (!ok) continue;
    if (canTrace(w, grid)) {
      words.push(w);
      score += wordScore(w.length);
    }
  }

  return { score, words };
}

export function initialState(seed: number, settings: GameSettings): GameState {
  const rng = mulberry32(seed);
  const grid = rollGrid(rng);
  const duration = parseInt(settings.duration, 10);
  const { score: cpuScore, words: cpuWords } = solveCpu(grid);
  return {
    grid,
    currentPath: [],
    foundWords: [],
    playerScore: 0,
    timeLeft: duration,
    done: false,
    error: null,
    cpuScore,
    cpuWords,
  };
}

export function reducer(state: GameState, action: GameAction): GameState {
  if (state.done) return state;
  switch (action.type) {
    case "tick": {
      const t = state.timeLeft - 1;
      if (t <= 0) return { ...state, timeLeft: 0, done: true };
      return { ...state, timeLeft: t };
    }
    case "selectCell": {
      const { index } = action;
      if (index < 0 || index >= state.grid.length) return state;
      const path = state.currentPath;
      // Trim-back retrace: clicking a cell already in path trims to it.
      const existing = path.indexOf(index);
      if (existing !== -1) {
        return { ...state, currentPath: path.slice(0, existing + 1), error: null };
      }
      // Adjacency check after first cell.
      if (path.length > 0 && !areAdjacent(path[path.length - 1]!, index)) {
        return { ...state, error: "Not adjacent" };
      }
      return { ...state, currentPath: [...path, index], error: null };
    }
    case "submitWord": {
      const path = state.currentPath;
      if (path.length < 3) {
        return { ...state, currentPath: [], error: "Too short (min 3 letters)" };
      }
      if (!isValidPath(path)) {
        return { ...state, currentPath: [], error: "Invalid path" };
      }
      const word = pathToWord(path, state.grid);
      if (state.foundWords.includes(word)) {
        return { ...state, currentPath: [], error: "Already found" };
      }
      if (!isValidWord(word)) {
        return { ...state, currentPath: [], error: "Not a word" };
      }
      const pts = wordScore(word.length);
      return {
        ...state,
        foundWords: [...state.foundWords, word],
        playerScore: state.playerScore + pts,
        currentPath: [],
        error: null,
      };
    }
    case "clearPath":
      return { ...state, currentPath: [], error: null };
    default:
      return state;
  }
}

/** Score reported on the leaderboard: player's words, plus a 100-point
 *  win bonus if they beat the CPU. Non-negative — losing still counts as
 *  whatever they earned, but at least beating the bar is rewarded. */
export function isTerminal(state: GameState): { score: number } | null {
  if (!state.done) return null;
  const bonus = state.playerScore > state.cpuScore ? 100 : 0;
  return { score: state.playerScore + bonus };
}
