// Text Twist word lists keyed by length

export const WORD_LIST_3: readonly string[] = [
  "ACE","AGE","AIR","ARC","ARM","ART","ASH","ATE","AWE",
  "BAD","BAN","BAR","BAT","BED","BIG","BIT","BOW","BOX",
  "BUD","BUG","BUN","BUS","BUT","CAB","CAN","CAP","CAR",
  "CAT","COP","COR","COT","CUB","CUP","CUR","CUT","DAB",
  "DAM","DEN","DEW","DIM","DIP","DOE","DOT","DRY","DUG",
  "DUO","DYE","EAR","EAT","EEL","EGG","ELM","EMU","ERA",
  "EVE","EWE","FAD","FAN","FAR","FAT","FAX","FEW","FIG",
  "FIN","FIT","FLY","FOB","FOE","FOG","FOP","FOR","FRY",
  "FUN","FUR","GAB","GAP","GAS","GAY","GEL","GEM","GET",
  "GIG","GIN","GNU","GOB","GOT","GUM","GUN","GUT","GUY",
  "GYM","HAD","HAM","HAS","HAT","HAY","HEM","HEN","HEW",
  "HIM","HIP","HIT","HOB","HOG","HOP","HOT","HUB","HUE",
  "HUM","ICE","ILL","INN","ION","IRE","JAB","JAM","JAR",
  "JAW","JET","JOB","JOG","JOT","JOY","JUG","JUT","KEG",
  "KID","KIT","LAB","LAD","LAP","LAW","LAX","LAY","LEG",
  "LET","LID","LIP","LIT","LOG","LOT","LOW","LUG","MAD",
  "MAP","MAR","MAT","MAW","MAY","MEN","MET","MOB","MOD",
  "MOM","MOP","MUD","MUG","NAB","NAG","NAP","NET","NEW",
  "NIP","NOB","NOD","NOR","NOT","NOW","NUB","NUN","NUT",
  "OAK","OAR","OAT","ODD","ODE","OLD","ONE","OPT","ORB",
  "ORE","OWL","OWN","PAD","PAL","PAN","PAP","PAR","PAT",
  "PAW","PAY","PEA","PEG","PEN","PEP","PET","PIE","PIG",
  "PIN","PIT","PLY","POD","POP","POT","POW","PRY","PUB",
  "PUN","PUP","PUS","PUT","RAG","RAM","RAN","RAP","RAT",
  "RAW","RAY","RED","REF","RIB","RID","RIG","RIM","RIP",
  "ROB","ROD","ROT","ROW","RUB","RUG","RUN","RUT","SAG",
  "SAP","SAT","SAW","SAY","SEA","SET","SEW","SIP","SIT",
  "SIX","SKI","SKY","SLY","SOB","SOD","SON","SOP","SOT",
  "SOW","SOY","SPA","SPY","STY","SUB","SUM","SUN","SUP",
  "TAB","TAN","TAP","TAR","TAX","TEN","THE","TIE","TIN",
  "TIP","TOE","TON","TOO","TOP","TOW","TOY","TUB","TUG",
  "TUN","TWO","URN","USE","VAT","VIA","VIM","VOW","WAD",
  "WAR","WAS","WAX","WEB","WED","WET","WHO","WHY","WIG",
  "WIN","WIT","WOE","WOK","WON","WOO","WOW","YAM","YAP",
  "YAW","YEA","YEN","YEW","YOB","YOU","ZAP","ZEN","ZIT",
] as const;

export const WORD_LIST_4: readonly string[] = [
  "ABLE","ACID","AGED","ALSO","ANEW","ARCH","AREA","ARMY",
  "ALSO","ALTO","AMEN","APEX","ARCH","ARIA","ASHY","ATOP",
  "AUNT","AUTO","AVID","BABE","BACK","BALE","BALK","BALL",
  "BAND","BANE","BANG","BANK","BARE","BARN","BASE","BASH",
  "BATH","BEAD","BEAM","BEAN","BEAR","BEAT","BEEF","BEEN",
  "BELL","BELT","BEND","BEST","BILE","BILL","BIND","BITE",
  "BLOT","BLOW","BLUE","BLUR","BOAR","BODY","BOIL","BOLD",
  "BOLT","BONE","BOOK","BOOM","BOON","BORE","BOTH","BRED",
  "BREW","BULK","BULL","BUMP","BURN","BURP","BUSH","BUSY",
  "BYTE","CAGE","CAKE","CALF","CALL","CALM","CAME","CAPE",
  "CARD","CARE","CART","CASE","CASH","CAST","CAVE","CELL",
  "CHAT","CHIP","CHOP","CITE","CITY","CLAD","CLAM","CLAP",
  "CLAY","CLIP","CLUB","CLUE","COAL","COAT","COIL","COIN",
  "COLD","COMET","COME","CONE","COOK","COOL","COPE","CORE",
  "CORN","COST","COZY","CRAM","CREW","CROP","CUBE","CURE",
  "DAMP","DARE","DARK","DASH","DATA","DATE","DAWN","DEAD",
  "DEAL","DEAN","DEAR","DECK","DEED","DEEM","DEEP","DEER",
  "DEFT","DENY","DESK","DIAL","DICE","DIME","DINE","DIRT",
  "DISH","DISK","DOME","DONE","DOOM","DOOR","DOSE","DOTE",
  "DOVE","DOWN","DRAB","DRAG","DRAW","DRIP","DROP","DRUG",
  "DRUM","DUCK","DUEL","DUMB","DUMP","DUNE","DUSK","DUST",
  "DUSK","EACH","EARL","EARN","EASE","EDGE","ELSE","EMIT",
  "ENVY","EPIC","EVEN","EVER","EVIL","EXAM","FACE","FACT",
  "FADE","FAIL","FAIR","FAKE","FALL","FAME","FARE","FARM",
  "FAST","FAWN","FEAT","FEEL","FEET","FELL","FELT","FILE",
  "FILL","FILM","FIND","FINE","FIRM","FISH","FIST","FLAG",
  "FLAT","FLAW","FLEE","FLEW","FLEX","FLIP","FLIT","FOLK",
  "FOND","FONT","FOOL","FOOT","FORD","FORE","FORK","FORM",
  "FORT","FOUL","FOUR","FOWL","FRAY","FREE","FROG","FROM",
  "FUEL","FULL","FUME","FURY","FUSE","GALE","GALL","GAME",
  "GANG","GASH","GATE","GAZE","GEAR","GIFT","GILL","GIRL",
  "GIVE","GLAD","GLIB","GLOB","GLOW","GLUE","GOAL","GOAT",
  "GOLF","GOOD","GORE","GOWN","GRAB","GRAY","GREW","GRIN",
  "GRIP","GRIT","GUST","GUYS","HACK","HAIL","HAIR","HALF",
  "HALL","HALT","HAND","HANG","HARD","HARE","HARM","HARP",
  "HART","HASH","HAUL","HAWK","HEAD","HEAL","HEAP","HEAR",
  "HEAT","HEEL","HELP","HERB","HERO","HIGH","HILL","HIRE",
  "HOLD","HOLE","HOLY","HOME","HOOD","HOOK","HOPE","HORN",
  "HOUR","HUGE","HULL","HUNG","HUNT","HURL","HURT","HYMN",
  "IDEA","IDLE","INCH","INTO","IRON","ISLE","ITCH","ITEM",
  "JADE","JAIL","JOKE","JOLT","JUMP","JUST","KEEN","KEEP",
  "KELP","KERN","KICK","KILL","KILN","KIND","KING","KITE",
  "KIWI","KNOB","KNOW","LACE","LACK","LAKE","LAMB","LAMP",
  "LAND","LANE","LARK","LAST","LATE","LAUD","LEAF","LEAN",
  "LEAP","LEFT","LESS","LIAR","LIKE","LILY","LIME","LINE",
  "LINK","LION","LIST","LIVE","LOAD","LOAM","LOAN","LOBE",
  "LOCK","LOFT","LONE","LONG","LOOK","LORE","LORN","LOSE",
  "LOSS","LOST","LOUD","LURE","LUST","LUTE","LYNX","MACE",
  "MAIL","MAIN","MAKE","MALE","MALL","MALT","MANE","MANY",
  "MARK","MARS","MASH","MAST","MAZE","MEAD","MEAL","MEAN",
  "MEAT","MELT","MEND","MESH","MILD","MILK","MILL","MIME",
  "MINT","MIST","MOAT","MOCK","MOLE","MONK","MOON","MOOR",
  "MORE","MOST","MOTH","MOVE","MUCK","MULE","MUSE","MYTH",
] as const;

export const WORD_LIST_5: readonly string[] = [
  "ABOUT","ABOVE","ABUSE","ACORN","ACUTE","ADMIT","ADOPT","ADULT",
  "AFTER","AGAIN","AGILE","AGLOW","AHEAD","ALARM","ALBUM","ALERT",
  "ALIKE","ALIVE","ALOFT","ALOOF","ALONE","ALONG","ALTER","ANGEL",
  "ANGLE","ANGRY","ANNOY","APRON","ARENA","ARGUE","ARISE","ARMOR",
  "AROMA","ASIDE","ATLAS","ATONE","ATTIC","AVOID","AWAKE","AWARE",
  "BADLY","BASIC","BEACH","BEGAN","BEING","BELOW","BENCH","BLACK",
  "BLADE","BLAME","BLAND","BLANK","BLAST","BLAZE","BLEAK","BLEND",
  "BLESS","BLIND","BLISS","BLOCK","BLOOD","BLOOM","BLOWN","BOARD",
  "BONUS","BOOST","BOOTH","BOUND","BRACE","BRAID","BRAIN","BRAND",
  "BRAVE","BREAD","BREAK","BREED","BRIBE","BRICK","BRIDE","BRIEF",
  "BRING","BROAD","BROOD","BUILD","BUNCH","BURST","CABIN","CABLE",
  "CAMEL","CANAL","CANDY","CARRY","CARVE","CATCH","CAUSE","CEASE",
  "CHAIR","CHARM","CHART","CHASE","CHEAP","CHECK","CHEER","CHIEF",
  "CHILD","CIVIL","CLAIM","CLASH","CLASS","CLEAN","CLEAR","CLIMB",
  "CLING","CLOCK","CLOSE","CLOUD","CLOWN","COACH","CORAL","COUNT",
  "COURT","COVER","CRAFT","CRASH","CREAM","CREEK","CRIME","CRISP",
  "CROSS","CROWD","CROWN","CRUDE","CRUSH","CURVE","CYCLE","DANCE",
  "DEATH","DEBUT","DECAY","DELAY","DEPOT","DEPTH","DERBY","DEVIL",
  "DRAFT","DRAIN","DRAMA","DREAM","DRESS","DRIFT","DRINK","DRIVE",
  "DROWN","EAGLE","EARLY","EARTH","ELECT","EMPTY","ENTER","EQUIP",
  "EXACT","EXCEL","EXIST","EXTRA","FAINT","FAITH","FALSE","FANCY",
  "FEAST","FENCE","FERRY","FEVER","FIBER","FIELD","FIERY","FIGHT",
  "FINAL","FIRST","FIXED","FLAME","FLASH","FLESH","FLOOR","FLOUR",
  "FOCUS","FORCE","FORGE","FOUND","FRAME","FRANK","FRAUD","FRESH",
  "FRONT","FROST","FRUIT","FULLY","FUNNY","GIANT","GIVEN","GRACE",
  "GRADE","GRAIN","GRAND","GRANT","GRASP","GRASS","GREAT","GREED",
  "GREET","GRIEF","GRILL","GRIND","GROAN","GROSS","GROUP","GROVE",
  "GROWL","GUIDE","GUILD","GUILT","GUISE","HAUNT","HEART","HEAVY",
  "HENCE","HONOR","HOTEL","HOUSE","HOVER","HUMAN","HURRY","IMAGE",
  "INDEX","INNER","IRONY","JUDGE","JUICE","KEENS","KNIFE","KNOCK",
  "KNOWN","LABEL","LANCE","LARGE","LASER","LATER","LAYER","LEAFY",
  "LEARN","LEAVE","LEVEL","LIGHT","LIMIT","LOCAL","LOOSE","LOVER",
  "LOWER","LUCKY","MAGIC","MAKER","MANOR","MAPLE","MARCH","MEDAL",
  "MERGE","MERIT","METAL","MIGHT","MINOR","MODEL","MONEY","MORAL",
  "MOUNT","MOUSE","MUSIC","NERVE","NIGHT","NOBLE","NOISE","NORTH",
  "NOTED","NOVEL","OCCUR","OFFER","OFTEN","ORBIT","ORDER","OZONE",
  "PAINT","PANIC","PAPER","PATCH","PAUSE","PEACE","PEARL","PHASE",
  "PIANO","PILOT","PLACE","PLAIN","PLANE","PLANT","PLATE","PLAZA",
  "PLEAD","POLAR","POWER","PRESS","PRICE","PRIDE","PRIME","PRINT",
  "PRIZE","PROBE","PROOF","PROSE","PROUD","PROVE","PULSE","PUNCH",
  "QUEEN","QUEST","QUICK","QUIET","QUITE","QUOTA","QUOTE","RADIO",
  "RAISE","RALLY","RANGE","RAPID","REACH","REALM","REBEL","REFER",
  "REIGN","RELAX","RENEW","RESET","RIDER","RIGHT","RIGID","RISEN",
  "RIVER","ROCKY","ROUGH","ROUND","ROUTE","ROYAL","RULER","RURAL",
  "SADLY","SAINT","SALAD","SAUCE","SCALE","SCENE","SCENT","SCOPE",
  "SCORE","SCOUT","SENSE","SERVE","SEVEN","SHAPE","SHARE","SHARP",
  "SHELF","SHELL","SHIFT","SHINE","SHOCK","SHORE","SHORT","SHOUT",
  "SIGHT","SINCE","SKILL","SLEEP","SLIDE","SLOPE","SMALL","SMART",
  "SMELL","SMILE","SMOKE","SOLID","SOLVE","SORRY","SOUND","SOUTH",
  "SPACE","SPARE","SPARK","SPEAK","SPEED","SPELL","SPEND","SPLIT",
  "SPORT","SPRAY","STACK","STAFF","STAGE","STAIN","STAND","START",
  "STATE","STEAM","STEEL","STERN","STICK","STILL","STING","STOCK",
  "STONE","STORE","STORM","STORY","STUCK","STUDY","STYLE","SUGAR",
  "SUNNY","SUPER","SURGE","SWEEP","SWEET","SWIFT","SWORD","TABLE",
  "TASTE","TEACH","TENSE","THINK","THROW","TIGER","TIGHT","TIMER",
  "TIRED","TITLE","TODAY","TOKEN","TOTAL","TOUCH","TOUGH","TOWER",
  "TRACK","TRADE","TRAIL","TRAIN","TREAT","TREND","TRIAL","TRICK",
  "TRIED","TRULY","TRUST","TRUTH","UNCLE","UNDER","UNITY","UNTIL",
  "UPPER","URBAN","USAGE","USUAL","VALID","VALUE","VERSE","VIDEO",
  "VIGOR","VIRAL","VITAL","VIVID","VOICE","VOTER","WASTE","WATCH",
  "WATER","WHILE","WHITE","WHOLE","YOUNG","SLOPE","SNARE","SUITE",
] as const;

export const WORD_LIST_6: readonly string[] = [
  "ABSENT","ACCEPT","ACCESS","ACCORD","ACHIEVE","ACROSS","ACTIVE","ADMIRE",
  "AFFORD","AFRAID","AGREED","ALMOST","ALWAYS","ANIMAL","ANSWER","ANYONE",
  "APPEAR","AROUND","ARRIVE","ARTIST","ATTACK","ATTEND","AUTUMN","BATTLE",
  "BEAUTY","BECOME","BEFORE","BEHIND","BETTER","BORDER","BOTTLE","BOUGHT",
  "BRANCH","BREACH","BROKEN","BROWSE","BURDEN","BUTTER","BUTTON","CANCEL",
  "CANNON","CARBON","CASTLE","CAUGHT","CENTER","CHANCE","CHANGE","CHOSEN",
  "CHURCH","CIRCLE","CLEVER","CLOSER","CLOTHE","COFFEE","COMMIT","COTTON",
  "COURSE","CREATE","CRISIS","DANGER","DEBATE","DECIDE","DEFEND","DEFINE",
  "DEMAND","DEPEND","DESIGN","DESIRE","DETAIL","DIFFER","DINNER","DIRECT",
  "DIVIDE","DOLLAR","DOUBLE","DRIVEN","DURING","EASILY","EITHER","EMPLOY",
  "ENABLE","ENERGY","ENGAGE","ENSURE","ENTIRE","ESCAPE","ESTATE","EXCEPT",
  "EXPECT","FACTOR","FAMOUS","FATHER","FINISH","FLIGHT","FOLLOW","FOREST",
  "FORGET","FORMAL","FOSTER","FRIEND","FUTURE","GATHER","GENDER","GENTLE",
  "GLOBAL","GOLDEN","GROUND","GROWTH","HANDLE","HAPPEN","HEALTH","HEIGHT",
  "HIDDEN","HONEST","HORROR","HUNGER","IMPOSE","INDEED","INSIDE","INVEST",
  "ISLAND","ITSELF","JUNGLE","JUNIOR","LAUNCH","LAWYER","LEADER","LENGTH",
  "LESSON","LISTEN","LITTLE","MARKET","MASTER","MATTER","MEDIUM","MEMBER",
  "METHOD","MIDDLE","MINUTE","MIRROR","MODERN","MOMENT","MOTHER","MOTION",
  "MURDER","MUSCLE","MUTUAL","NATURE","NEARLY","NEEDLE","NORMAL","NOTICE",
  "NUMBER","OBTAIN","OFFICE","OPTION","ORANGE","OUTPUT","OTHERS","OUTLET",
  "OUTRUN","PARENT","PEOPLE","PERIOD","PERMIT","PERSON","PHRASE","PLANET",
  "PLEASE","PLENTY","POCKET","POLICE","POLICY","POORLY","PREFER","PRETTY",
  "PRINCE","PRISON","PROFIT","PROPER","PROVEN","PUBLIC","PURSUE","PUZZLE",
  "REASON","RECENT","RECALL","REDUCE","REFORM","REFUSE","REMAIN","RESULT",
  "RETURN","REVEAL","REVIEW","ROBUST","SAFETY","SAMPLE","SCHOOL","SEASON",
  "SECOND","SECRET","SECURE","SENIOR","SIGNAL","SIMPLE","SINGLE","SISTER",
  "SPRING","SQUARE","STABLE","STATUS","STRICT","STRING","STRONG","SUNSET",
  "SUPPLY","SYSTEM","TALENT","TARGET","TENDER","THANKS","THEORY","THOUGH",
  "THREAT","TONGUE","TREATY","TRIPLE","TROUBLE","UNEASY","UNIQUE","UNITED",
  "UNLESS","UNLIKE","UPDATE","USEFUL","VALLEY","VICTIM","VIRTUE","VISION",
  "WEEKLY","WEIGHT","WONDER","WORKER","WORTHY","YELLOW","ZEALOT","ZIPPER",
] as const;

export const WORD_LIST_7: readonly string[] = [
  "ABANDON","ACCOUNT","ACHIEVE","ACQUIRE","BECAUSE","BENEFIT","CAPTAIN",
  "CENTURY","CHAPTER","CIRCUIT","CLIMATE","COMFORT","COMPETE","CONTAIN",
  "CONTROL","CONVERT","CORRECT","COUNCIL","COUNSEL","CULTURE","CURRENT",
  "COMPANY","COMPLEX","CONCERN","CONFIRM","CONNECT","CONDUCT","CAPABLE",
  "CAPTURE","CARTOON","CERTAIN","CHARITY","CHICKEN","COASTAL","COLLEGE",
  "COMBINE","CONSENT","CONSUME","CONTEXT","COURAGE","CREATED","CRYSTAL",
  "DECIDED","DEFAULT","DELIVER","DESPITE","DEVELOP","DISPLAY","DISTANT",
  "DRAWING","ECONOMY","ELEMENT","ENFORCE","EXAMINE","EXAMPLE","EXPLAIN",
  "FACTORY","FAILURE","FANTASY","FASHION","FEATURE","FEELING","PROBLEM",
  "FORWARD","FRAGILE","FREEDOM","GENERAL","GESTURE","HISTORY","HUNDRED",
  "IMAGINE","IMPROVE","INCLUDE","INSPIRE","INTEGER","JOURNEY","JUSTICE",
  "KITCHEN","LANDING","MACHINE","MEASURE","MESSAGE","MILLION","NATURAL",
  "NETWORK","NOTHING","OBVIOUS","OPERATE","OUTDOOR","PATIENT","PATTERN",
  "PERFECT","PERFORM","PERHAPS","PICTURE","PLASTIC","POPULAR","PORTION",
  "POSSESS","PREPARE","PREVENT","PRIVATE","PROCESS","PRODUCT","PROJECT",
  "PROTECT","PROVIDE","PURPOSE","QUALIFY","QUALITY","QUARTER","REALIZE",
  "RECEIVE","REPLACE","REQUIRE","RESPECT","RESPOND","RESTORE","RETREAT",
  "REUNION","REVENUE","REVERSE","SERVICE","SESSION","SHELTER","SURFACE",
  "TEACHER","THROUGH","TONIGHT","TOTALLY","TROUBLE","VISIBLE","WELCOME",
] as const;

export type WordLength = 3 | 4 | 5 | 6 | 7;

export function getWordList(len: WordLength): readonly string[] {
  if (len === 3) return WORD_LIST_3;
  if (len === 4) return WORD_LIST_4;
  if (len === 5) return WORD_LIST_5;
  if (len === 6) return WORD_LIST_6;
  return WORD_LIST_7;
}

export function canFormFrom(word: string, letters: readonly string[]): boolean {
  const avail = [...letters];
  for (const ch of word.toUpperCase()) {
    const idx = avail.indexOf(ch);
    if (idx === -1) return false;
    avail.splice(idx, 1);
  }
  return true;
}

export function getValidSubwords(targetLetters: readonly string[], targetLen: number): { target: string; subwords: string[] } {
  // Pick a target word
  const pool = getWordList(targetLen as WordLength).filter(w => w.length === targetLen);
  // subwords must be formable from the target's letters
  const letters = pool[0] ? [...pool[0]] : [];

  const subwords: string[] = [];
  for (const list of [WORD_LIST_3, WORD_LIST_4, WORD_LIST_5, WORD_LIST_6, WORD_LIST_7]) {
    for (const w of list) {
      if (w.length >= 3 && w.length <= targetLen && canFormFrom(w, targetLetters)) {
        subwords.push(w);
      }
    }
  }
  void letters;
  return { target: pool[0] ?? "", subwords };
}
