// Hangman word list — 200+ uppercase words, lengths 4-10
export const HANGMAN_WORDS: readonly string[] = [
  // 4-letter words
  "BEAR","BIRD","BOAT","BOMB","BOOK","BOOT","BULL","BURN","CAGE","CAKE",
  "CAMP","CARD","CART","CAVE","CHEF","CHIP","CLUB","COAL","COAT","CODE",
  "COIN","CORK","CORN","CRAB","CREW","CROP","CROW","DARK","DART","DAWN",
  "DECK","DEER","DESK","DIAL","DISH","DOCK","DOOR","DRUM","DUKE","DUSK",
  "DUST","EARL","EDGE","EPIC","FACE","FACT","FAIR","FARM","FIRE","FISH",
  "FLAG","FLAT","FOAM","FOLD","FOLK","FORK","FORT","FROG","FUEL","GAME",
  "GEAR","GIFT","GIRL","GLOW","GLUE","GOAL","GOLD","GOLF","GRAB","GRAY",
  "GRIM","GRIP","GULF","HALF","HALL","HAND","HAWK","HELM","HERB","HERO",
  "HIDE","HILL","HINT","HIVE","HORN","HULK","HUNT","HUSK","HYMN","ICON",

  // 5-letter words
  "ADOBE","AGENT","ALIEN","ALTAR","ANGEL","ANVIL","APPLE","APRON","ARROW","ATLAS",
  "BANJO","BARON","BERRY","BLAZE","BLISS","BLOOM","BOARD","BRAID","BRAVE","BREAD",
  "BROTH","BRUSH","BUILD","BULLY","BURRO","BURST","CAMEL","CANOE","CARGO","CARVE",
  "CHALK","CHARM","CHART","CHASE","CHECK","CHEEK","CHESS","CHEST","CHOIR","CHORD",
  "CLAIM","CLAMP","CLASP","CLASS","CLIFF","CLIMB","CLOAK","CLOCK","CLONE","CLOUD",
  "COACH","COAST","COBRA","COMET","CORAL","COUNT","COURT","COVER","CRAFT","CRANE",
  "CRASH","CREST","CROSS","CROWD","CROWN","CRUST","CUTIE","DAISY","DANCE","DEVIL",
  "DIARY","DIGIT","DINER","DISCO","DITCH","DODGE","DOLLY","DRAIN","DRAKE","DRAMA",
  "DRAWL","DREAD","DRIFT","DRILL","DRINK","DRIVE","DRONE","DROWN","DUNCE","DWARF",
  "EAGLE","EARTH","EBONY","ELBOW","EMBER","EMPTY","EPOCH","EQUIP","ERODE","EVENT",

  // 6-letter words
  "BRIDGE","BUTTER","CAMERA","CANOPY","CASTLE","CHORUS","CIRCUS","CLOVER","COBALT",
  "COLONY","COMBAT","COMET","COPPER","CORNER","COTTON","COUGAR","COYOTE","CRAYON",
  "CURFEW","CUSTOM","CYBORG","DANCER","DANGER","DANISH","DAPPER","DAZZLE","DEBRIS",
  "DECODE","DEMON","DESERT","DEVICE","DEVOUR","DIFFER","DIMPLE","DONKEY","DOODLE",
  "DOCTOR","DOLLAR","DONKEY","DRAWER","DUMPLING","DUNGEON","EAGLE","EMBLEM","EMERGE",
  "EMPIRE","ENGINE","ENIGMA","ESCAPE","ESTATE","FAMINE","FANDOM","FATHOM","FENNEL",
  "FESTER","FILTER","FINGER","FLEDGE","FLIGHT","FLOWER","FLYWAY","FOREST","FOSSIL",
  "FROLIC","FROZEN","FUNNEL","FUSION","GALAXY","GALLEY","GARLIC","GEYSER","GLITCH",
  "GOBLIN","GOITER","GRAVEL","GRILLE","GROVEL","GUTTER","HAMMER","HARBOR","HARNESS",

  // 7-letter words
  "BARNACLE","CAPTAIN","CHARIOT","CHICKEN","CHIMNEY","CIRCUIT","CLIMATE","CLUSTER",
  "COBWEB","COMPASS","CONCERT","CONTEST","CRICKET","CRYSTAL","CURTAIN","CUSHION",
  "CYCLONE","DIAMOND","DOLPHIN","DRAWING","DYNASTY","ECLIPSE","EMBASSY","EMPEROR",
  "ESSENCE","EYEBROW","FACTORY","FANTASY","FEATHER","FICTION","FIGHTER","FISHNET",
  "FLICKER","FLUTTER","FOGHORN","FRECKLE","FREEDOM","FURNACE","GATEWAY","GENERAL",
  "GESTURE","GIRAFFE","GLACIER","GRAVITY","GRIFFIN","HARVEST","HAUNTED","HEDGEHOG",

  // 8+ letter words
  "ABSOLUTE","ABSTRACT","ABUNDANT","ACADEMIC","ACCIDENT","ACCURATE","ALPHABET","AMBITION",
  "ANCESTOR","ANIMATOR","ANNOUNCE","ANTELOPE","ARCHIVAL","ARMCHAIR","ASTEROID","BACKYARD",
  "BACKBONE","BAILMENT","BALCONY","BANDWAGON","BARRACKS","BASEMENT","BEHAVIOR","BIRDCAGE",
  "BLACKOUT","BLIZZARD","BOOKCASE","BOUNDARY","BROADWAY","BUILDING","BULLDOZE","BULLETIN",
  "CALENDAR","CARRIAGE","CATEGORY","CHAMPION","CHANDLER","CHEMICAL","CHERRIES","CHESTNUT",
  "CHILDHOOD","CHLORINE","CINNAMON","CIRCULAR","CIVILIZE","CLAPPING","COLOSSUS","COMMENCE",
  "COMPOUND","CONCLUDE","CONQUEST","CONSIDER","CONSUMER","CONTRACT","CONVINCE","CORRIDOR",
  "MOUNTAIN","KEYBOARD","CALENDAR","EXPLORER","FOOTBALL","TRIANGLE","UMBRELLA","VACATION",
  "WORKSHOP","DINOSAUR","PLATINUM","SEMESTER","ENVELOPE","PHARMACY","DOWNTOWN","CHAMPION",
  "CALENDAR","DISCOVER","FLAMINGO","HERCULES","INDUSTRY","NOTEBOOK","PENTAGON","SEQUENCE",
] as const;

export function filterByLength(words: readonly string[], lengthFilter: "any" | "short" | "medium" | "long"): readonly string[] {
  switch (lengthFilter) {
    case "short":  return words.filter(w => w.length >= 4 && w.length <= 5);
    case "medium": return words.filter(w => w.length >= 6 && w.length <= 7);
    case "long":   return words.filter(w => w.length >= 8);
    default:       return words;
  }
}
