import {
  makeInitialState,
  reducer as engineReducer,
  isTerminal as engineTerminal,
  type MahjongState,
  type MahjongAction,
  type TilePos,
} from "../_shared/mahjongEngine.js";

export type MahjongSeasonsCycleState = MahjongState;
export type MahjongSeasonsCycleAction = MahjongAction;

export const LAYOUT: TilePos[] = [
  { row: 0, col: 0, layer: 0 },
  { row: 0, col: 1, layer: 0 },
  { row: 0, col: 2, layer: 0 },
  { row: 0, col: 3, layer: 0 },
  { row: 1, col: 0, layer: 0 },
  { row: 1, col: 1, layer: 0 },
  { row: 1, col: 2, layer: 0 },
  { row: 1, col: 3, layer: 0 },
  { row: 2, col: 0, layer: 0 },
  { row: 2, col: 1, layer: 0 },
  { row: 2, col: 2, layer: 0 },
  { row: 2, col: 3, layer: 0 },
  { row: 3, col: 0, layer: 0 },
  { row: 3, col: 1, layer: 0 },
  { row: 3, col: 2, layer: 0 },
  { row: 3, col: 3, layer: 0 },
  { row: 1, col: 1, layer: 1 },
  { row: 1, col: 2, layer: 1 },
  { row: 2, col: 1, layer: 1 },
  { row: 2, col: 2, layer: 1 },
  { row: 0, col: 6, layer: 0 },
  { row: 0, col: 7, layer: 0 },
  { row: 0, col: 8, layer: 0 },
  { row: 0, col: 9, layer: 0 },
  { row: 1, col: 6, layer: 0 },
  { row: 1, col: 7, layer: 0 },
  { row: 1, col: 8, layer: 0 },
  { row: 1, col: 9, layer: 0 },
  { row: 2, col: 6, layer: 0 },
  { row: 2, col: 7, layer: 0 },
  { row: 2, col: 8, layer: 0 },
  { row: 2, col: 9, layer: 0 },
  { row: 3, col: 6, layer: 0 },
  { row: 3, col: 7, layer: 0 },
  { row: 3, col: 8, layer: 0 },
  { row: 3, col: 9, layer: 0 },
  { row: 1, col: 7, layer: 1 },
  { row: 1, col: 8, layer: 1 },
  { row: 2, col: 7, layer: 1 },
  { row: 2, col: 8, layer: 1 },
  { row: 6, col: 0, layer: 0 },
  { row: 6, col: 1, layer: 0 },
  { row: 6, col: 2, layer: 0 },
  { row: 6, col: 3, layer: 0 },
  { row: 7, col: 0, layer: 0 },
  { row: 7, col: 1, layer: 0 },
  { row: 7, col: 2, layer: 0 },
  { row: 7, col: 3, layer: 0 },
  { row: 8, col: 0, layer: 0 },
  { row: 8, col: 1, layer: 0 },
  { row: 8, col: 2, layer: 0 },
  { row: 8, col: 3, layer: 0 },
  { row: 9, col: 0, layer: 0 },
  { row: 9, col: 1, layer: 0 },
  { row: 9, col: 2, layer: 0 },
  { row: 9, col: 3, layer: 0 },
  { row: 7, col: 1, layer: 1 },
  { row: 7, col: 2, layer: 1 },
  { row: 8, col: 1, layer: 1 },
  { row: 8, col: 2, layer: 1 },
  { row: 6, col: 6, layer: 0 },
  { row: 6, col: 7, layer: 0 },
  { row: 6, col: 8, layer: 0 },
  { row: 6, col: 9, layer: 0 },
  { row: 7, col: 6, layer: 0 },
  { row: 7, col: 7, layer: 0 },
  { row: 7, col: 8, layer: 0 },
  { row: 7, col: 9, layer: 0 },
  { row: 8, col: 6, layer: 0 },
  { row: 8, col: 7, layer: 0 },
  { row: 8, col: 8, layer: 0 },
  { row: 8, col: 9, layer: 0 },
  { row: 9, col: 6, layer: 0 },
  { row: 9, col: 7, layer: 0 },
  { row: 9, col: 8, layer: 0 },
  { row: 9, col: 9, layer: 0 },
  { row: 7, col: 7, layer: 1 },
  { row: 7, col: 8, layer: 1 },
  { row: 8, col: 7, layer: 1 },
  { row: 8, col: 8, layer: 1 }
];

export function initialState(seed: number, _settings: Record<string, never> = {}): MahjongState {
  void _settings;
  return makeInitialState(LAYOUT, seed);
}

export const reducer = engineReducer;
export const isTerminal = engineTerminal;
