// Specifications for cooperative games. Each spec wires the shared coop-engine
// with thematic tactics, accent color, scenario/threat labels.
const T = (id, label, emoji, effort, reliability, threatPush, desc) => ({ id, label, emoji, effort, reliability, threatPush, desc });

export const COOP_SPECS = [
  // PANDEMIC family
  { folder: "pandemic-base", prefix: "pdb", title: "Pandemic", accent: "#dc2626", bg: "#fef2f2",
    description: "Cooperative disease control around the globe.",
    cfg: { totalRounds: 12, progressTarget: 60, threatPerRound: 3, startMorale: 3, threatBreakpoint: 6, allyEffort: 3, allyClutch: 0.35, scenarioLabel: "Disease Outbreak", scenarioEmoji: "🦠", progressLabel: "Cures", threatLabel: "Infections", moraleLabel: "Outbreaks left" },
    intro: "Find cures before disease spreads to four cities. Pick a tactic each round.",
    tactics: [T("treat","Treat Disease","💉",4,0.85,1,"Remove cubes in a hot zone."), T("research","Research Cure","🧪",6,0.55,0,"Bank cards toward a cure."), T("fly","Fly to Hotspot","✈️",3,0.95,2,"Reposition for response."), T("build","Build Station","🏥",2,1.0,1,"Foundation for later moves.")] },
  { folder: "pandemic-hot-zone-na", prefix: "phna", title: "Pandemic Hot Zone N.A.", accent: "#dc2626", bg: "#fef2f2",
    description: "Faster Pandemic in three North American cities.",
    cfg: { totalRounds: 8, progressTarget: 45, threatPerRound: 3, startMorale: 2, threatBreakpoint: 5, allyEffort: 4, allyClutch: 0.4, scenarioLabel: "Hot Zone: North America", scenarioEmoji: "🌎", progressLabel: "Cures", threatLabel: "Hotspots", moraleLabel: "Health" },
    intro: "30-minute Pandemic. Fewer rounds, sharper threat.",
    tactics: [T("treat","Treat","💉",4,0.85,1,"Reduce active cases."), T("cure","Cure","🧪",6,0.5,0,"Long-term progress."), T("travel","Travel","✈️",3,0.95,2,"Respond fast."), T("supply","Resupply","📦",2,1.0,1,"Stable gain.")] },
  { folder: "pandemic-fall-of-rome", prefix: "pfor", title: "Pandemic: Fall of Rome", accent: "#92400e", bg: "#fef3c7",
    description: "Defend Rome from invading barbarian tribes.",
    cfg: { totalRounds: 12, progressTarget: 65, threatPerRound: 4, startMorale: 3, threatBreakpoint: 6, allyEffort: 3, allyClutch: 0.3, scenarioLabel: "Barbarians at the Gates", scenarioEmoji: "🏛️", progressLabel: "Alliances", threatLabel: "Invasions", moraleLabel: "Cities held" },
    intro: "Forge alliances before tribes sack Rome.",
    tactics: [T("battle","Battle","⚔️",5,0.7,2,"Engage barbarians directly."), T("forge","Forge Alliance","🤝",6,0.55,0,"Convert a tribe."), T("march","March Legion","🛡️",3,0.95,2,"Reposition troops."), T("fort","Fortify","🏰",2,1.0,1,"Defensive gain.")] },
  { folder: "pandemic-iberia", prefix: "pibe", title: "Pandemic: Iberia", accent: "#1e40af", bg: "#dbeafe",
    description: "Quell disease in 19th-century Iberia.",
    cfg: { totalRounds: 10, progressTarget: 55, threatPerRound: 3, startMorale: 3, threatBreakpoint: 6, allyEffort: 3, allyClutch: 0.35, scenarioLabel: "Iberian Peninsula", scenarioEmoji: "🚂", progressLabel: "Research", threatLabel: "Infections", moraleLabel: "Resilience" },
    intro: "Build railways and purify water to fight disease.",
    tactics: [T("rail","Build Rail","🚂",4,0.85,1,"Connect regions."), T("purify","Purify Water","💧",5,0.7,1,"Prevent infection growth."), T("cure","Research","🧪",6,0.5,0,"Toward a cure."), T("hosp","Hospital","🏥",3,1.0,1,"Steady care.")] },
  { folder: "pandemic-in-the-lab", prefix: "pitl", title: "Pandemic: In the Lab", accent: "#7c3aed", bg: "#ede9fe",
    description: "Lab-research expansion: synthesize cures from samples.",
    cfg: { totalRounds: 12, progressTarget: 70, threatPerRound: 3, startMorale: 3, threatBreakpoint: 6, allyEffort: 3, allyClutch: 0.4, scenarioLabel: "CDC Laboratory", scenarioEmoji: "🔬", progressLabel: "Cure progress", threatLabel: "Outbreaks", moraleLabel: "Funding" },
    intro: "Sequence pathogens; field actions still required.",
    tactics: [T("sequence","Sequence","🧬",6,0.55,0,"Big lab progress."), T("treat","Field Treat","💉",4,0.85,1,"Direct treatment."), T("sample","Sample","🧪",3,0.9,1,"Collect sample."), T("publish","Publish Paper","📄",2,1.0,1,"Lock in results.")] },
  { folder: "pandemic-legacy-s1", prefix: "ple1", title: "Pandemic Legacy S1", accent: "#b91c1c", bg: "#fee2e2",
    description: "Cooperative campaign: faded city by city.",
    cfg: { totalRounds: 14, progressTarget: 80, threatPerRound: 4, startMorale: 3, threatBreakpoint: 6, allyEffort: 3, allyClutch: 0.3, scenarioLabel: "Faded Cities — Year 1", scenarioEmoji: "📜", progressLabel: "Mission Progress", threatLabel: "Faded", moraleLabel: "Funding" },
    intro: "Each round you commit a permanent action toward saving the world.",
    tactics: [T("operate","Operate","🏥",4,0.8,1,"Field operation."), T("research","Research","🔬",6,0.55,0,"Lab gains."), T("relocate","Relocate","✈️",3,0.95,2,"Move to crisis."), T("dispatch","Dispatch","🛰️",3,0.9,1,"Coordinate.")] },
  { folder: "pandemic-legacy-s2", prefix: "ple2", title: "Pandemic Legacy S2", accent: "#0891b2", bg: "#cffafe",
    description: "Plague-ravaged future: rebuild from havens.",
    cfg: { totalRounds: 14, progressTarget: 85, threatPerRound: 4, startMorale: 3, threatBreakpoint: 6, allyEffort: 3, allyClutch: 0.3, scenarioLabel: "Year 71", scenarioEmoji: "⚓", progressLabel: "Reclaimed", threatLabel: "Plague", moraleLabel: "Havens" },
    intro: "Run supply lines; reclaim mainland regions.",
    tactics: [T("supply","Supply Run","📦",4,0.85,1,"Move goods."), T("scout","Scout","🔭",5,0.7,1,"Reveal."), T("build","Establish","🏗️",6,0.55,0,"Construct outpost."), T("guard","Guard","🛡️",3,1.0,1,"Hold ground.")] },
  { folder: "pandemic-multistep", prefix: "pmst", title: "Pandemic Multi-Step", accent: "#dc2626", bg: "#fef2f2",
    description: "Pandemic variant with chained turn actions.",
    cfg: { totalRounds: 10, progressTarget: 55, threatPerRound: 3, startMorale: 3, threatBreakpoint: 6, allyEffort: 3, allyClutch: 0.4, scenarioLabel: "Outbreak Chain", scenarioEmoji: "🔗", progressLabel: "Steps Completed", threatLabel: "Spread", moraleLabel: "Health" },
    intro: "Each tactic chains: minor + major effect. Keep ahead of spread.",
    tactics: [T("treatfly","Treat+Fly","💉",5,0.75,2,"Treat then move."), T("buildres","Build+Research","🏥",6,0.55,1,"Build & research."), T("dispatch","Dispatch","🚀",4,0.85,1,"Move ally."), T("emerg","Emergency","🚨",3,1.0,2,"Big push.")] },

  // FORBIDDEN family
  { folder: "forbidden-island-coop", prefix: "fbi", title: "Forbidden Island", accent: "#0d9488", bg: "#ccfbf1",
    description: "Recover treasures before the island sinks.",
    cfg: { totalRounds: 10, progressTarget: 50, threatPerRound: 3, startMorale: 3, threatBreakpoint: 6, allyEffort: 3, allyClutch: 0.4, scenarioLabel: "Sinking Island", scenarioEmoji: "🏝️", progressLabel: "Treasures", threatLabel: "Flood", moraleLabel: "Tiles" },
    intro: "Capture four idols and escape via the helipad.",
    tactics: [T("shoreup","Shore Up","🪨",4,0.9,2,"Push back the flood."), T("capture","Capture Treasure","💎",6,0.55,0,"Major progress."), T("move","Move/Swim","🏊",3,0.95,1,"Reposition."), T("airlift","Airlift","🚁",2,1.0,2,"Emergency rescue.")] },
  { folder: "forbidden-jungle-coop", prefix: "fbj", title: "Forbidden Jungle", accent: "#16a34a", bg: "#dcfce7",
    description: "Escape an overgrown jungle before vines consume all.",
    cfg: { totalRounds: 10, progressTarget: 55, threatPerRound: 3, startMorale: 3, threatBreakpoint: 6, allyEffort: 3, allyClutch: 0.35, scenarioLabel: "Tangled Vines", scenarioEmoji: "🌿", progressLabel: "Path Cleared", threatLabel: "Vines", moraleLabel: "Stamina" },
    intro: "Hack a path through cursed jungle.",
    tactics: [T("hack","Hack","🪓",5,0.8,2,"Cut vines."), T("relic","Relic","🗿",6,0.55,0,"Recover relic."), T("trail","Blaze Trail","🥾",3,0.95,1,"Move team."), T("camp","Camp","⛺",2,1.0,1,"Recover.")] },
  { folder: "forbidden-desert-coop", prefix: "fbd", title: "Forbidden Desert", accent: "#d97706", bg: "#fef3c7",
    description: "Assemble a flying machine before the sand buries you.",
    cfg: { totalRounds: 12, progressTarget: 60, threatPerRound: 3, startMorale: 3, threatBreakpoint: 5, allyEffort: 3, allyClutch: 0.35, scenarioLabel: "Storm-Buried Tomb", scenarioEmoji: "🏜️", progressLabel: "Parts", threatLabel: "Sandstorm", moraleLabel: "Water" },
    intro: "Find four parts of the airship.",
    tactics: [T("excavate","Excavate","🪣",4,0.85,1,"Clear sand."), T("part","Find Part","⚙️",6,0.55,0,"Locate fragment."), T("water","Drink Water","💧",2,1.0,1,"Replenish."), T("move","Move","🐫",3,0.95,1,"Travel.")] },
  { folder: "forbidden-sky-coop", prefix: "fbs", title: "Forbidden Sky", accent: "#3b82f6", bg: "#dbeafe",
    description: "Build a rocket on a thunderhead and escape.",
    cfg: { totalRounds: 10, progressTarget: 65, threatPerRound: 4, startMorale: 3, threatBreakpoint: 6, allyEffort: 3, allyClutch: 0.35, scenarioLabel: "Lightning Storm", scenarioEmoji: "⚡", progressLabel: "Rocket", threatLabel: "Strikes", moraleLabel: "Heart" },
    intro: "Wire circuits, dodge bolts.",
    tactics: [T("wire","Wire","🔌",5,0.7,1,"Connect circuits."), T("part","Build Stage","🚀",6,0.55,0,"Big build."), T("rope","Rope","🪢",3,0.95,1,"Climb."), T("ground","Ground","🛡️",2,1.0,2,"Lightning rod.")] },

  // SPIRIT ISLAND
  { folder: "spirit-island-coop", prefix: "spi", title: "Spirit Island", accent: "#059669", bg: "#d1fae5",
    description: "Spirits defend their island from invading colonizers.",
    cfg: { totalRounds: 10, progressTarget: 60, threatPerRound: 4, startMorale: 4, threatBreakpoint: 7, allyEffort: 3, allyClutch: 0.4, scenarioLabel: "Invader Tide", scenarioEmoji: "🌊", progressLabel: "Fear", threatLabel: "Blight", moraleLabel: "Presence" },
    intro: "Generate fear faster than invaders blight the island.",
    tactics: [T("power","Major Power","🔥",6,0.6,1,"Cast a major spell."), T("minor","Minor Power","💨",4,0.85,0,"Steady fear."), T("growth","Growth","🌱",3,0.95,1,"Expand presence."), T("defend","Defend Land","🛡️",2,1.0,2,"Stop blight.")] },
  { folder: "spirit-island-jagged", prefix: "spj", title: "Spirit Island: Jagged Earth", accent: "#65a30d", bg: "#ecfccb",
    description: "Volcanic and rocky spirits overwhelm with terrain.",
    cfg: { totalRounds: 10, progressTarget: 65, threatPerRound: 4, startMorale: 4, threatBreakpoint: 7, allyEffort: 3, allyClutch: 0.4, scenarioLabel: "Jagged Earth Awakens", scenarioEmoji: "🌋", progressLabel: "Fear", threatLabel: "Blight", moraleLabel: "Presence" },
    intro: "Erupt mountains; trap colonists in stone.",
    tactics: [T("erupt","Erupt","🌋",7,0.55,1,"Volcanic devastation."), T("quake","Earthquake","💢",5,0.75,1,"Shake the land."), T("grow","Grow","🌱",3,0.95,0,"Expand."), T("defend","Stoneskin","🪨",2,1.0,2,"Protect.")] },
  { folder: "spirit-island-nature", prefix: "spn", title: "Spirit Island: Nature Incarnate", accent: "#16a34a", bg: "#dcfce7",
    description: "Nature spirits bend rivers and roots to drive invaders.",
    cfg: { totalRounds: 10, progressTarget: 60, threatPerRound: 4, startMorale: 4, threatBreakpoint: 7, allyEffort: 3, allyClutch: 0.4, scenarioLabel: "Wild Reclamation", scenarioEmoji: "🌳", progressLabel: "Fear", threatLabel: "Blight", moraleLabel: "Presence" },
    intro: "Roots strangle; rivers wash away.",
    tactics: [T("roots","Roots","🌳",6,0.6,1,"Grasp village."), T("flood","Flood","🌊",5,0.75,1,"Drown towns."), T("grow","Grow","🌱",3,0.95,0,"Expand."), T("guard","Guard","🛡️",2,1.0,2,"Protect.")] },

  // AEONS END
  { folder: "aeons-end-mages", prefix: "aem", title: "Aeon's End: Mages", accent: "#7c3aed", bg: "#ede9fe",
    description: "Spell-slinging mages defend Gravehold from the Nameless.",
    cfg: { totalRounds: 12, progressTarget: 70, threatPerRound: 4, startMorale: 4, threatBreakpoint: 6, allyEffort: 3, allyClutch: 0.35, scenarioLabel: "The Breach", scenarioEmoji: "🌌", progressLabel: "Damage to Nameless", threatLabel: "Nemesis Power", moraleLabel: "Gravehold" },
    intro: "Prep gems, cast through breaches.",
    tactics: [T("cast","Cast Spell","✨",6,0.7,1,"Big damage."), T("prep","Prep Spell","🔮",4,0.95,0,"Steady setup."), T("gem","Gain Gem","💎",3,1.0,0,"Income."), T("focus","Focus Breach","🎯",2,1.0,1,"Speed up.")] },
  { folder: "aeons-end-coop", prefix: "aec", title: "Aeon's End Coop", accent: "#7c3aed", bg: "#ede9fe",
    description: "Aeon's End cooperative format.",
    cfg: { totalRounds: 12, progressTarget: 70, threatPerRound: 4, startMorale: 4, threatBreakpoint: 6, allyEffort: 3, allyClutch: 0.35, scenarioLabel: "Gravehold Defense", scenarioEmoji: "🌑", progressLabel: "Nemesis HP", threatLabel: "Tokens", moraleLabel: "Gravehold" },
    intro: "Coordinate spells with another mage.",
    tactics: [T("cast","Cast","✨",6,0.7,1,"Damage."), T("prep","Prep","🔮",4,0.95,0,"Set up."), T("gem","Gem","💎",3,1.0,0,"Charge."), T("crystal","Focus","🎯",2,1.0,1,"Open breach.")] },
  { folder: "aeons-end-legacy", prefix: "ael", title: "Aeon's End Legacy", accent: "#581c87", bg: "#f3e8ff",
    description: "Aeon's End campaign with persistent upgrades.",
    cfg: { totalRounds: 14, progressTarget: 85, threatPerRound: 4, startMorale: 4, threatBreakpoint: 6, allyEffort: 3, allyClutch: 0.35, scenarioLabel: "World of Estoria", scenarioEmoji: "🗺️", progressLabel: "Campaign", threatLabel: "Corruption", moraleLabel: "Gravehold" },
    intro: "Permanent unlocks shape future games.",
    tactics: [T("cast","Cast","✨",6,0.7,1,"Damage."), T("prep","Prep","🔮",4,0.95,0,"Set up."), T("recruit","Recruit","👥",3,0.9,0,"New ally."), T("focus","Focus","🎯",2,1.0,1,"Breach.")] },
  { folder: "aeons-end-war-eternal", prefix: "aewe", title: "Aeon's End: War Eternal", accent: "#9333ea", bg: "#f3e8ff",
    description: "Stand-alone Aeon's End with new mages.",
    cfg: { totalRounds: 12, progressTarget: 75, threatPerRound: 4, startMorale: 4, threatBreakpoint: 6, allyEffort: 3, allyClutch: 0.35, scenarioLabel: "Eternal War", scenarioEmoji: "⚔️", progressLabel: "Damage", threatLabel: "Nemesis", moraleLabel: "Gravehold" },
    intro: "Dual-class spell loadouts.",
    tactics: [T("cast","Cast","✨",6,0.7,1,"Damage."), T("prep","Prep","🔮",4,0.95,0,"Set up."), T("artifact","Artifact","🪙",3,1.0,1,"Effect."), T("focus","Focus","🎯",2,1.0,1,"Breach.")] },

  // ARKHAM / LOTR / Marvel
  { folder: "arkham-lcg-coop", prefix: "arkc", title: "Arkham Horror LCG", accent: "#0c4a6e", bg: "#e0f2fe",
    description: "Mythos investigators stop creeping horrors.",
    cfg: { totalRounds: 12, progressTarget: 70, threatPerRound: 3, startMorale: 4, threatBreakpoint: 6, allyEffort: 3, allyClutch: 0.35, scenarioLabel: "Mythos Encroaches", scenarioEmoji: "🔮", progressLabel: "Clues", threatLabel: "Doom", moraleLabel: "Sanity" },
    intro: "Investigate, gather clues, fight horrors.",
    tactics: [T("investigate","Investigate","🔍",5,0.75,1,"Gain clues."), T("fight","Fight","⚔️",6,0.55,1,"Damage horror."), T("evade","Evade","🏃",3,0.95,0,"Slip away."), T("commit","Commit Skill","💪",2,1.0,1,"Boost test.")] },
  { folder: "arkham-lcg-fellow", prefix: "arkf", title: "Arkham LCG: Fellowship", accent: "#0e7490", bg: "#cffafe",
    description: "Arkham LCG cooperative fellowship campaign.",
    cfg: { totalRounds: 12, progressTarget: 70, threatPerRound: 3, startMorale: 4, threatBreakpoint: 6, allyEffort: 3, allyClutch: 0.35, scenarioLabel: "Fellowship Campaign", scenarioEmoji: "📓", progressLabel: "Clues", threatLabel: "Doom", moraleLabel: "Sanity" },
    intro: "Multi-investigator hand pooling.",
    tactics: [T("investigate","Investigate","🔍",5,0.75,1,"Clues."), T("fight","Fight","⚔️",6,0.55,1,"Damage."), T("aid","Aid Ally","🤝",3,0.95,0,"Ally helps."), T("rally","Rally","🛡️",2,1.0,1,"Heal sanity.")] },
  { folder: "lotr-lcg-coop", prefix: "lotr", title: "LOTR LCG", accent: "#15803d", bg: "#dcfce7",
    description: "Heroes of Middle-earth on quests.",
    cfg: { totalRounds: 11, progressTarget: 60, threatPerRound: 3, startMorale: 4, threatBreakpoint: 6, allyEffort: 3, allyClutch: 0.4, scenarioLabel: "Shadow of Mirkwood", scenarioEmoji: "🧝", progressLabel: "Quest", threatLabel: "Threat", moraleLabel: "Heroes" },
    intro: "Quest, fight, and survive Sauron's gaze.",
    tactics: [T("quest","Quest","🌟",5,0.75,2,"Lower threat."), T("attack","Attack","🗡️",5,0.7,1,"Slay enemy."), T("ally","Play Ally","🤝",3,0.95,0,"Reinforcement."), T("heal","Heal","💖",2,1.0,1,"Restore.")] },
  { folder: "lotr-lcg-fellow", prefix: "lotrf", title: "LOTR LCG: Fellowship", accent: "#16a34a", bg: "#dcfce7",
    description: "Fellowship multi-deck campaign of LOTR LCG.",
    cfg: { totalRounds: 11, progressTarget: 65, threatPerRound: 3, startMorale: 4, threatBreakpoint: 6, allyEffort: 3, allyClutch: 0.4, scenarioLabel: "Fellowship Campaign", scenarioEmoji: "💍", progressLabel: "Quest", threatLabel: "Threat", moraleLabel: "Heroes" },
    intro: "Saga deck campaign with persistent rewards.",
    tactics: [T("quest","Quest","🌟",5,0.75,2,"Quest."), T("attack","Attack","🗡️",5,0.7,1,"Slay."), T("aid","Aid","🤝",3,0.95,0,"Help."), T("heal","Heal","💖",2,1.0,1,"Heal.")] },
  { folder: "lord-of-rings-lcg", prefix: "lotrl", title: "Lord of the Rings LCG", accent: "#166534", bg: "#bbf7d0",
    description: "Lord of the Rings LCG full campaign.",
    cfg: { totalRounds: 12, progressTarget: 70, threatPerRound: 3, startMorale: 4, threatBreakpoint: 6, allyEffort: 3, allyClutch: 0.4, scenarioLabel: "Across Middle-earth", scenarioEmoji: "🗡️", progressLabel: "Quest", threatLabel: "Shadow", moraleLabel: "Heroes" },
    intro: "Take heroes from the Shire to Mordor.",
    tactics: [T("quest","Quest","🌟",5,0.75,2,"Quest."), T("attack","Attack","🗡️",5,0.7,1,"Battle."), T("ally","Ally","🤝",3,0.95,0,"Recruit."), T("heal","Heal","💖",2,1.0,1,"Restore.")] },
  { folder: "marvel-champions-coop", prefix: "mvc", title: "Marvel Champions", accent: "#dc2626", bg: "#fee2e2",
    description: "Heroes team up against Marvel villains.",
    cfg: { totalRounds: 10, progressTarget: 60, threatPerRound: 3, startMorale: 5, threatBreakpoint: 6, allyEffort: 3, allyClutch: 0.4, scenarioLabel: "Villain Schemes", scenarioEmoji: "🦸", progressLabel: "Damage", threatLabel: "Scheme", moraleLabel: "Hero HP" },
    intro: "Switch hero/alter-ego; thwart villain schemes.",
    tactics: [T("attack","Attack","💥",6,0.7,1,"Big damage."), T("thwart","Thwart","🛡️",4,0.85,2,"Reduce scheme."), T("recover","Recover","💖",3,1.0,1,"Heal."), T("setup","Set Up","🃏",2,1.0,1,"Resources.")] },
  { folder: "marvel-champions-hero", prefix: "mvh", title: "Marvel Champions: Hero", accent: "#b91c1c", bg: "#fef2f2",
    description: "Solo hero focus deck-building variant.",
    cfg: { totalRounds: 10, progressTarget: 65, threatPerRound: 3, startMorale: 5, threatBreakpoint: 6, allyEffort: 3, allyClutch: 0.4, scenarioLabel: "Solo Hero Mission", scenarioEmoji: "💢", progressLabel: "Damage", threatLabel: "Scheme", moraleLabel: "HP" },
    intro: "Solo hero loadout vs. villain.",
    tactics: [T("attack","Attack","💥",6,0.7,1,"Damage."), T("thwart","Thwart","🛡️",4,0.85,2,"Scheme."), T("recover","Recover","💖",3,1.0,1,"Heal."), T("ready","Ready","♻️",2,1.0,1,"Untap.")] },

  // HOGWARTS
  { folder: "hogwarts-battle-coop", prefix: "hwb", title: "Harry Potter: Hogwarts Battle", accent: "#92400e", bg: "#fef3c7",
    description: "Defend Hogwarts from villain takeovers.",
    cfg: { totalRounds: 10, progressTarget: 55, threatPerRound: 3, startMorale: 5, threatBreakpoint: 5, allyEffort: 3, allyClutch: 0.4, scenarioLabel: "Years 1–7", scenarioEmoji: "⚡", progressLabel: "Villains Defeated", threatLabel: "Dark Arts", moraleLabel: "Locations" },
    intro: "Buy spells; KO villains.",
    tactics: [T("attack","Attack Villain","💥",5,0.75,1,"Damage villain."), T("acquire","Acquire Spell","🪄",4,0.85,0,"Buy spell."), T("influence","Influence","🪙",3,0.9,0,"Money."), T("heal","Heal","💖",2,1.0,1,"Restore.")] },
  { folder: "hp-defence-dark-arts", prefix: "hpdda", title: "HP: Defence Against the Dark Arts", accent: "#581c87", bg: "#f3e8ff",
    description: "DADA-themed Hogwarts Battle variant.",
    cfg: { totalRounds: 10, progressTarget: 55, threatPerRound: 3, startMorale: 5, threatBreakpoint: 5, allyEffort: 3, allyClutch: 0.4, scenarioLabel: "DADA Practical Exam", scenarioEmoji: "🧙", progressLabel: "Defences", threatLabel: "Curses", moraleLabel: "Health" },
    intro: "Master defensive spells.",
    tactics: [T("expelliarmus","Expelliarmus","🪄",5,0.8,1,"Disarm."), T("patronus","Patronus","🦌",6,0.6,2,"Big push."), T("study","Study","📖",3,0.9,0,"Card."), T("shield","Shield","🛡️",2,1.0,1,"Block.")] },
  { folder: "hogwarts-villain-coop", prefix: "hwv", title: "Hogwarts Battle: Villains", accent: "#7f1d1d", bg: "#fee2e2",
    description: "Villain-only deck Hogwarts Battle variant.",
    cfg: { totalRounds: 10, progressTarget: 60, threatPerRound: 3, startMorale: 5, threatBreakpoint: 5, allyEffort: 3, allyClutch: 0.4, scenarioLabel: "Death Eater Onslaught", scenarioEmoji: "🐍", progressLabel: "Villains Down", threatLabel: "Marks", moraleLabel: "Stamina" },
    intro: "Tougher villains, brutal fights.",
    tactics: [T("attack","Attack","💥",5,0.75,1,"Damage."), T("buy","Buy Card","🪙",4,0.85,0,"Purchase."), T("influence","Influence","🪙",3,0.9,0,"Money."), T("heal","Heal","💖",2,1.0,1,"Restore.")] },

  // SENTINELS
  { folder: "sentinels-multiverse-coop", prefix: "smc", title: "Sentinels of the Multiverse", accent: "#1d4ed8", bg: "#dbeafe",
    description: "Comic-book heroes defeat villains in the Multiverse.",
    cfg: { totalRounds: 12, progressTarget: 75, threatPerRound: 3, startMorale: 4, threatBreakpoint: 6, allyEffort: 3, allyClutch: 0.35, scenarioLabel: "Villain Plot", scenarioEmoji: "💥", progressLabel: "Villain HP", threatLabel: "Plot", moraleLabel: "Heroes" },
    intro: "Each hero has unique deck and powers.",
    tactics: [T("power","Use Power","⚡",5,0.8,1,"Hero power."), T("play","Play Card","🃏",6,0.6,0,"Big effect."), T("draw","Draw","📖",3,0.95,0,"Card."), T("guard","Guard","🛡️",2,1.0,1,"Defend.")] },
  { folder: "sentinels-definitive", prefix: "smdef", title: "Sentinels: Definitive Edition", accent: "#1e40af", bg: "#dbeafe",
    description: "Definitive Edition revamp of Sentinels.",
    cfg: { totalRounds: 12, progressTarget: 80, threatPerRound: 3, startMorale: 4, threatBreakpoint: 6, allyEffort: 3, allyClutch: 0.35, scenarioLabel: "Definitive Story", scenarioEmoji: "🦸", progressLabel: "Villain HP", threatLabel: "Plot", moraleLabel: "Heroes" },
    intro: "Streamlined hero decks.",
    tactics: [T("power","Power","⚡",5,0.8,1,"Hero power."), T("play","Play","🃏",6,0.6,0,"Card."), T("draw","Draw","📖",3,0.95,0,"Card."), T("guard","Guard","🛡️",2,1.0,1,"Defend.")] },
  { folder: "sentinels-environment", prefix: "smenv", title: "Sentinels: Environment Mode", accent: "#0891b2", bg: "#cffafe",
    description: "Environment-focused Sentinels variant.",
    cfg: { totalRounds: 12, progressTarget: 75, threatPerRound: 4, startMorale: 4, threatBreakpoint: 6, allyEffort: 3, allyClutch: 0.35, scenarioLabel: "Hostile Environment", scenarioEmoji: "🌀", progressLabel: "Villain HP", threatLabel: "Hazards", moraleLabel: "Heroes" },
    intro: "Environment threatens both sides.",
    tactics: [T("power","Power","⚡",5,0.8,1,"Hero power."), T("env","Use Environment","🌪️",4,0.85,1,"Environmental."), T("play","Play","🃏",6,0.6,0,"Card."), T("guard","Guard","🛡️",2,1.0,1,"Defend.")] },

  // MAGIC MAZE
  { folder: "magic-maze-coop", prefix: "mmc", title: "Magic Maze", accent: "#f59e0b", bg: "#fef3c7",
    description: "Silent cooperative dungeon shopping spree.",
    cfg: { totalRounds: 10, progressTarget: 50, threatPerRound: 4, startMorale: 3, threatBreakpoint: 5, allyEffort: 3, allyClutch: 0.4, scenarioLabel: "Mall Heist", scenarioEmoji: "🛍️", progressLabel: "Items Stolen", threatLabel: "Sand Timer", moraleLabel: "Reset" },
    intro: "Each player controls a direction; reach all four exits.",
    tactics: [T("move","Move","➡️",5,0.85,1,"Walk a direction."), T("explore","Explore","🗺️",4,0.85,0,"Reveal tile."), T("vortex","Vortex","🌀",3,0.9,1,"Teleport."), T("flip","Flip Timer","⏳",2,1.0,2,"Reset.")] },
  { folder: "magic-maze-pawn", prefix: "mmp", title: "Magic Maze: Pawn Mode", accent: "#d97706", bg: "#fef3c7",
    description: "Variant with movement restrictions.",
    cfg: { totalRounds: 10, progressTarget: 50, threatPerRound: 4, startMorale: 3, threatBreakpoint: 5, allyEffort: 3, allyClutch: 0.4, scenarioLabel: "Pawn Mode", scenarioEmoji: "♟️", progressLabel: "Items", threatLabel: "Sand", moraleLabel: "Resets" },
    intro: "Each pawn obeys one direction.",
    tactics: [T("move","Move","➡️",5,0.85,1,"Move."), T("explore","Explore","🗺️",4,0.85,0,"Tile."), T("escalator","Escalator","🛗",3,0.9,1,"Speed up."), T("flip","Flip","⏳",2,1.0,2,"Reset.")] },
  { folder: "magic-maze-max-security", prefix: "mmms", title: "Magic Maze: Max Security", accent: "#ea580c", bg: "#fed7aa",
    description: "Hardest Magic Maze: cameras everywhere.",
    cfg: { totalRounds: 9, progressTarget: 50, threatPerRound: 5, startMorale: 3, threatBreakpoint: 5, allyEffort: 3, allyClutch: 0.35, scenarioLabel: "Max Security", scenarioEmoji: "📹", progressLabel: "Items", threatLabel: "Cameras", moraleLabel: "Resets" },
    intro: "Cameras eat time aggressively.",
    tactics: [T("move","Move","➡️",5,0.85,1,"Move."), T("disable","Disable Camera","📵",4,0.75,2,"Stop camera."), T("vortex","Vortex","🌀",3,0.9,1,"Teleport."), T("flip","Flip","⏳",2,1.0,2,"Reset.")] },

  // FLASHPOINT
  { folder: "flashpoint-rescue-coop", prefix: "fpr", title: "Flash Point: Fire Rescue", accent: "#dc2626", bg: "#fee2e2",
    description: "Firefighters rescue victims from a burning house.",
    cfg: { totalRounds: 12, progressTarget: 60, threatPerRound: 3, startMorale: 4, threatBreakpoint: 5, allyEffort: 3, allyClutch: 0.4, scenarioLabel: "Burning Building", scenarioEmoji: "🚒", progressLabel: "Rescued", threatLabel: "Fire", moraleLabel: "Damage" },
    intro: "Drop fire, drag people to safety.",
    tactics: [T("hose","Spray Hose","💦",4,0.9,2,"Reduce fire."), T("rescue","Rescue","🆘",6,0.6,0,"Carry victim."), T("chop","Chop Wall","🪓",3,0.85,1,"Open path."), T("drive","Drive Truck","🚒",2,1.0,2,"Big push.")] },
  { folder: "flashpoint-victims", prefix: "fpv", title: "Flash Point: Victims", accent: "#b91c1c", bg: "#fef2f2",
    description: "Victim-rescue intensive scenario.",
    cfg: { totalRounds: 12, progressTarget: 70, threatPerRound: 4, startMorale: 4, threatBreakpoint: 5, allyEffort: 3, allyClutch: 0.4, scenarioLabel: "Many Trapped", scenarioEmoji: "🆘", progressLabel: "Saved", threatLabel: "Fire", moraleLabel: "Damage" },
    intro: "Many victims, one truck.",
    tactics: [T("rescue","Rescue","🆘",6,0.6,0,"Carry."), T("hose","Hose","💦",4,0.9,2,"Fight fire."), T("medic","Medic","💊",3,0.9,1,"Heal."), T("chop","Chop","🪓",2,1.0,1,"Open.")] },

  // CREW
  { folder: "crew-deep-sea-coop", prefix: "crwd", title: "The Crew: Deep Sea", accent: "#0e7490", bg: "#cffafe",
    description: "Trick-taking quest under the ocean.",
    cfg: { totalRounds: 10, progressTarget: 55, threatPerRound: 3, startMorale: 3, threatBreakpoint: 6, allyEffort: 3, allyClutch: 0.4, scenarioLabel: "Atlantis Mission", scenarioEmoji: "🐙", progressLabel: "Tasks Done", threatLabel: "Mistakes", moraleLabel: "Air" },
    intro: "Win specific tricks in specific order.",
    tactics: [T("lead","Lead Trick","🎴",5,0.8,1,"Win trick."), T("dump","Dump Trick","💧",3,0.95,1,"Lose trick."), T("signal","Signal","📡",4,0.7,1,"Hint."), T("plan","Plan","🗒️",2,1.0,1,"Reorder.")] },
  { folder: "crew-quest-planet-9", prefix: "crwq", title: "The Crew: Planet Nine", accent: "#1e40af", bg: "#dbeafe",
    description: "Trick-taking quest to find Planet 9.",
    cfg: { totalRounds: 10, progressTarget: 50, threatPerRound: 3, startMorale: 3, threatBreakpoint: 6, allyEffort: 3, allyClutch: 0.4, scenarioLabel: "Mission to Planet Nine", scenarioEmoji: "🪐", progressLabel: "Tasks", threatLabel: "Errors", moraleLabel: "O₂" },
    intro: "Coordinate trick-taking with no chat.",
    tactics: [T("lead","Lead","🎴",5,0.8,1,"Win."), T("dump","Dump","💧",3,0.95,1,"Lose."), T("signal","Signal","📡",4,0.7,1,"Hint."), T("plan","Plan","🗒️",2,1.0,1,"Reorder.")] },
  { folder: "crew-distress-signal", prefix: "crws", title: "The Crew: Distress Signal", accent: "#0891b2", bg: "#cffafe",
    description: "Distress-signal variant for The Crew.",
    cfg: { totalRounds: 10, progressTarget: 55, threatPerRound: 4, startMorale: 3, threatBreakpoint: 6, allyEffort: 3, allyClutch: 0.4, scenarioLabel: "SOS", scenarioEmoji: "📡", progressLabel: "Tasks", threatLabel: "Static", moraleLabel: "Battery" },
    intro: "Distress tokens add pressure.",
    tactics: [T("lead","Lead","🎴",5,0.8,1,"Win."), T("dump","Dump","💧",3,0.95,1,"Lose."), T("distress","Distress","🚨",4,0.7,1,"Signal."), T("plan","Plan","🗒️",2,1.0,1,"Reorder.")] },

  // DEAD OF WINTER / ELDRITCH / VAST / ESCAPE
  { folder: "dead-of-winter-survival", prefix: "dowS", title: "Dead of Winter: Survival", accent: "#0f172a", bg: "#e2e8f0",
    description: "Colonists survive zombie winter, secret betrayer possible.",
    cfg: { totalRounds: 12, progressTarget: 70, threatPerRound: 4, startMorale: 4, threatBreakpoint: 6, allyEffort: 3, allyClutch: 0.3, scenarioLabel: "Crossroads Winter", scenarioEmoji: "🧟", progressLabel: "Crisis Avoided", threatLabel: "Zombies", moraleLabel: "Morale" },
    intro: "Find food, fight zombies, manage paranoia.",
    tactics: [T("scout","Scout","🔭",4,0.85,1,"Find resources."), T("attack","Attack","🪓",5,0.7,2,"Kill zombies."), T("medic","Medic","💊",3,0.9,1,"Heal."), T("stash","Stash","📦",2,1.0,1,"Hoard food.")] },
  { folder: "eldritch-investigator", prefix: "ehi", title: "Eldritch Horror: Investigator", accent: "#581c87", bg: "#f3e8ff",
    description: "Globe-trotting Lovecraftian investigators.",
    cfg: { totalRounds: 12, progressTarget: 70, threatPerRound: 4, startMorale: 4, threatBreakpoint: 6, allyEffort: 3, allyClutch: 0.35, scenarioLabel: "Ancient One Awakens", scenarioEmoji: "🐙", progressLabel: "Mysteries", threatLabel: "Doom", moraleLabel: "Sanity" },
    intro: "Solve mysteries before the Ancient One wakes.",
    tactics: [T("travel","Travel","🚂",4,0.85,1,"Cross globe."), T("research","Research","📜",6,0.55,0,"Solve."), T("combat","Combat","🔫",5,0.65,2,"Battle."), T("rest","Rest","🛌",2,1.0,1,"Heal sanity.")] },
  { folder: "escape-aliens-hidden", prefix: "ehsa", title: "Escape: Curse of the Aliens", accent: "#16a34a", bg: "#dcfce7",
    description: "Hidden-movement coop on a doomed ship.",
    cfg: { totalRounds: 10, progressTarget: 55, threatPerRound: 4, startMorale: 4, threatBreakpoint: 5, allyEffort: 3, allyClutch: 0.35, scenarioLabel: "Ship Evacuation", scenarioEmoji: "👽", progressLabel: "Distance", threatLabel: "Aliens", moraleLabel: "HP" },
    intro: "Move silently; reach an escape pod.",
    tactics: [T("sneak","Sneak","🤫",4,0.9,1,"Quiet move."), T("dash","Dash","🏃",5,0.7,1,"Loud but fast."), T("scan","Scan","📡",3,0.9,1,"Locate alien."), T("trap","Set Trap","🪤",2,1.0,2,"Slow alien.")] },
  { folder: "vast-mysterious-coop", prefix: "vstm", title: "Vast: Mysterious Manor", accent: "#7c3aed", bg: "#ede9fe",
    description: "Asymmetric coop variant of Vast.",
    cfg: { totalRounds: 12, progressTarget: 70, threatPerRound: 3, startMorale: 4, threatBreakpoint: 6, allyEffort: 3, allyClutch: 0.35, scenarioLabel: "Mysterious Manor", scenarioEmoji: "🏚️", progressLabel: "Rooms Cleared", threatLabel: "Spirits", moraleLabel: "Sanity" },
    intro: "Each role plays differently — coop variant unifies them.",
    tactics: [T("explore","Explore","🗺️",5,0.75,1,"New room."), T("fight","Fight","⚔️",5,0.7,1,"Spirit."), T("ritual","Ritual","🕯️",6,0.55,0,"Cleanse."), T("rest","Rest","🛌",2,1.0,1,"Heal.")] },

  // BURGLE / LETTER JAM / SPACE ALERT / ROBINSON
  { folder: "burgle-bros-heist", prefix: "bbh", title: "Burgle Bros", accent: "#374151", bg: "#e5e7eb",
    description: "Three-floor heist coop.",
    cfg: { totalRounds: 10, progressTarget: 50, threatPerRound: 3, startMorale: 3, threatBreakpoint: 5, allyEffort: 3, allyClutch: 0.4, scenarioLabel: "Three-Floor Vault", scenarioEmoji: "💼", progressLabel: "Loot", threatLabel: "Guards", moraleLabel: "Stealth" },
    intro: "Crack safes; avoid alarms.",
    tactics: [T("crack","Crack Safe","🔓",6,0.55,0,"Open vault."), T("sneak","Sneak","🤫",4,0.9,1,"Move quiet."), T("hack","Hack Camera","💻",3,0.85,2,"Disable."), T("hide","Hide","🪟",2,1.0,1,"Avoid.")] },
  { folder: "burgle-bros-multi", prefix: "bbm", title: "Burgle Bros: Multi-Heist", accent: "#1f2937", bg: "#e5e7eb",
    description: "Linked-heist Burgle Bros campaign.",
    cfg: { totalRounds: 12, progressTarget: 60, threatPerRound: 3, startMorale: 3, threatBreakpoint: 5, allyEffort: 3, allyClutch: 0.4, scenarioLabel: "Heist Trilogy", scenarioEmoji: "💎", progressLabel: "Loot", threatLabel: "Guards", moraleLabel: "Stealth" },
    intro: "Three vaults; persistent crew.",
    tactics: [T("crack","Crack","🔓",6,0.55,0,"Vault."), T("sneak","Sneak","🤫",4,0.9,1,"Move."), T("hack","Hack","💻",3,0.85,2,"Disable."), T("hide","Hide","🪟",2,1.0,1,"Avoid.")] },
  { folder: "letter-jam-coop", prefix: "ltj", title: "Letter Jam", accent: "#a16207", bg: "#fef3c7",
    description: "Word-clue cooperative deduction.",
    cfg: { totalRounds: 10, progressTarget: 50, threatPerRound: 2, startMorale: 4, threatBreakpoint: 6, allyEffort: 3, allyClutch: 0.4, scenarioLabel: "Word Puzzle", scenarioEmoji: "🔤", progressLabel: "Letters Deduced", threatLabel: "Tokens Used", moraleLabel: "Hints" },
    intro: "Form words; clue your teammate.",
    tactics: [T("clue","Give Clue","💡",5,0.8,0,"Word clue."), T("guess","Guess Letter","🔡",6,0.6,0,"Try letter."), T("hint","Use Hint","🎯",3,0.9,1,"Spend token."), T("plan","Plan","🗒️",2,1.0,1,"Reorder.")] },
  { folder: "space-alert-coop", prefix: "spa", title: "Space Alert", accent: "#0891b2", bg: "#cffafe",
    description: "Real-time spaceship coop.",
    cfg: { totalRounds: 10, progressTarget: 55, threatPerRound: 4, startMorale: 4, threatBreakpoint: 5, allyEffort: 3, allyClutch: 0.35, scenarioLabel: "Mission T+10:00", scenarioEmoji: "🛰️", progressLabel: "Threats Cleared", threatLabel: "Damage", moraleLabel: "Hull" },
    intro: "Plan a 10-minute mission against waves.",
    tactics: [T("fire","Fire Cannon","🔫",5,0.8,1,"Damage."), T("shield","Shield","🛡️",3,0.95,1,"Protect."), T("repair","Repair","🔧",4,0.85,2,"Fix hull."), T("move","Move","➡️",2,1.0,0,"Crew shift.")] },
  { folder: "robinson-crusoe-coop", prefix: "rcc", title: "Robinson Crusoe", accent: "#16a34a", bg: "#dcfce7",
    description: "Stranded survivors build, hunt and explore.",
    cfg: { totalRounds: 12, progressTarget: 70, threatPerRound: 4, startMorale: 4, threatBreakpoint: 6, allyEffort: 3, allyClutch: 0.35, scenarioLabel: "Castaway Island", scenarioEmoji: "🏝️", progressLabel: "Goals", threatLabel: "Storm", moraleLabel: "Health" },
    intro: "Build shelter; survive weather.",
    tactics: [T("build","Build","🪵",5,0.8,1,"Construct."), T("hunt","Hunt","🏹",6,0.6,0,"Food."), T("explore","Explore","🧭",4,0.85,0,"Reveal."), T("rest","Rest","🛌",2,1.0,1,"Heal.")] },
  { folder: "robinson-island", prefix: "rci", title: "Robinson: Island", accent: "#15803d", bg: "#dcfce7",
    description: "Robinson Crusoe scenario pack.",
    cfg: { totalRounds: 12, progressTarget: 70, threatPerRound: 4, startMorale: 4, threatBreakpoint: 6, allyEffort: 3, allyClutch: 0.35, scenarioLabel: "Volcano Island", scenarioEmoji: "🌋", progressLabel: "Goals", threatLabel: "Lava", moraleLabel: "Health" },
    intro: "Survive volcanic threats.",
    tactics: [T("build","Build","🪵",5,0.8,1,"Construct."), T("hunt","Hunt","🏹",6,0.6,0,"Food."), T("explore","Explore","🧭",4,0.85,0,"Reveal."), T("rest","Rest","🛌",2,1.0,1,"Heal.")] },

  // THE MIND / HANABI variants (Hanabi base is overhauled separately)
  { folder: "the-mind-coop", prefix: "tmd", title: "The Mind", accent: "#7c3aed", bg: "#ede9fe",
    description: "Wordless number-sequencing telepathy.",
    cfg: { totalRounds: 10, progressTarget: 55, threatPerRound: 3, startMorale: 3, threatBreakpoint: 5, allyEffort: 3, allyClutch: 0.5, scenarioLabel: "Hive Mind", scenarioEmoji: "🧠", progressLabel: "Cards Played", threatLabel: "Mistakes", moraleLabel: "Lives" },
    intro: "Play cards in ascending order without speaking.",
    tactics: [T("focus","Focus","🧘",5,0.85,1,"Sense timing."), T("play","Play Card","🃏",6,0.6,0,"Risk play."), T("wait","Wait","⏳",3,0.95,1,"Pause."), T("sync","Sync","🔁",2,1.0,1,"Align.")] },
  { folder: "hanabi-avenue-bonus", prefix: "hbab", title: "Hanabi: Avenue Bonus", accent: "#db2777", bg: "#fce7f3",
    description: "Bonus-rule Hanabi variant.",
    cfg: { totalRounds: 10, progressTarget: 50, threatPerRound: 3, startMorale: 3, threatBreakpoint: 5, allyEffort: 3, allyClutch: 0.4, scenarioLabel: "Bonus Round", scenarioEmoji: "🎆", progressLabel: "Fireworks", threatLabel: "Fuse", moraleLabel: "Lives" },
    intro: "Hanabi with bonus tokens for clean plays.",
    tactics: [T("play","Play","🎆",6,0.6,1,"Light firework."), T("hint","Hint","💡",4,0.9,0,"Give hint."), T("discard","Discard","🗑️",3,0.95,0,"Recover token."), T("bonus","Bonus","⭐",2,1.0,1,"Combo.")] },
  { folder: "hanabi-extra-coop", prefix: "hbex", title: "Hanabi: Extra", accent: "#ec4899", bg: "#fce7f3",
    description: "Hanabi with extra suits.",
    cfg: { totalRounds: 10, progressTarget: 60, threatPerRound: 3, startMorale: 3, threatBreakpoint: 5, allyEffort: 3, allyClutch: 0.4, scenarioLabel: "Extra Suit", scenarioEmoji: "🎇", progressLabel: "Fireworks", threatLabel: "Fuse", moraleLabel: "Lives" },
    intro: "Add a sixth suit for harder play.",
    tactics: [T("play","Play","🎆",6,0.6,1,"Firework."), T("hint","Hint","💡",4,0.9,0,"Hint."), T("discard","Discard","🗑️",3,0.95,0,"Token."), T("extra","Extra Suit","🌈",2,1.0,1,"Bonus suit.")] },

  // CLANK / DOMINION / MAGE / THUNDER / LEGENDARY / TASH / SORCERER / KEYFORGE / SUMMONER / BATTLECON / ONE DECK / TANTO / DUNGEON / FOUR SOULS / UNDAUNTED / GRIZZLED / APOTHECARIA
  { folder: "clank-in-space", prefix: "cks", title: "Clank! In! Space!", accent: "#0e7490", bg: "#cffafe",
    description: "Deckbuilding heist on a space station.",
    cfg: { totalRounds: 11, progressTarget: 65, threatPerRound: 3, startMorale: 4, threatBreakpoint: 6, allyEffort: 3, allyClutch: 0.4, scenarioLabel: "Lord Eradikus' Ship", scenarioEmoji: "🚀", progressLabel: "Loot", threatLabel: "Clank", moraleLabel: "Health" },
    intro: "Deckbuild while sneaking through Lord Eradikus' ship.",
    tactics: [T("acquire","Acquire Card","🛒",5,0.8,1,"Buy upgrade."), T("attack","Attack","⚔️",4,0.85,0,"Fight."), T("loot","Loot","💎",6,0.55,0,"Grab artifact."), T("hide","Hide","🌫️",2,1.0,2,"Reduce clank.")] },
  { folder: "dominion-intrigue", prefix: "dmi", title: "Dominion: Intrigue", accent: "#9d174d", bg: "#fce7f3",
    description: "Court-intrigue Dominion expansion.",
    cfg: { totalRounds: 12, progressTarget: 60, threatPerRound: 3, startMorale: 4, threatBreakpoint: 6, allyEffort: 3, allyClutch: 0.4, scenarioLabel: "The Royal Court", scenarioEmoji: "👑", progressLabel: "VP", threatLabel: "Empty Piles", moraleLabel: "Hand Size" },
    intro: "Buy victory; AI race against you.",
    tactics: [T("buyaction","Buy Action","🃏",5,0.8,0,"+ engine."), T("buygold","Buy Gold","🪙",4,0.9,0,"+ money."), T("buyvp","Buy VP","👑",6,0.55,1,"+ score."), T("attack","Attack","⚔️",3,0.85,1,"Slow opponent.")] },
  { folder: "dominion-seaside", prefix: "dms", title: "Dominion: Seaside", accent: "#0e7490", bg: "#cffafe",
    description: "Duration-card Dominion expansion.",
    cfg: { totalRounds: 12, progressTarget: 65, threatPerRound: 3, startMorale: 4, threatBreakpoint: 6, allyEffort: 3, allyClutch: 0.4, scenarioLabel: "High Seas", scenarioEmoji: "⛵", progressLabel: "VP", threatLabel: "Empty Piles", moraleLabel: "Hand" },
    intro: "Duration cards stay around for next turn.",
    tactics: [T("dur","Buy Duration","🌊",5,0.8,0,"Lasting."), T("buygold","Buy Gold","🪙",4,0.9,0,"+ money."), T("buyvp","Buy VP","👑",6,0.55,1,"+ score."), T("attack","Attack","⚓",3,0.85,1,"Slow.")] },
  { folder: "dominion-prosperity", prefix: "dmp", title: "Dominion: Prosperity", accent: "#a16207", bg: "#fef3c7",
    description: "Big-money Dominion expansion.",
    cfg: { totalRounds: 12, progressTarget: 75, threatPerRound: 3, startMorale: 4, threatBreakpoint: 6, allyEffort: 3, allyClutch: 0.4, scenarioLabel: "Boom Era", scenarioEmoji: "💰", progressLabel: "VP", threatLabel: "Empty Piles", moraleLabel: "Hand" },
    intro: "Platinum + Colony big-money game.",
    tactics: [T("plat","Buy Platinum","💎",6,0.55,0,"Huge money."), T("buygold","Buy Gold","🪙",4,0.9,0,"+money."), T("buycolony","Colony","🏰",6,0.5,1,"Huge VP."), T("draw","Draw","🃏",3,0.95,0,"Cycle.")] },
  { folder: "dominion-adventures", prefix: "dma", title: "Dominion: Adventures", accent: "#7c2d12", bg: "#fed7aa",
    description: "Token-based Dominion expansion.",
    cfg: { totalRounds: 12, progressTarget: 65, threatPerRound: 3, startMorale: 4, threatBreakpoint: 6, allyEffort: 3, allyClutch: 0.4, scenarioLabel: "Quest Tokens", scenarioEmoji: "🗺️", progressLabel: "VP", threatLabel: "Empty Piles", moraleLabel: "Hand" },
    intro: "Reserve cards & tokens.",
    tactics: [T("reserve","Reserve","🏦",5,0.8,0,"Set aside."), T("buygold","Gold","🪙",4,0.9,0,"+money."), T("buyvp","VP","👑",6,0.55,1,"+score."), T("token","Token","🎟️",3,0.9,1,"Special.")] },
  { folder: "mage-knight-card", prefix: "mkc", title: "Mage Knight Card", accent: "#1e3a8a", bg: "#dbeafe",
    description: "Tactical adventure deck-builder.",
    cfg: { totalRounds: 12, progressTarget: 75, threatPerRound: 4, startMorale: 4, threatBreakpoint: 6, allyEffort: 3, allyClutch: 0.35, scenarioLabel: "Knight's Quest", scenarioEmoji: "🛡️", progressLabel: "Conquest", threatLabel: "Mana Drain", moraleLabel: "Health" },
    intro: "Plan multi-step combos.",
    tactics: [T("attack","Attack","⚔️",6,0.65,1,"Damage."), T("move","Move","🐎",4,0.85,1,"Travel."), T("recruit","Recruit","🤝",3,0.9,0,"Unit."), T("rest","Rest","🌙",2,1.0,1,"Heal.")] },
  { folder: "thunderstone-quest", prefix: "tqs", title: "Thunderstone Quest", accent: "#b45309", bg: "#fef3c7",
    description: "Dungeon-delving deck-builder.",
    cfg: { totalRounds: 11, progressTarget: 70, threatPerRound: 3, startMorale: 4, threatBreakpoint: 6, allyEffort: 3, allyClutch: 0.4, scenarioLabel: "Dungeon Delve", scenarioEmoji: "🐉", progressLabel: "XP", threatLabel: "Dungeon", moraleLabel: "Hero HP" },
    intro: "Buy heroes/items, raid the dungeon.",
    tactics: [T("buy","Buy Card","🛒",5,0.8,0,"Upgrade."), T("dungeon","Raid","🗡️",6,0.6,1,"Fight monster."), T("village","Village","🏘️",3,0.95,0,"Income."), T("rest","Rest","🛌",2,1.0,1,"Heal.")] },
  { folder: "legendary-marvel", prefix: "lgm", title: "Legendary: Marvel", accent: "#dc2626", bg: "#fee2e2",
    description: "Marvel deck-builder coop.",
    cfg: { totalRounds: 10, progressTarget: 65, threatPerRound: 4, startMorale: 4, threatBreakpoint: 6, allyEffort: 3, allyClutch: 0.4, scenarioLabel: "Mastermind Plot", scenarioEmoji: "🦸", progressLabel: "Damage", threatLabel: "Scheme Twist", moraleLabel: "City" },
    intro: "Recruit heroes; defeat villains and Mastermind.",
    tactics: [T("recruit","Recruit","🤝",4,0.85,0,"Hero."), T("attack","Attack","💥",6,0.6,1,"Villain."), T("master","Hit Mastermind","🎯",6,0.5,2,"Major progress."), T("heal","Heal","💖",2,1.0,1,"City.")] },
  { folder: "tash-kalar-arena", prefix: "tka", title: "Tash-Kalar: Arena", accent: "#581c87", bg: "#f3e8ff",
    description: "Pattern-summoning duel — coop variant.",
    cfg: { totalRounds: 10, progressTarget: 55, threatPerRound: 3, startMorale: 4, threatBreakpoint: 6, allyEffort: 3, allyClutch: 0.4, scenarioLabel: "Mage Arena", scenarioEmoji: "🔯", progressLabel: "Patterns", threatLabel: "Mana Drain", moraleLabel: "Health" },
    intro: "Place stones in patterns; summon beings.",
    tactics: [T("summon","Summon","🐉",6,0.55,1,"Big creature."), T("place","Place Stone","🟦",4,0.9,0,"Foundation."), T("flare","Flare","🔥",3,0.85,1,"Bonus."), T("focus","Focus","🎯",2,1.0,1,"Special.")] },
  { folder: "sorcerer-city-build", prefix: "scb", title: "Sorcerer City", accent: "#7c3aed", bg: "#ede9fe",
    description: "Tile-laying city builder.",
    cfg: { totalRounds: 10, progressTarget: 60, threatPerRound: 3, startMorale: 4, threatBreakpoint: 6, allyEffort: 3, allyClutch: 0.4, scenarioLabel: "Sorcerer's Capital", scenarioEmoji: "🏰", progressLabel: "Districts", threatLabel: "Monsters", moraleLabel: "Walls" },
    intro: "Real-time tile placement.",
    tactics: [T("build","Build","🏗️",5,0.8,1,"Tile."), T("magic","Cast Magic","✨",6,0.55,0,"Bonus."), T("guard","Guard","🛡️",3,0.95,1,"Defend."), T("trade","Trade","💰",2,1.0,1,"Income.")] },
  { folder: "keyforge-archons", prefix: "kfa", title: "KeyForge: Archons", accent: "#92400e", bg: "#fef3c7",
    description: "Unique-deck card duel — coop variant.",
    cfg: { totalRounds: 10, progressTarget: 60, threatPerRound: 3, startMorale: 4, threatBreakpoint: 6, allyEffort: 3, allyClutch: 0.35, scenarioLabel: "Archon Forge", scenarioEmoji: "🗝️", progressLabel: "Aember", threatLabel: "Opponent Aember", moraleLabel: "Keys" },
    intro: "Forge three keys before the AI Archon.",
    tactics: [T("reap","Reap","🌾",4,0.9,0,"+aember."), T("fight","Fight","⚔️",5,0.7,1,"Remove enemy."), T("forge","Forge Key","🗝️",6,0.5,2,"Major."), T("draw","Draw","🃏",2,1.0,0,"Card.")] },
  { folder: "summoner-wars-grid", prefix: "swg", title: "Summoner Wars: Grid", accent: "#1f2937", bg: "#e5e7eb",
    description: "Grid combat with summoners.",
    cfg: { totalRounds: 11, progressTarget: 60, threatPerRound: 3, startMorale: 4, threatBreakpoint: 6, allyEffort: 3, allyClutch: 0.4, scenarioLabel: "Battlefield", scenarioEmoji: "♟️", progressLabel: "Summoner Damage", threatLabel: "Enemy Units", moraleLabel: "Magic" },
    intro: "Position units; KO the enemy summoner.",
    tactics: [T("summon","Summon","✨",5,0.8,0,"Bring unit."), T("attack","Attack","⚔️",5,0.7,1,"Damage."), T("move","Maneuver","➡️",3,0.95,0,"Reposition."), T("magic","Recharge","🔋",2,1.0,1,"Magic.")] },
  { folder: "battlecon-indines", prefix: "bcni", title: "BattleCON: Indines", accent: "#b91c1c", bg: "#fee2e2",
    description: "Card-pair fighting game.",
    cfg: { totalRounds: 10, progressTarget: 50, threatPerRound: 3, startMorale: 4, threatBreakpoint: 6, allyEffort: 3, allyClutch: 0.4, scenarioLabel: "Indines Tournament", scenarioEmoji: "🥊", progressLabel: "Damage", threatLabel: "Counters", moraleLabel: "HP" },
    intro: "Play attack pairs; mind-game opponent.",
    tactics: [T("attack","Attack","🥊",5,0.7,1,"Strike."), T("dodge","Dodge","💫",3,0.95,1,"Avoid."), T("special","Special","⚡",6,0.55,0,"Burst."), T("block","Block","🛡️",2,1.0,1,"Defend.")] },
  { folder: "one-deck-galaxy", prefix: "odg", title: "One Deck Galaxy", accent: "#7c3aed", bg: "#ede9fe",
    description: "Pocket 4X with one deck.",
    cfg: { totalRounds: 10, progressTarget: 55, threatPerRound: 3, startMorale: 4, threatBreakpoint: 6, allyEffort: 3, allyClutch: 0.4, scenarioLabel: "Tiny Galaxy", scenarioEmoji: "🌌", progressLabel: "Glory", threatLabel: "Encroachment", moraleLabel: "Resources" },
    intro: "Tiny but tense space empire.",
    tactics: [T("explore","Explore","🚀",4,0.85,0,"New world."), T("expand","Expand","🪐",5,0.75,1,"Colony."), T("research","Research","🔬",6,0.55,0,"Tech."), T("defend","Defend","🛡️",2,1.0,1,"Border.")] },
  { folder: "tanto-cuore-maids", prefix: "tcm", title: "Tanto Cuore: Maids", accent: "#db2777", bg: "#fce7f3",
    description: "Maid-themed deck-builder.",
    cfg: { totalRounds: 12, progressTarget: 65, threatPerRound: 3, startMorale: 4, threatBreakpoint: 6, allyEffort: 3, allyClutch: 0.4, scenarioLabel: "Manor Service", scenarioEmoji: "🎀", progressLabel: "Love", threatLabel: "Bad Habits", moraleLabel: "Manor Order" },
    intro: "Hire maids; manage the manor.",
    tactics: [T("hire","Hire Maid","👩",5,0.8,0,"Recruit."), T("event","Event","🎉",6,0.55,1,"Big effect."), T("clean","Clean","🧹",3,0.9,2,"Reduce bad habits."), T("rest","Rest","💤",2,1.0,1,"Recover.")] },
  { folder: "dungeon-lords-trap", prefix: "dlt", title: "Dungeon Lords: Trap", accent: "#7f1d1d", bg: "#fee2e2",
    description: "Lay traps; lure heroes to their doom.",
    cfg: { totalRounds: 10, progressTarget: 55, threatPerRound: 3, startMorale: 4, threatBreakpoint: 6, allyEffort: 3, allyClutch: 0.35, scenarioLabel: "Evil Dungeon", scenarioEmoji: "💀", progressLabel: "Heroes Defeated", threatLabel: "Audit", moraleLabel: "Reputation" },
    intro: "Be the dungeon-lord; trap parties of heroes.",
    tactics: [T("trap","Place Trap","🪤",6,0.55,1,"Big damage."), T("hire","Hire Goblin","👹",4,0.85,0,"Minion."), T("dig","Dig Tunnel","⛏️",3,0.9,0,"Expand."), T("rest","Recover","🌙",2,1.0,1,"Reputation.")] },
  { folder: "four-souls-isaac", prefix: "fsi", title: "Four Souls: Isaac", accent: "#dc2626", bg: "#fee2e2",
    description: "Roguelike co-op deck-builder.",
    cfg: { totalRounds: 11, progressTarget: 65, threatPerRound: 3, startMorale: 4, threatBreakpoint: 6, allyEffort: 3, allyClutch: 0.4, scenarioLabel: "Basement Run", scenarioEmoji: "👁️", progressLabel: "Souls", threatLabel: "Curses", moraleLabel: "HP" },
    intro: "Defeat monsters; collect 4 souls.",
    tactics: [T("attack","Attack","⚔️",5,0.7,1,"Fight."), T("loot","Loot","💎",4,0.85,0,"Item."), T("buy","Buy","🪙",3,0.9,0,"Shop."), T("pray","Pray","🙏",2,1.0,1,"Heal.")] },
  { folder: "undaunted-normandy", prefix: "udnn", title: "Undaunted: Normandy", accent: "#15803d", bg: "#dcfce7",
    description: "WWII deckbuilding tactics.",
    cfg: { totalRounds: 10, progressTarget: 60, threatPerRound: 4, startMorale: 4, threatBreakpoint: 6, allyEffort: 3, allyClutch: 0.35, scenarioLabel: "D-Day Beachhead", scenarioEmoji: "🪖", progressLabel: "Objectives", threatLabel: "Enemy Pressure", moraleLabel: "Morale" },
    intro: "Squad-card deck building.",
    tactics: [T("scout","Scout","🔭",4,0.85,1,"Recon."), T("attack","Attack","🔫",5,0.7,1,"Fire."), T("control","Control","🚩",6,0.55,0,"Capture."), T("rally","Rally","📣",2,1.0,1,"Morale.")] },
  { folder: "undaunted-north-africa", prefix: "udna", title: "Undaunted: North Africa", accent: "#a16207", bg: "#fef3c7",
    description: "Desert WWII deck builder.",
    cfg: { totalRounds: 10, progressTarget: 60, threatPerRound: 4, startMorale: 4, threatBreakpoint: 6, allyEffort: 3, allyClutch: 0.35, scenarioLabel: "Desert Campaign", scenarioEmoji: "🏜️", progressLabel: "Objectives", threatLabel: "Enemy", moraleLabel: "Morale" },
    intro: "Tanks + infantry across desert.",
    tactics: [T("scout","Scout","🔭",4,0.85,1,"Recon."), T("attack","Attack","🔫",5,0.7,1,"Fire."), T("control","Control","🚩",6,0.55,0,"Capture."), T("rally","Rally","📣",2,1.0,1,"Morale.")] },
  { folder: "grizzled-coop", prefix: "grz", title: "The Grizzled", accent: "#374151", bg: "#e5e7eb",
    description: "WWI soldiers survive the trenches.",
    cfg: { totalRounds: 11, progressTarget: 60, threatPerRound: 3, startMorale: 4, threatBreakpoint: 6, allyEffort: 3, allyClutch: 0.35, scenarioLabel: "Trench Mission", scenarioEmoji: "🪖", progressLabel: "Missions", threatLabel: "Threats", moraleLabel: "Morale" },
    intro: "Discard threats; survive the war.",
    tactics: [T("play","Play Card","🎴",5,0.8,1,"Front."), T("withdraw","Withdraw","🌙",3,0.95,1,"Retreat."), T("speech","Speech","📣",4,0.75,2,"Morale."), T("share","Share Hardship","🤝",2,1.0,1,"Heal.")] },
  { folder: "grizzled-orders", prefix: "grzo", title: "The Grizzled: Orders", accent: "#1f2937", bg: "#e5e7eb",
    description: "Armistice add-on missions for The Grizzled.",
    cfg: { totalRounds: 11, progressTarget: 65, threatPerRound: 3, startMorale: 4, threatBreakpoint: 6, allyEffort: 3, allyClutch: 0.35, scenarioLabel: "Armistice", scenarioEmoji: "✉️", progressLabel: "Missions", threatLabel: "Orders", moraleLabel: "Morale" },
    intro: "Fulfil orders before peace breaks.",
    tactics: [T("play","Play","🎴",5,0.8,1,"Front."), T("withdraw","Withdraw","🌙",3,0.95,1,"Retreat."), T("speech","Speech","📣",4,0.75,2,"Morale."), T("share","Share","🤝",2,1.0,1,"Heal.")] },
  { folder: "apothecaria-witch", prefix: "apw", title: "Apothecaria: Witch", accent: "#16a34a", bg: "#dcfce7",
    description: "Solo witch-apothecary brewing campaign.",
    cfg: { totalRounds: 12, progressTarget: 70, threatPerRound: 3, startMorale: 4, threatBreakpoint: 6, allyEffort: 3, allyClutch: 0.4, scenarioLabel: "Forest Apothecary", scenarioEmoji: "🌿", progressLabel: "Customers Helped", threatLabel: "Plague", moraleLabel: "Stamina" },
    intro: "Forage, brew, deliver.",
    tactics: [T("forage","Forage","🌱",5,0.8,0,"Herbs."), T("brew","Brew","🧪",6,0.55,1,"Potion."), T("deliver","Deliver","📬",4,0.85,1,"Customer."), T("rest","Rest","🌙",2,1.0,1,"Recover.")] },
  { folder: "apothecaria-seasons", prefix: "aps", title: "Apothecaria: Seasons", accent: "#15803d", bg: "#dcfce7",
    description: "Seasonal scenarios for Apothecaria.",
    cfg: { totalRounds: 12, progressTarget: 75, threatPerRound: 3, startMorale: 4, threatBreakpoint: 6, allyEffort: 3, allyClutch: 0.4, scenarioLabel: "Year of Brewing", scenarioEmoji: "🍂", progressLabel: "Customers", threatLabel: "Frost", moraleLabel: "Stamina" },
    intro: "Each season changes available herbs.",
    tactics: [T("forage","Forage","🌱",5,0.8,0,"Herbs."), T("brew","Brew","🧪",6,0.55,1,"Potion."), T("deliver","Deliver","📬",4,0.85,1,"Customer."), T("rest","Rest","🌙",2,1.0,1,"Recover.")] },
];
