// Deduction-puzzle specs.
const COLORS = ["R","O","Y","G","B","V","P","K"];
const COLORS10 = ["R","O","Y","G","C","B","V","M","P","K"];
const NUM10 = ["1","2","3","4","5","6","7","8","9","0"];
const SHAPES = ["●","■","▲","◆","★","✚","♣","♥"];

export const DEDUCTION_SPECS = [
  { folder: "mastermind", prefix: "mm", title: "Mastermind", accent: "#1d4ed8", bg: "#dbeafe",
    description: "Crack the four-color code in 10 guesses.",
    cfg: { mode: "exact", answerLength: 4, poolSize: 6, allowRepeats: true, maxGuesses: 10, symbolLabels: COLORS.slice(0,6), scenarioLabel: "Code Cracker", scenarioEmoji: "🔓" },
    intro: "Click a slot to cycle colours; submit to read pegs. ● exact · ○ misplaced." },
  { folder: "super-mastermind", prefix: "smm", title: "Super Mastermind", accent: "#1e3a8a", bg: "#dbeafe",
    description: "Five-peg eight-color Mastermind.",
    cfg: { mode: "exact", answerLength: 5, poolSize: 8, allowRepeats: true, maxGuesses: 12, symbolLabels: COLORS, scenarioLabel: "Super Code", scenarioEmoji: "🧠" },
    intro: "Five slots, eight colors. 12 attempts." },
  { folder: "mastermind-5peg-8color", prefix: "mm58", title: "Mastermind 5/8", accent: "#0e7490", bg: "#cffafe",
    description: "5 pegs, 8 colors variant.",
    cfg: { mode: "exact", answerLength: 5, poolSize: 8, allowRepeats: true, maxGuesses: 12, symbolLabels: COLORS, scenarioLabel: "5×8 Code", scenarioEmoji: "🔢" },
    intro: "Standard Mastermind 5/8." },
  { folder: "mastermind-6peg-10color", prefix: "mm610", title: "Mastermind 6/10", accent: "#0891b2", bg: "#cffafe",
    description: "Hardest classic Mastermind.",
    cfg: { mode: "exact", answerLength: 6, poolSize: 10, allowRepeats: true, maxGuesses: 14, symbolLabels: COLORS10, scenarioLabel: "6×10 Code", scenarioEmoji: "🧮" },
    intro: "6 pegs, 10 colors, 14 attempts." },
  { folder: "mastermind-no-repeats", prefix: "mmnr", title: "Mastermind No Repeats", accent: "#1d4ed8", bg: "#dbeafe",
    description: "Mastermind without repeated colours.",
    cfg: { mode: "exact", answerLength: 4, poolSize: 8, allowRepeats: false, maxGuesses: 10, symbolLabels: COLORS, scenarioLabel: "No-Repeat Code", scenarioEmoji: "🚫" },
    intro: "All four pegs are different." },
  { folder: "jotto", prefix: "jot", title: "Jotto", accent: "#a16207", bg: "#fef3c7",
    description: "Five-letter unique-letter word puzzle.",
    cfg: { mode: "exact", answerLength: 5, poolSize: 10, allowRepeats: false, maxGuesses: 12, symbolLabels: ["A","E","I","O","U","R","S","T","L","N"], scenarioLabel: "Letter Hunt", scenarioEmoji: "🔡" },
    intro: "Match each position to a letter." },
  { folder: "black-box-mini", prefix: "bbx", title: "Black Box Mini", accent: "#0f172a", bg: "#e2e8f0",
    description: "Probe the black box to locate hidden atoms.",
    cfg: { mode: "exact", answerLength: 4, poolSize: 8, allowRepeats: false, maxGuesses: 10, symbolLabels: ["A","B","C","D","E","F","G","H"], scenarioLabel: "Black Box", scenarioEmoji: "📦" },
    intro: "Locate hidden atoms by sequence." },
  { folder: "bulls-and-cows", prefix: "bc", title: "Bulls and Cows", accent: "#15803d", bg: "#dcfce7",
    description: "Numeric Mastermind: bulls = exact, cows = misplaced.",
    cfg: { mode: "exact", answerLength: 4, poolSize: 10, allowRepeats: false, maxGuesses: 10, symbolLabels: NUM10, scenarioLabel: "Bulls & Cows", scenarioEmoji: "🐂" },
    intro: "Find the secret 4-digit number." },
  { folder: "sleuth-mini", prefix: "slt", title: "Sleuth Mini", accent: "#7c3aed", bg: "#ede9fe",
    description: "Deduce hidden gem combination.",
    cfg: { mode: "exact", answerLength: 3, poolSize: 8, allowRepeats: false, maxGuesses: 8, symbolLabels: ["💎","💍","🔱","🔮","🗝️","🪙","🎯","🪞"], scenarioLabel: "Stolen Gems", scenarioEmoji: "🔍" },
    intro: "Three gems, eight possibilities." },
  { folder: "code-777-mini", prefix: "c777", title: "Code 777 Mini", accent: "#dc2626", bg: "#fee2e2",
    description: "Logic puzzle: deduce the seven-symbol code.",
    cfg: { mode: "exact", answerLength: 3, poolSize: 7, allowRepeats: true, maxGuesses: 10, symbolLabels: SHAPES.slice(0,7), scenarioLabel: "Code 777", scenarioEmoji: "🎯" },
    intro: "Three slots, seven symbols (repeats allowed)." },
  { folder: "thirteen-clues", prefix: "tcl", title: "13 Clues", accent: "#581c87", bg: "#f3e8ff",
    description: "Solve a murder by deducing the secret card combo.",
    cfg: { mode: "exact", answerLength: 3, poolSize: 6, allowRepeats: false, maxGuesses: 10, symbolLabels: ["💀","🗡️","🪓","🧪","🔫","🪢"], scenarioLabel: "Murder Solved", scenarioEmoji: "🕵️" },
    intro: "Suspect / weapon / location." },
  { folder: "13-clues", prefix: "tc13", title: "Thirteen Clues", accent: "#7e22ce", bg: "#f3e8ff",
    description: "13 Clues alias.",
    cfg: { mode: "exact", answerLength: 3, poolSize: 6, allowRepeats: false, maxGuesses: 10, symbolLabels: ["💀","🗡️","🪓","🧪","🔫","🪢"], scenarioLabel: "Murder Mystery", scenarioEmoji: "🕯️" },
    intro: "Solve the case." },
  { folder: "turing-machine-puzzle", prefix: "trm", title: "Turing Machine", accent: "#374151", bg: "#e5e7eb",
    description: "Three-digit logic deduction.",
    cfg: { mode: "exact", answerLength: 3, poolSize: 5, allowRepeats: true, maxGuesses: 10, symbolLabels: ["1","2","3","4","5"], scenarioLabel: "Turing Test", scenarioEmoji: "🤖" },
    intro: "Verify against silicon checkers." },
  { folder: "decrypto-codes", prefix: "dec", title: "Decrypto Codes", accent: "#16a34a", bg: "#dcfce7",
    description: "Decode the 3-digit secret cipher.",
    cfg: { mode: "exact", answerLength: 3, poolSize: 4, allowRepeats: false, maxGuesses: 8, symbolLabels: ["1","2","3","4"], scenarioLabel: "Cipher Hunt", scenarioEmoji: "📡" },
    intro: "Three digits from {1,2,3,4}, no repeats." },
  { folder: "codenames-pictures", prefix: "cnp", title: "Codenames: Pictures", accent: "#dc2626", bg: "#fee2e2",
    description: "Identify your team's pictures by clue.",
    cfg: { mode: "exact", answerLength: 4, poolSize: 8, allowRepeats: false, maxGuesses: 8, symbolLabels: ["🐶","🐱","🦁","🐧","🦋","🐢","🦊","🐯"], scenarioLabel: "Spymaster's Clue", scenarioEmoji: "🕵️" },
    intro: "Pick the four agents matching your spymaster's clue." },
  { folder: "codenames-xxl", prefix: "cnxl", title: "Codenames XXL", accent: "#b91c1c", bg: "#fee2e2",
    description: "Larger Codenames party puzzle.",
    cfg: { mode: "exact", answerLength: 5, poolSize: 8, allowRepeats: false, maxGuesses: 8, symbolLabels: ["A","B","C","D","E","F","G","H"], scenarioLabel: "Big Spymaster", scenarioEmoji: "🎯" },
    intro: "Five agents from a larger pool." },
  // Concept / Mysterium / Awkward Guests / Lingo / Tempel / Cryptid / Deception
  { folder: "concept-deduction", prefix: "cnd", title: "Concept", accent: "#0891b2", bg: "#cffafe",
    description: "Deduce the concept from icons.",
    cfg: { mode: "exact", answerLength: 3, poolSize: 6, allowRepeats: false, maxGuesses: 9, symbolLabels: ["🎬","📚","🌍","🦁","⚔️","💡"], scenarioLabel: "Concept", scenarioEmoji: "💡" },
    intro: "Three icon hints; deduce three answer keys." },
  { folder: "decrypto-codes-alt", prefix: "deca", title: "Decrypto", accent: "#15803d", bg: "#dcfce7",
    description: "Alternate Decrypto puzzle.",
    cfg: { mode: "exact", answerLength: 3, poolSize: 4, allowRepeats: false, maxGuesses: 8, symbolLabels: ["1","2","3","4"], scenarioLabel: "Decrypto", scenarioEmoji: "📡" },
    intro: "Decode 3 digits from 4." },
  { folder: "mysterium-visions", prefix: "myv", title: "Mysterium Visions", accent: "#581c87", bg: "#f3e8ff",
    description: "Decipher ghost visions to identify the killer.",
    cfg: { mode: "exact", answerLength: 3, poolSize: 6, allowRepeats: false, maxGuesses: 9, symbolLabels: ["👤","🏠","🔪","🩸","🕯️","🧥"], scenarioLabel: "Séance", scenarioEmoji: "👻" },
    intro: "Suspect / location / weapon." },
  { folder: "mystery-abbey", prefix: "myab", title: "Mystery of the Abbey", accent: "#a16207", bg: "#fef3c7",
    description: "Identify the missing monk.",
    cfg: { mode: "exact", answerLength: 3, poolSize: 6, allowRepeats: false, maxGuesses: 10, symbolLabels: ["🍞","🍇","📜","🔔","🕯️","🪤"], scenarioLabel: "Abbey Mystery", scenarioEmoji: "⛪" },
    intro: "Three traits of the missing monk." },
  { folder: "awkward-guests", prefix: "awg", title: "Awkward Guests", accent: "#7c3aed", bg: "#ede9fe",
    description: "Cluedo-style detective deduction.",
    cfg: { mode: "exact", answerLength: 3, poolSize: 6, allowRepeats: false, maxGuesses: 10, symbolLabels: ["🤵","💃","🎩","👮","🧑‍🍳","🕵️"], scenarioLabel: "Mansion Murder", scenarioEmoji: "🍷" },
    intro: "Suspect, weapon, room." },
  { folder: "deadly-dowagers", prefix: "ddw", title: "Deadly Dowagers", accent: "#9d174d", bg: "#fce7f3",
    description: "Identify the deadly dowager.",
    cfg: { mode: "exact", answerLength: 3, poolSize: 6, allowRepeats: false, maxGuesses: 10, symbolLabels: ["👵","🍵","🎭","💎","🪞","🕯️"], scenarioLabel: "Edwardian Murder", scenarioEmoji: "🥀" },
    intro: "Pin down dowager / weapon / clue." },
  { folder: "lingo-deduction", prefix: "lng", title: "Lingo", accent: "#16a34a", bg: "#dcfce7",
    description: "Five-letter word deduction.",
    cfg: { mode: "exact", answerLength: 5, poolSize: 10, allowRepeats: false, maxGuesses: 6, symbolLabels: ["A","E","I","O","U","R","S","T","L","N"], scenarioLabel: "Lingo", scenarioEmoji: "🎯" },
    intro: "Six tries to find the 5-letter word." },
  { folder: "tempel-deduction", prefix: "tmd2", title: "Tempel", accent: "#a16207", bg: "#fef3c7",
    description: "Find the temple's hidden treasures.",
    cfg: { mode: "exact", answerLength: 3, poolSize: 6, allowRepeats: false, maxGuesses: 8, symbolLabels: ["💎","🏺","📿","🗝️","🪨","🪙"], scenarioLabel: "Temple Run", scenarioEmoji: "🏛️" },
    intro: "Pick three treasure tiles." },
  { folder: "tempel-trap", prefix: "tmtr", title: "Tempel: Traps", accent: "#92400e", bg: "#fef3c7",
    description: "Avoid the four traps.",
    cfg: { mode: "exact", answerLength: 4, poolSize: 6, allowRepeats: false, maxGuesses: 9, symbolLabels: ["🪤","🗡️","🔥","💀","🪨","🐍"], scenarioLabel: "Trap Maze", scenarioEmoji: "🪤" },
    intro: "Pick the safe path of four." },
  // Cryptid family
  { folder: "cryptid-mini", prefix: "crm", title: "Cryptid Mini", accent: "#15803d", bg: "#dcfce7",
    description: "Find the cryptid hex.",
    cfg: { mode: "exact", answerLength: 2, poolSize: 6, allowRepeats: false, maxGuesses: 8, symbolLabels: ["A","B","C","D","E","F"], scenarioLabel: "Cryptid", scenarioEmoji: "🦄" },
    intro: "Two coordinates of the lair." },
  { folder: "cryptid-deduction", prefix: "crd", title: "Cryptid Deduction", accent: "#16a34a", bg: "#dcfce7",
    description: "Cryptid logic puzzle.",
    cfg: { mode: "exact", answerLength: 3, poolSize: 6, allowRepeats: false, maxGuesses: 9, symbolLabels: ["🌲","🏔️","🏜️","💧","🐾","🌫️"], scenarioLabel: "Find the Cryptid", scenarioEmoji: "👣" },
    intro: "Cross-reference clues to find the lair." },
  { folder: "cryptid-urban-roll", prefix: "cur", title: "Cryptid: Urban Roll", accent: "#0891b2", bg: "#cffafe",
    description: "Urban Cryptid variant.",
    cfg: { mode: "exact", answerLength: 3, poolSize: 6, allowRepeats: false, maxGuesses: 9, symbolLabels: ["🏙️","🚇","🌉","🏟️","🏬","🛣️"], scenarioLabel: "Cryptid in the City", scenarioEmoji: "🌆" },
    intro: "Track cryptid through urban tiles." },
  { folder: "deception-hk", prefix: "dhk", title: "Deception: Hong Kong", accent: "#0f172a", bg: "#e2e8f0",
    description: "Forensic deduction puzzle.",
    cfg: { mode: "exact", answerLength: 3, poolSize: 6, allowRepeats: false, maxGuesses: 10, symbolLabels: ["🔪","💊","🪢","🔫","🗡️","🪤"], scenarioLabel: "HK Investigation", scenarioEmoji: "🏙️" },
    intro: "Identify weapon, evidence, scene." },
  { folder: "chronicles-of-crime", prefix: "coc", title: "Chronicles of Crime", accent: "#1e3a8a", bg: "#dbeafe",
    description: "Crime-scene deduction.",
    cfg: { mode: "exact", answerLength: 3, poolSize: 6, allowRepeats: false, maxGuesses: 10, symbolLabels: ["🔍","🔪","💊","🪢","🔫","🪤"], scenarioLabel: "Crime Scene", scenarioEmoji: "🚨" },
    intro: "Pin down weapon / motive / suspect." },
  // Spyfall / Chameleon / Insider / Saboteur / Coup / Skull / Cheat / Cockroach / Kakerlaken / Palifico
  { folder: "spyfall-mini", prefix: "sfm", title: "Spyfall Mini", accent: "#0c4a6e", bg: "#e0f2fe",
    description: "Identify the location among 8.",
    cfg: { mode: "exact", answerLength: 1, poolSize: 8, allowRepeats: false, maxGuesses: 5, symbolLabels: ["🏝️","🚀","🏥","🎬","✈️","🏰","🚂","🏟️"], scenarioLabel: "Identify Location", scenarioEmoji: "🕵️" },
    intro: "Only one is the spy's location." },
  { folder: "chameleon-bluff", prefix: "chb", title: "The Chameleon", accent: "#16a34a", bg: "#dcfce7",
    description: "Find the chameleon among words.",
    cfg: { mode: "exact", answerLength: 1, poolSize: 8, allowRepeats: false, maxGuesses: 5, symbolLabels: ["A","B","C","D","E","F","G","H"], scenarioLabel: "Chameleon Hunt", scenarioEmoji: "🦎" },
    intro: "Spot the odd one out." },
  { folder: "insider-quiz", prefix: "ins", title: "Insider", accent: "#0891b2", bg: "#cffafe",
    description: "Detect the insider.",
    cfg: { mode: "exact", answerLength: 1, poolSize: 6, allowRepeats: false, maxGuesses: 5, symbolLabels: ["1","2","3","4","5","6"], scenarioLabel: "Find Insider", scenarioEmoji: "🔎" },
    intro: "One of six knows the answer in advance." },
  { folder: "saboteur-mini", prefix: "sbt", title: "Saboteur Mini", accent: "#a16207", bg: "#fef3c7",
    description: "Find the saboteur miner.",
    cfg: { mode: "exact", answerLength: 1, poolSize: 6, allowRepeats: false, maxGuesses: 5, symbolLabels: ["⛏️1","⛏️2","⛏️3","⛏️4","⛏️5","⛏️6"], scenarioLabel: "Mine Saboteur", scenarioEmoji: "💎" },
    intro: "One miner is sabotaging." },
  { folder: "coup-bluff", prefix: "cpb", title: "Coup: Bluff Puzzle", accent: "#7f1d1d", bg: "#fee2e2",
    description: "Deduce hidden roles in Coup.",
    cfg: { mode: "exact", answerLength: 2, poolSize: 5, allowRepeats: false, maxGuesses: 8, symbolLabels: ["Duke","Captain","Assassin","Ambassador","Contessa"], scenarioLabel: "Coup Court", scenarioEmoji: "👑" },
    intro: "Two unknown influence cards." },
  { folder: "skull-bluff", prefix: "sk", title: "Skull", accent: "#0f172a", bg: "#e2e8f0",
    description: "Find roses, dodge skulls.",
    cfg: { mode: "exact", answerLength: 2, poolSize: 4, allowRepeats: false, maxGuesses: 6, symbolLabels: ["🌹","💀","🌹","💀"], scenarioLabel: "Skull Standoff", scenarioEmoji: "💀" },
    intro: "Pick two coasters; flowers only." },
  { folder: "cheat-bs", prefix: "ch", title: "Cheat / BS", accent: "#dc2626", bg: "#fee2e2",
    description: "Spot the bluff.",
    cfg: { mode: "exact", answerLength: 2, poolSize: 4, allowRepeats: false, maxGuesses: 6, symbolLabels: ["A","2","3","4"], scenarioLabel: "Cheat!", scenarioEmoji: "🎴" },
    intro: "Catch which two cards are bluffs." },
  { folder: "cockroach-bluff", prefix: "ckr", title: "Cockroach Poker", accent: "#65a30d", bg: "#ecfccb",
    description: "Cockroach Poker deduction.",
    cfg: { mode: "exact", answerLength: 2, poolSize: 4, allowRepeats: false, maxGuesses: 6, symbolLabels: ["🪲","🪳","🐀","🦟"], scenarioLabel: "Bluff or Truth", scenarioEmoji: "🪳" },
    intro: "Pick whether opponent is bluffing on each card." },
  { folder: "kakerlaken-poker", prefix: "kpk", title: "Kakerlaken Poker", accent: "#a16207", bg: "#fef3c7",
    description: "German Cockroach Poker.",
    cfg: { mode: "exact", answerLength: 2, poolSize: 4, allowRepeats: false, maxGuesses: 6, symbolLabels: ["🪲","🪳","🐀","🦟"], scenarioLabel: "Käfer Bluff", scenarioEmoji: "🪲" },
    intro: "Bluff guess on two cards." },
  { folder: "palifico", prefix: "plf", title: "Palifico", accent: "#9333ea", bg: "#f3e8ff",
    description: "Liar's Dice variant.",
    cfg: { mode: "exact", answerLength: 2, poolSize: 6, allowRepeats: true, maxGuesses: 8, symbolLabels: ["1","2","3","4","5","6"], scenarioLabel: "Palifico", scenarioEmoji: "🎲" },
    intro: "Liar's dice round." },
  // Clue family
  { folder: "clue-mini", prefix: "clm", title: "Clue Mini", accent: "#dc2626", bg: "#fee2e2",
    description: "Murder, Suspect, Location, Weapon.",
    cfg: { mode: "exact", answerLength: 3, poolSize: 6, allowRepeats: false, maxGuesses: 8, symbolLabels: ["Plum","Green","Mustard","Scarlet","Peacock","White"], scenarioLabel: "Clue", scenarioEmoji: "🕵️" },
    intro: "Suspect / weapon / room." },
  { folder: "clue-master-detective", prefix: "cmd", title: "Clue: Master Detective", accent: "#b91c1c", bg: "#fef2f2",
    description: "Expanded Clue with more rooms.",
    cfg: { mode: "exact", answerLength: 3, poolSize: 8, allowRepeats: false, maxGuesses: 10, symbolLabels: ["Plum","Green","Mustard","Scarlet","Peacock","White","Rose","Brunette"], scenarioLabel: "Master Detective", scenarioEmoji: "🔎" },
    intro: "8 suspects, 8 rooms, 8 weapons." },
  { folder: "clue-suspect", prefix: "csus", title: "Clue: Suspect", accent: "#7f1d1d", bg: "#fee2e2",
    description: "Suspect-themed Clue card game.",
    cfg: { mode: "exact", answerLength: 3, poolSize: 6, allowRepeats: false, maxGuesses: 9, symbolLabels: ["A","B","C","D","E","F"], scenarioLabel: "Suspect", scenarioEmoji: "🃏" },
    intro: "Only one combo solves it." },
  // Hanabi (separate handling for engine but treat as deduction-ish)
];
