import {
  makeInitialState,
  reducer as engineReducer,
  isTerminal as engineTerminal,
  type MahjongState,
  type MahjongAction,
  type TilePos,
} from "../_shared/mahjongEngine.js";

export type MahjongTheatreLayoutState = MahjongState;
export type MahjongTheatreLayoutAction = MahjongAction;

export const LAYOUT: TilePos[] = [
  { row: 0, col: 0, layer: 0 },
  { row: 0, col: 2, layer: 0 },
  { row: 0, col: 4, layer: 0 },
  { row: 0, col: 6, layer: 0 },
  { row: 0, col: 8, layer: 0 },
  { row: 0, col: 10, layer: 0 },
  { row: 0, col: 12, layer: 0 },
  { row: 0, col: 14, layer: 0 },
  { row: 0, col: 16, layer: 0 },
  { row: 0, col: 18, layer: 0 },
  { row: 0, col: 20, layer: 0 },
  { row: 0, col: 22, layer: 0 },
  { row: 1, col: 1, layer: 0 },
  { row: 1, col: 3, layer: 0 },
  { row: 1, col: 5, layer: 0 },
  { row: 1, col: 7, layer: 0 },
  { row: 1, col: 9, layer: 0 },
  { row: 1, col: 11, layer: 0 },
  { row: 1, col: 13, layer: 0 },
  { row: 1, col: 15, layer: 0 },
  { row: 1, col: 17, layer: 0 },
  { row: 1, col: 19, layer: 0 },
  { row: 1, col: 21, layer: 0 },
  { row: 1, col: 23, layer: 0 },
  { row: 2, col: 0, layer: 0 },
  { row: 2, col: 2, layer: 0 },
  { row: 2, col: 4, layer: 0 },
  { row: 2, col: 6, layer: 0 },
  { row: 2, col: 8, layer: 0 },
  { row: 2, col: 10, layer: 0 },
  { row: 2, col: 12, layer: 0 },
  { row: 2, col: 14, layer: 0 },
  { row: 2, col: 16, layer: 0 },
  { row: 2, col: 18, layer: 0 },
  { row: 2, col: 20, layer: 0 },
  { row: 2, col: 22, layer: 0 },
  { row: 3, col: 1, layer: 0 },
  { row: 3, col: 3, layer: 0 },
  { row: 3, col: 5, layer: 0 },
  { row: 3, col: 7, layer: 0 },
  { row: 3, col: 9, layer: 0 },
  { row: 3, col: 11, layer: 0 },
  { row: 3, col: 13, layer: 0 },
  { row: 3, col: 15, layer: 0 },
  { row: 3, col: 17, layer: 0 },
  { row: 3, col: 19, layer: 0 },
  { row: 3, col: 21, layer: 0 },
  { row: 3, col: 23, layer: 0 },
  { row: 4, col: 0, layer: 0 },
  { row: 4, col: 2, layer: 0 },
  { row: 4, col: 4, layer: 0 },
  { row: 4, col: 6, layer: 0 },
  { row: 4, col: 8, layer: 0 },
  { row: 4, col: 10, layer: 0 },
  { row: 4, col: 12, layer: 0 },
  { row: 4, col: 14, layer: 0 },
  { row: 4, col: 16, layer: 0 },
  { row: 4, col: 18, layer: 0 },
  { row: 4, col: 20, layer: 0 },
  { row: 4, col: 22, layer: 0 },
  { row: 5, col: 1, layer: 0 },
  { row: 5, col: 3, layer: 0 },
  { row: 5, col: 5, layer: 0 },
  { row: 5, col: 7, layer: 0 },
  { row: 5, col: 9, layer: 0 },
  { row: 5, col: 11, layer: 0 },
  { row: 5, col: 13, layer: 0 },
  { row: 5, col: 15, layer: 0 },
  { row: 5, col: 17, layer: 0 },
  { row: 5, col: 19, layer: 0 },
  { row: 5, col: 21, layer: 0 },
  { row: 5, col: 23, layer: 0 }
];

export function initialState(seed: number, _settings: Record<string, never> = {}): MahjongState {
  void _settings;
  return makeInitialState(LAYOUT, seed);
}

export const reducer = engineReducer;
export const isTerminal = engineTerminal;
