// Word Construction — words organized by prefix
export const PREFIX_WORDS: Record<string, readonly string[]> = {
  "UN": [
    "UNITE","UNIFY","UNDO","UNDO","UNCLE","UNDER","UNION","UNTIL","UPPER","URBAN",
    "UNITY","UNFIT","UNPEG","UNZIP","UNSAY","UNBOX","UNCUT","UNDID","UNDUE",
    "UNEASY","UNFAIR","UNHOOK","UNKIND","UNLINK","UNLOCK","UNLOAD","UNPACK",
    "UNREAL","UNREST","UNSAFE","UNTOLD","UNTRUE","UNWRAP","UNUSED","UNSUNG",
    "UNABLE","UNBORN","UNDONE","UNEASY","UNFOLD","UNGRAB","UNHAPPY","UNIFY",
  ],
  "RE": [
    "READ","REAL","REAR","REED","REEF","REEL","REEL","RELY","RENT","REST",
    "REDO","REMIX","RENEW","REPAY","REPEL","REPAY","RESET","RIDER","RIGHT",
    "REACH","REALM","REBEL","REFER","REIGN","RELAX","RENEW","RESET","REUSE",
    "REACT","READY","REALM","REAP","REAR","RECE","REBUY","RECAP","RECUR",
    "REFER","REIGN","RELAY","RELY","REMIT","RENEW","REPAY","REPEL","REPLY",
    "RERUN","RESAY","RESET","RETCH","RETRY","REUSE","REVEL","REVERT","REVOKE",
    "RECALL","RECENT","REDUCE","REFORM","REFUSE","REMAIN","REMOVE","REPAIR","REPLY",
    "REPORT","RETURN","REVEAL","REVIEW","REVISE","REVOKE","REWARD","REWIND",
  ],
  "PRE": [
    "PRESS","PRICE","PRIDE","PRIME","PRINT","PRIZE","PROBE","PROOF","PROSE",
    "PREFER","PRETTY","PRINCE","PRISON","PROFIT","PROPER","PROVEN","PROVIDE",
    "PREPARE","PREVENT","PRIVATE","PROCESS","PRODUCT","PROJECT","PROTECT","PROMISE",
    "PRESENT","PROBLEM","PROGRAM","PREVIEW","PREDICT","PRECISE","PRELUDE","PREFACE",
  ],
  "OUT": [
    "OUTDO","OUTGO","OUTER","OUTRUN","OUTBID","OUTBOX","OUTBUY","OUTFLY",
    "OUTFOX","OUTGUN","OUTING","OUTLAW","OUTLET","OUTPAY","OUTPUT","OUTSET",
    "OUTFIT","OUTACT","OUTAGE","OUTBEG","OUTCUT","OUTDID","OUTEYE","OUTFED",
    "OUTCOME","OUTDOOR","OUTFLOW","OUTGROW","OUTLOOK","OUTNUMBER","OUTPOST","OUTRAGE",
  ],
  "OVER": [
    "OVARY","OVERT","OVERDO","OVERGO","OVERLY","OVERRUN","OVERALL","OVERDUE",
    "OVERHEAR","OVERLAP","OVERLAY","OVERPASS","OVERPLAY","OVERPAY","OVERRATE","OVERSEE",
    "OVERSIZE","OVERSEE","OVERSHOOT","OVERCOME","OVERFLOW","OVERHAUL","OVERLOAD","OVERRULE",
  ],
  "MIS": [
    "MISS","MIST","MISUSE","MISHAP","MISFIT","MISLED","MISLAY","MISREAD",
    "MISTAKE","MISLEAD","MISPLACE","MISSPELL","MISTIME","MISTRUST","MISGUIDE",
    "MISBEHAVE","MISCHIEF","MISCOUNT","MISDO","MISFEED","MISFILE","MISFIRE",
  ],
  "DIS": [
    "DISH","DISK","DISCO","DISCUS","DISDAIN","DISEASE","DISLIKE","DISMAY",
    "DISORDER","DISPLAY","DISPOSE","DISRUPT","DISTORT","DISTRUST","DISTURB",
    "DISCARD","DISMISS","DISOWN","DISPROVE","DISSENT","DISTANT","DIVIDE",
  ],
  "IN": [
    "INCH","IRON","ISLE","ITCH","ITEM","INNER","IMAGE","INDEX","IDEAL",
    "INBOX","INBORN","INCOME","INDEED","INFORM","INJECT","INLAY","INLINE",
    "INMATE","INNATE","INSANE","INSERT","INSIDE","INVENT","INVEST","INVITE",
    "INCLUDE","INSPIRE","INTEGER","INVOLVE","INROADS","INSIGHT","INTERIM",
  ],
};

export const ALL_PREFIXES = Object.keys(PREFIX_WORDS) as string[];

export function isValidPrefixWord(word: string, prefix: string): boolean {
  const upper = word.toUpperCase();
  if (!upper.startsWith(prefix.toUpperCase())) return false;
  const list = PREFIX_WORDS[prefix.toUpperCase()] ?? [];
  return list.some(w => w.toUpperCase() === upper);
}
