import type { GamePlugin, SettingsOf } from "../../platform/game-plugin/types.js";
import type { LightsOut5x5State, LightsOut5x5Action, LightsOut5x5Settings } from "./state.js";
import { initialState, reducer, isTerminal } from "./state.js";
import { LightsOut5x5Game } from "./Game.js";

const settings = { dummy: { kind: "boolean" as const, label: "dummy", default: false } } as const;
type S = SettingsOf<typeof settings>;

export const lightsOut5x5Plugin: GamePlugin<LightsOut5x5State, LightsOut5x5Action, typeof settings> = {
  id: "lights-out-5x5",
  title: "Lights Out 5×5",
  category: "board",
  players: { min: 1, max: 1, multiplayer: false },
  description: `Full 5×5 Lights Out: tap cells to toggle them and neighbours; aim for all-off.`,
  howToPlay: `Lights Out 5×5 is the full-size version of the 1995 Tiger Electronics handheld classic. The board is a 5×5 grid of cells, each lit (yellow) or unlit (dark). When you tap a cell, that cell AND its four orthogonal neighbours flip state.

The starting board is generated by pressing 8–14 random cells from an all-off board, which guarantees solvability. Your goal is to turn every light off.

Scoring: 600 points minus 8 per move, with a 80-point floor. Every solvable board has a unique minimum-move solution.

Tips: Lights Out has an elegant linear-algebra structure over GF(2). The "light chasing" technique works for 5×5: solve row 1 by pressing the row-2 cell directly under each lit row-1 cell, then row 2 with row 3, etc. The bottom row may not solve cleanly — there are exactly seven valid bottom-row patterns; for each you press a specific set in row 1 and re-chase. With practice you can solve any 5×5 in under 15 moves.`,
  settings,
  initialState: (seed: number, s: S) => initialState(seed, s as LightsOut5x5Settings),
  reducer,
  isTerminal,
  hint: (s: any) => { const p = (s as any).phase; if (p === "done" || p === "gameover" || p === "ended" || p === "finished" || (s as any).gameOver || (s as any).won || (s as any).complete || (s as any).isComplete) return null; return { selector: ".lo5-btn", pulses: 3 }; },
  component: LightsOut5x5Game,
};
