// =====================================================================
// Game families
// ---------------------------------------------------------------------
// With 4500+ games in the registry, the lobby grid becomes unscannable.
// Many games are minor variants of a few well-known titles (Klondike,
// FreeCell, Spider, Mahjong, Hold'em, Yahtzee, etc.) — collapsing those
// into a single "family" tile that opens a variant picker dramatically
// reduces visual noise without hiding any games.
//
// Each family is defined by:
//   - id           : stable family slug (also used as the tile testid:
//                    `tile-<familyId>`). For families that share an id
//                    with an existing game (e.g. `klondike`), the family
//                    tile replaces that game's standalone tile. The
//                    underlying game is still accessible from inside the
//                    picker.
//   - label        : human-readable family name shown on the tile.
//   - description  : 1-line summary used on the family tile.
//   - matches      : either an explicit list of member game IDs, OR a
//                    predicate over IDs (used for `mahjong-*` since
//                    listing 110+ layouts inline is noisy).
//
// Resolution rule: a game belongs to the FIRST family whose `matches`
// returns true. Order in `FAMILIES` therefore matters when ids could
// theoretically match multiple families — keep the most specific
// families earlier in the list. In practice the explicit-list families
// rarely overlap; the only generic predicate (`mahjong`) is unique.
// =====================================================================

export interface GameFamily {
  id: string;
  label: string;
  description: string;
  /** Explicit list of member game ids. */
  memberIds?: readonly string[];
  /** Optional predicate — used when listing IDs would be unwieldy. */
  matches?: (id: string) => boolean;
}

/**
 * Build a Set of every member id covered by `family`. Used by the lobby
 * to compute "is this game inside a family" without re-running the
 * predicate on every render.
 */
export function expandFamily(
  family: GameFamily,
  allIds: readonly string[],
): Set<string> {
  const out = new Set<string>();
  if (family.memberIds) for (const id of family.memberIds) out.add(id);
  if (family.matches) {
    for (const id of allIds) if (family.matches(id)) out.add(id);
  }
  return out;
}

export const FAMILIES: readonly GameFamily[] = [
  // ---------- Solitaire patiences ----------
  {
    id: "klondike",
    label: "Klondike",
    description: "The classic seven-pile patience and its many flavours.",
    memberIds: [
      "klondike",
      "klondike-by-threes",
      "klondike-deal-one",
      "klondike-deal-one-no-redeal",
      "klondike-no-redeal",
      "klondike-super-solver",
      "klondike-threes-no-redeal",
      "klondike-threes-standard",
      "double-klondike",
      "double-klondike-pat",
      "triple-klondike",
      "vegas-klondike",
      "bakers-klondike",
      "chinese-klondike",
    ],
  },
  {
    id: "freecell",
    label: "FreeCell",
    description: "Open-information cell games — no luck, all deduction.",
    memberIds: [
      "freecell",
      "freecell-classic",
      "freecell-two-deck",
      "double-freecell",
      "double-deck-freecell",
      "triple-freecell",
      "eight-off",
      "mini-eight-off",
      "seahaven-towers",
      "bakers-game",
    ],
  },
  {
    id: "spider",
    label: "Spider",
    description: "Two-deck cascade solitaires — sequence by suit and clear.",
    memberIds: [
      "spider",
      "spider-one-suit",
      "spider-two-suits",
      "spider-four-suits",
      "mini-spider-1suit",
      "relaxed-spider",
      "spiderette",
      "little-spider",
      "spidike",
      "wasp",
      "wasp-pat",
      "wasp-soli",
      "wasp-whip",
      "scorpion",
      "scorpion-pat",
      "scorpion-soli",
      "scorpion-tail",
      "black-widow",
      "black-widow-spider",
      "will-o-wisp",
      "will-o-the-wisp",
    ],
  },
  {
    id: "yukon",
    label: "Yukon",
    description: "Klondike's wilder cousin — move any face-up card with its tail.",
    memberIds: [
      "yukon",
      "yukon-cells",
      "moosehide",
      "moosehide-yukon",
      "alaska",
      "alaska-pat",
      "alaska-solitaire",
      "russian-soli",
      "russian-solitaire",
    ],
  },
  {
    id: "pyramid",
    label: "Pyramid",
    description: "Pair to thirteen and dismantle the tomb.",
    memberIds: [
      "pyramid",
      "pyramid-golf",
      "pyramid-no-redeal",
      "pyramid-solitaire-classic",
      "mini-pyramid-solitaire",
      "pharaohs-pyramid",
      "giza",
      "giza-pyramid",
      "tut-tomb",
      "tuts-tomb",
    ],
  },
  {
    id: "tri-peaks",
    label: "TriPeaks",
    description: "Climb three peaks one card at a time.",
    memberIds: [
      "tri-peaks",
      "tri-peaks-continuous",
      "tri-peaks-solitaire",
      "mini-tripeaks",
    ],
  },
  {
    id: "forty-thieves",
    label: "Forty Thieves",
    description: "Ten-column open patiences — Napoleon's favourite family.",
    memberIds: [
      "forty-thieves",
      "limited-forty-thieves",
      "big-forty",
      "forty-and-eight",
      "forty-eight-one-deck",
      "lucas",
      "maria",
      "number-ten",
      "streets",
      "streets-and-alleys",
      "indian",
      "indian-fty",
      "indian-patience",
      "josephine",
      "blockade",
      "busy-aces",
      "gigantic",
      "presidents-cabinet",
    ],
  },
  {
    id: "canfield",
    label: "Canfield",
    description: "Casino patience with a thirteen-card reserve.",
    memberIds: [
      "canfield",
      "canfield-chameleon",
      "canfield-storehouse",
      "storehouse",
      "storehouse-canfield",
      "demon",
      "demon-patience",
      "rainbow-canfield",
      "selective-canfield",
      "superior-canfield",
    ],
  },

  // ---------- Tile-matching ----------
  {
    id: "mahjong-solitaire",
    label: "Mahjong Solitaire",
    description: "Match free tiles across dozens of hand-built layouts.",
    matches: (id) => id.startsWith("mahjong-"),
  },

  // ---------- Poker ----------
  {
    id: "holdem",
    label: "Texas Hold'em",
    description: "Two-card hold'em across every limit and casino variant.",
    memberIds: [
      "holdem-no-limit",
      "holdem-pot-limit",
      "holdem-fixed-limit",
      "holdem-spread-limit",
      "short-deck-holdem",
      "super-holdem",
      "double-flop-holdem",
      "ultimate-holdem",
      "casino-holdem",
      "casino-holdem-cas",
      "royal-holdem",
      "heads-up-holdem-cas",
    ],
  },
  {
    id: "omaha",
    label: "Omaha",
    description: "Four (or five) hole cards, must use exactly two.",
    memberIds: [
      "omaha-hi",
      "omaha-hi-lo",
      "omaha-five-card-hi",
      "omaha-five-card-hi-lo",
      "omaha-six-card-hi",
      "omaha-holdem",
      "courchevel-poker",
      "courchevel-cas",
      "courchevel-hi-lo",
      "big-o-plo",
      "plo6-poker",
    ],
  },
  {
    id: "stud",
    label: "Stud Poker",
    description: "Open-board stud games — five and seven card.",
    memberIds: [
      "seven-card-stud",
      "seven-card-stud-hi-lo-cas",
      "seven-stud-hi-lo",
      "five-card-stud-cas",
      "five-card-stud-classic",
      "five-stud-poker",
    ],
  },
  {
    id: "lowball-draw",
    label: "Lowball & Draw",
    description: "Draw poker variants where the lowest hand wins.",
    memberIds: [
      "two-seven-triple-draw",
      "two-seven-single-draw",
      "ace-five-triple-draw",
      "badugi",
      "badeucy-poker",
      "badacey-poker",
      "kansas-city-lowball",
      "cal-lowball",
    ],
  },
  {
    id: "pineapple",
    label: "Pineapple Poker",
    description: "Hold'em with three hole cards — discard, then play.",
    memberIds: [
      "pineapple-poker",
      "crazy-pineapple",
      "crazy-pineapple-cas",
      "lazy-pineapple",
      "lazy-pineapple-cas",
      "pineapple-ofc",
      "pineapple-ofc-cas",
      "ofc-pineapple-cas",
    ],
  },

  // ---------- Casino ----------
  {
    id: "blackjack",
    label: "Blackjack",
    description: "Beat the dealer to twenty-one — every house variant.",
    memberIds: [
      "blackjack",
      "blackjack-switch",
      "blackjack-switch-cas",
      "atlantic-city-bj-cas",
      "european-bj-cas",
      "spanish-21",
      "spanish-21-cas",
      "pontoon",
      "pontoon-cas",
    ],
  },

  // ---------- Dice ----------
  {
    id: "yahtzee",
    label: "Yahtzee",
    description: "Five-dice category scoring — and its many sequels.",
    memberIds: [
      "yahtzee",
      "yahtzee-mini",
      "mini-yahtzee",
      "open-face-yahtzee",
      "yahtzee-boss-dice",
      "yahtzee-free-for-all",
      "triple-yahtzee",
      "battle-yahtzee",
      "jumbo-yahtzee",
      "kniffel",
      "yamb-dice",
      "maxi-yatzy",
      "yatzy-scand",
    ],
  },

  // ---------- Board ----------
  {
    id: "connect-four",
    label: "Connect Four",
    description: "Drop discs to make a line — every shape and rule twist.",
    memberIds: [
      "connect-4",
      "connect-four-classic",
      "connect-four-classic-cl",
      "connect-four-mini",
      "connect-four-3d",
      "connect-four-gravity-flip",
      "connect-four-pop10",
      "connect-four-popout",
      "connect-four-power-checker",
      "connect-five",
      "connect-six",
      "connect-six-classic",
      "connect6",
    ],
  },
  {
    id: "backgammon",
    label: "Backgammon",
    description: "Race your checkers home — classics and short games.",
    memberIds: [
      "backgammon-standard-race",
      "nackgammon",
      "hyper-backgammon",
      "hypergammon",
      "hypergammon-mini",
      "narde-russian",
      "tavli-greek-race",
      "tavli-portes-race",
      "fevga-tavli",
      "plakoto-tavli",
      "acey-deucey",
      "acey-deucey-cas",
      "acey-deucey-in-between",
    ],
  },
  {
    id: "mastermind",
    label: "Mastermind",
    description: "Crack the colour code in as few guesses as you can.",
    memberIds: [
      "mastermind",
      "mastermind-5peg-8color",
      "mastermind-6peg-10color",
      "mastermind-no-repeats",
    ],
  },
  {
    id: "sudoku",
    label: "Sudoku",
    description: "Logic-fill grids from 4×4 minis up to 25×25 monsters.",
    memberIds: [
      "sudoku",
      "sudoku-classic-pl",
      "sudoku-159",
      "sudoku-16",
      "sudoku-25",
      "sudoku-mini-4x4",
      "sudoku-mini-6x6",
    ],
  },

  // ---------- Trivia / quiz sub-families ----------
  {
    id: "decades-trivia",
    label: "Decades Trivia",
    description: "Test yourself on every decade from the 1920s to the 2010s.",
    memberIds: [
      "1920s-quiz",
      "1930s-quiz",
      "1940s-quiz",
      "1950s-quiz",
      "1960s-quiz",
      "1970s-quiz",
      "1980s-quiz",
      "1990s-quiz",
      "2000s-quiz",
      "2010s-quiz",
    ],
  },
  {
    id: "music-genre-trivia",
    label: "Music Genre Trivia",
    description: "Quizzes covering rock, jazz, classical, hip-hop and more.",
    memberIds: [
      "boy-bands-quiz",
      "classical-music-quiz",
      "composers-classical-quiz",
      "country-music-quiz",
      "electronic-music-quiz",
      "folk-music-quiz",
      "gospel-music-quiz",
      "hip-hop-quiz",
      "jazz-quiz",
      "mtv-music-awards-quiz",
      "musical-instruments-quiz",
      "music-decade-quiz",
      "music-notation-quiz",
      "music-theory-quiz",
      "pop-music-quiz",
      "rock-music-quiz",
    ],
  },
  {
    id: "chess-variants-trivia",
    label: "Chess Variants Trivia",
    description: "Quizzes on Atomic, Crazyhouse, Capablanca and other variants.",
    memberIds: [
      "atomic-chess-quiz",
      "capablanca-chess-quiz",
      "chess960-crazyhouse-quiz",
      "chess960-quiz",
      "chess-history-quiz",
      "cylinder-chess-quiz",
      "dark-chess-quiz",
      "four-player-chess-quiz",
      "horde-chess-quiz",
      "legan-chess-quiz",
      "losing-chess-quiz",
      "minichess-5x5-quiz",
      "omega-chess-quiz",
      "progressive-chess-quiz",
      "rifle-chess-quiz",
      "seirawan-chess-quiz",
      "spartan-chess-quiz",
      "toroidal-chess-quiz",
    ],
  },

  // =====================================================================
  //   Trivia / quiz themed families (expanded)
  // =====================================================================

  // ---------- Music sub-families ----------
  {
    id: "music-icons-trivia",
    label: "Music Icons Trivia",
    description: "Quizzes on Elvis, Bowie, Madonna, the Beatles and more legends.",
    memberIds: [
      "beatles-quiz",
      "bowie-quiz",
      "elvis-quiz",
      "led-zeppelin-quiz",
      "madonna-quiz",
      "pink-floyd-quiz",
      "prince-quiz",
      "rolling-stones-quiz",
    ],
  },
  {
    id: "music-eras-trivia",
    label: "Music Eras Trivia",
    description: "Disco, grunge, MTV, rave, streaming — every era of pop music.",
    memberIds: [
      "boy-bands-quiz",
      "disco-era-quiz",
      "girl-groups-quiz",
      "grunge-era-quiz",
      "karaoke-classics-quiz",
      "meme-era-quiz",
      "mtv-era-quiz",
      "music-decade-quiz",
      "one-hit-wonders-quiz",
      "rave-era-quiz",
      "streaming-era-quiz",
      "summer-hits-quiz",
    ],
  },
  {
    id: "composers-trivia",
    label: "Composers Trivia",
    description: "Classical, romantic and modern composer quizzes.",
    memberIds: [
      "composers-classical-quiz",
      "composers-modern-quiz",
      "composers-quiz",
      "composers-romantic-quiz",
    ],
  },
  {
    id: "music-theory-trivia",
    label: "Music Theory Trivia",
    description: "Notation, theory, modes, instruments and recording tech.",
    memberIds: [
      "chord-progressions-quiz",
      "instruments-quiz",
      "keys-and-modes-quiz",
      "music-notation-quiz",
      "music-theory-quiz",
      "musical-instruments-quiz",
      "recording-tech-quiz",
      "synthesizers-quiz",
    ],
  },
  {
    id: "music-awards-trivia",
    label: "Music Awards Trivia",
    description: "Grammys, Billboard, MTV, Eurovision and televised music shows.",
    memberIds: [
      "american-idol-quiz",
      "billboard-hits-quiz",
      "eurovision-quiz",
      "grammy-awards-quiz",
      "mtv-music-awards-quiz",
      "voice-show-quiz",
      "xfactor-quiz",
    ],
  },

  // ---------- Awards & ceremonies ----------
  {
    id: "screen-awards-trivia",
    label: "Screen Awards Trivia",
    description: "Oscars, Emmys, Tonys, Cannes, Palme d'Or — celebrating cinema.",
    memberIds: [
      "academy-awards-quiz",
      "cannes-quiz",
      "emmy-awards-quiz",
      "oscar-films-quiz",
      "palme-dor-quiz",
      "tony-awards-quiz",
    ],
  },
  {
    id: "literary-awards-trivia",
    label: "Literary Awards Trivia",
    description: "Pulitzers, Bookers, Nobel laureates and other literary prizes.",
    memberIds: [
      "man-booker-quiz",
      "nobel-laureates-quiz",
      "nobel-peace-quiz",
      "pulitzer-quiz",
    ],
  },

  // ---------- Sports ----------
  {
    id: "sports-rules-trivia",
    label: "Sports Rules Trivia",
    description: "Rulebook quizzes for every major team and individual sport.",
    memberIds: [
      "baseball-rules-quiz",
      "basketball-rules-quiz",
      "boxing-rules-quiz",
      "cricket-rules-quiz",
      "football-rules-quiz",
      "hockey-rules-quiz",
      "rugby-rules-quiz",
      "soccer-rules-quiz",
      "sports-rules-quiz",
      "tennis-rules-quiz",
      "wrestling-rules-quiz",
    ],
  },
  {
    id: "sports-legends-trivia",
    label: "Sports Legends Trivia",
    description: "MLB, NBA, NFL, soccer, tennis, golf and boxing all-time greats.",
    memberIds: [
      "boxing-legends-quiz",
      "golf-greats-quiz",
      "mlb-legends-quiz",
      "nba-legends-quiz",
      "nfl-legends-quiz",
      "soccer-stars-quiz",
      "tennis-greats-quiz",
    ],
  },
  {
    id: "olympics-trivia",
    label: "Olympics Trivia",
    description: "Summer, winter, Paralympic and individual-event quizzes.",
    memberIds: [
      "bobsled-quiz",
      "figure-skating-quiz",
      "gymnastics-quiz",
      "olympic-events-quiz",
      "olympic-quiz",
      "paralympics-quiz",
      "summer-olympics-quiz",
      "swimming-events-quiz",
      "track-field-quiz",
      "winter-olympics-quiz",
    ],
  },
  {
    id: "racing-trivia",
    label: "Racing Trivia",
    description: "F1, NASCAR, horse racing and other high-speed competitions.",
    memberIds: [
      "daytona-500-quiz",
      "formula1-quiz",
      "kentucky-derby-quiz",
      "nascar-quiz",
      "racing-kings-quiz",
    ],
  },
  {
    id: "championship-trivia",
    label: "Championship Trivia",
    description: "Super Bowl, World Cup, World Series, Stanley Cup and more.",
    memberIds: [
      "ncaa-basketball-quiz",
      "stanley-cup-quiz",
      "super-bowl-quiz",
      "wimbledon-quiz",
      "world-cup-quiz",
      "world-series-quiz",
    ],
  },

  // ---------- Cuisine ----------
  {
    id: "cuisine-trivia",
    label: "Cuisine Trivia",
    description: "World cuisines from Thai to Moroccan — pizza, sushi and more.",
    memberIds: [
      "african-cuisine-quiz",
      "american-cuisine-quiz",
      "asian-cuisine-quiz",
      "bbq-quiz",
      "brazilian-cuisine-quiz",
      "bread-quiz",
      "cheese-quiz",
      "chinese-cuisine-quiz",
      "chinese-regional-cuisine-quiz",
      "cooking-techniques-quiz",
      "curry-quiz",
      "dessert-quiz",
      "dim-sum-quiz",
      "ethiopian-cuisine-quiz",
      "european-cuisine-quiz",
      "french-cuisine-quiz",
      "greek-cuisine-quiz",
      "indian-cuisine-quiz",
      "italian-cuisine-quiz",
      "japanese-cuisine-quiz",
      "korean-cuisine-quiz",
      "korean-cuisine-quiz-2",
      "lebanese-cuisine-quiz",
      "mexican-cuisine-quiz",
      "mexican-cuisine-quiz-2",
      "moroccan-cuisine-quiz",
      "nordic-cuisine-quiz",
      "pasta-quiz",
      "peruvian-cuisine-quiz",
      "pizza-quiz",
      "spanish-cuisine-quiz",
      "sushi-quiz",
      "tacos-quiz",
      "thai-cuisine-quiz",
      "thai-cuisine-quiz-2",
      "vietnamese-cuisine-quiz",
    ],
  },
  {
    id: "drinks-trivia",
    label: "Drinks Trivia",
    description: "Wines, beers, ciders, cocktails and coffee brewing.",
    memberIds: [
      "beers-quiz",
      "ciders-quiz",
      "cocktails-quiz",
      "coffee-brewing-quiz",
      "drinks-quiz",
      "drinks-types-quiz",
      "wine-pairing-quiz",
      "wines-quiz",
    ],
  },

  // ---------- Geography & culture ----------
  {
    id: "country-culture-trivia",
    label: "Country Culture Trivia",
    description: "Culture and history quizzes by country, from Japan to Brazil.",
    memberIds: [
      "australia-culture-quiz",
      "brazil-culture-quiz",
      "china-history-quiz",
      "france-culture-quiz",
      "germany-culture-quiz",
      "india-culture-quiz",
      "italy-culture-quiz",
      "japan-culture-quiz",
      "mexico-culture-quiz",
      "spain-culture-quiz",
    ],
  },
  {
    id: "geography-trivia",
    label: "Geography Trivia",
    description: "Continents, capitals, oceans, islands and world flags.",
    memberIds: [
      "african-geography-quiz",
      "asian-geography-quiz",
      "capitals-quiz",
      "cities-quiz",
      "country-flag-quiz",
      "european-cities-quiz",
      "geography-quiz",
      "geology-quiz",
      "island-quiz",
      "lake-quiz",
      "mountain-quiz",
      "mountains-quiz",
      "oceania-quiz",
      "oceans-quiz",
      "rivers-quiz",
      "south-america-quiz",
      "us-states-quiz",
      "world-capitals-quiz",
      "world-flags-quiz",
      "world-rivers-quiz",
    ],
  },
  {
    id: "city-trivia",
    label: "City Trivia",
    description: "Famous-city quizzes — Paris, Tokyo, NYC, London, Dubai and more.",
    memberIds: [
      "dubai-quiz",
      "london-quiz",
      "nyc-quiz",
      "paris-quiz",
      "rio-quiz",
      "rome-quiz",
      "sydney-quiz",
      "tokyo-quiz",
    ],
  },
  {
    id: "monuments-trivia",
    label: "Monuments Trivia",
    description: "Eiffel Tower, Taj Mahal, Colosseum and other world wonders.",
    memberIds: [
      "christ-redeemer-quiz",
      "colosseum-quiz",
      "eiffel-tower-quiz",
      "everest-quiz",
      "great-wall-quiz",
      "monuments-quiz",
      "national-parks-quiz",
      "parthenon-quiz",
      "pyramids-quiz",
      "seven-summits-quiz",
      "statue-liberty-quiz",
      "taj-mahal-quiz",
    ],
  },

  // ---------- History ----------
  {
    id: "ancient-civilizations-trivia",
    label: "Ancient Civilizations Trivia",
    description: "Egypt, Greece, Rome, Maya, Inca, Aztec, Viking and more.",
    memberIds: [
      "ancient-egypt-quiz",
      "ancient-greece-quiz",
      "ancient-rome-quiz",
      "aztec-quiz",
      "byzantine-quiz",
      "feudal-japan-quiz",
      "incan-quiz",
      "mayan-quiz",
      "medieval-life-quiz",
      "mongol-empire-quiz",
      "ottoman-empire-quiz",
      "pharaohs-quiz",
      "prehistoric-quiz",
      "samurai-quiz",
      "viking-quiz",
      "vikings-quiz",
    ],
  },
  {
    id: "war-history-trivia",
    label: "War History Trivia",
    description: "Civil War, WWI, WWII, Cold War, Vietnam and other conflicts.",
    memberIds: [
      "100-years-war-quiz",
      "american-civil-war-quiz",
      "civil-war-quiz",
      "cold-war-quiz",
      "cold-war-spies-quiz",
      "crusades-quiz",
      "eastern-front-quiz",
      "gulf-war-quiz",
      "korean-war-quiz",
      "napoleonic-wars-quiz",
      "pacific-war-quiz",
      "revolutionary-war-quiz",
      "vietnam-war-quiz",
      "wars-quiz",
      "ww1-quiz",
      "ww2-quiz",
    ],
  },
  {
    id: "leaders-trivia",
    label: "Leaders Trivia",
    description: "Presidents, monarchs, prime ministers, emperors and dictators.",
    memberIds: [
      "british-monarchs-quiz",
      "dictators-quiz",
      "emperors-quiz",
      "kings-quiz",
      "knights-quiz",
      "military-leaders-quiz",
      "popes-quiz",
      "prime-ministers-quiz",
      "queens-quiz",
      "us-presidents-mem-quiz",
      "us-presidents-quiz",
      "world-dictators-quiz",
    ],
  },
  {
    id: "disasters-trivia",
    label: "Disasters Trivia",
    description: "Titanic, Hindenburg, Chernobyl, Pompeii and other catastrophes.",
    memberIds: [
      "bhopal-quiz",
      "chernobyl-quiz",
      "fukushima-quiz",
      "hindenburg-quiz",
      "katrina-quiz",
      "mt-st-helens-quiz",
      "pompeii-quiz",
      "san-francisco-quake-quiz",
      "titanic-quiz",
    ],
  },
  {
    id: "intrigue-trivia",
    label: "Intrigue & Crime Trivia",
    description: "Spies, heists, assassinations, outlaws and famous trials.",
    memberIds: [
      "al-capone-quiz",
      "art-heists-quiz",
      "assassinations-quiz",
      "bank-heists-quiz",
      "bonnie-clyde-quiz",
      "cia-quiz",
      "dillinger-quiz",
      "great-train-robbery-quiz",
      "kgb-quiz",
      "los-alamos-quiz",
      "mi6-quiz",
      "nuremberg-trials-quiz",
      "oj-trial-quiz",
      "outlaws-quiz",
      "salem-trials-quiz",
      "unsolved-mysteries-quiz",
    ],
  },
  {
    id: "eras-history-trivia",
    label: "Historical Eras Trivia",
    description: "Renaissance, Enlightenment, Industrial Revolution and more.",
    memberIds: [
      "civil-rights-quiz",
      "enlightenment-quiz",
      "industrial-revolution-quiz",
      "renaissance-quiz",
      "treaties-quiz",
    ],
  },

  // ---------- Brand & corporate trivia ----------
  {
    id: "brands-trivia",
    label: "Brands Trivia",
    description: "Cars, banks, fashion, soda, sneakers and more brand quizzes.",
    memberIds: [
      "airline-brands-quiz",
      "bank-brands-quiz",
      "car-brands-quiz",
      "cereal-brands-quiz",
      "cosmetic-brands-quiz",
      "fashion-brands-quiz",
      "fast-food-brands-quiz",
      "sneaker-brands-quiz",
      "soda-brands-quiz",
      "tech-brands-quiz",
    ],
  },
  {
    id: "tech-history-trivia",
    label: "Tech History Trivia",
    description: "Apple, Microsoft, Google, Amazon and the rise of the giants.",
    memberIds: [
      "ai-history-quiz",
      "amazon-history-quiz",
      "apple-history-quiz",
      "computer-history-quiz",
      "cybersec-quiz",
      "facebook-history-quiz",
      "gaming-history-quiz",
      "google-history-quiz",
      "internet-history-quiz",
      "microsoft-history-quiz",
      "netflix-history-quiz",
      "os-quiz",
      "programming-langs-quiz",
      "silicon-valley-quiz",
      "spacex-history-quiz",
      "tesla-history-quiz",
    ],
  },

  // ---------- Films / TV / pop culture ----------
  {
    id: "auteurs-trivia",
    label: "Auteurs Trivia",
    description: "Hitchcock, Kubrick, Tarantino, Spielberg and other directors.",
    memberIds: [
      "coppola-quiz",
      "hitchcock-quiz",
      "kubrick-quiz",
      "kurosawa-quiz",
      "nolan-quiz",
      "scorsese-quiz",
      "spielberg-quiz",
      "tarantino-quiz",
    ],
  },
  {
    id: "comedians-trivia",
    label: "Comedians Trivia",
    description: "Sandler, Carrey, Brooks, Mr. Bean, Monty Python and more.",
    memberIds: [
      "adam-sandler-quiz",
      "british-comedy-quiz",
      "comedy-central-quiz",
      "jim-carrey-quiz",
      "mel-brooks-quiz",
      "monty-python-quiz",
      "mr-bean-quiz",
      "snl-quiz",
      "stand-up-comedy-quiz",
      "will-ferrell-quiz",
    ],
  },
  {
    id: "film-genres-trivia",
    label: "Film Genres Trivia",
    description: "Horror, sci-fi, Pixar, DC, MCU — genre and franchise film quizzes.",
    memberIds: [
      "dc-comics-films-quiz",
      "horror-films-quiz",
      "marvel-mcu-quiz",
      "movies-trivia",
      "pixar-films-quiz",
      "sci-fi-films-quiz",
    ],
  },
  {
    id: "tv-shows-trivia",
    label: "TV Shows Trivia",
    description: "Friends, Seinfeld, Office, Simpsons, GoT and Breaking Bad.",
    memberIds: [
      "breaking-bad-quiz",
      "family-guy-quiz",
      "friends-show-quiz",
      "got-quiz",
      "lost-show-quiz",
      "office-show-quiz",
      "seinfeld-quiz",
      "simpsons-quiz",
      "south-park-quiz",
      "stranger-things-quiz",
      "tv-dramas-quiz",
      "tv-show-quiz",
      "tv-sitcoms-quiz",
    ],
  },
  {
    id: "anime-trivia",
    label: "Anime Trivia",
    description: "Naruto, Dragon Ball, One Piece, Ghibli and other anime.",
    memberIds: [
      "attack-titan-quiz",
      "bleach-quiz",
      "cowboy-bebop-quiz",
      "dragonball-quiz",
      "evangelion-quiz",
      "my-hero-quiz",
      "naruto-quiz",
      "onepiece-quiz",
      "sailor-moon-quiz",
      "studio-ghibli-quiz",
    ],
  },
  {
    id: "comics-superheroes-trivia",
    label: "Comics & Superheroes Trivia",
    description: "Batman, Superman, X-Men, Spider-Man and the comic-book canon.",
    memberIds: [
      "batman-quiz",
      "comic-villains-quiz",
      "flash-quiz",
      "green-lantern-quiz",
      "spiderman-quiz",
      "superman-quiz",
      "wonder-woman-quiz",
      "xmen-quiz",
    ],
  },
  {
    id: "video-game-trivia",
    label: "Video Game Franchise Trivia",
    description: "Mario, Zelda, Pokemon, Sonic, Final Fantasy and more.",
    memberIds: [
      "final-fantasy-quiz",
      "mario-quiz",
      "metal-gear-quiz",
      "mortal-kombat-quiz",
      "pokemon-quiz",
      "sonic-quiz",
      "streetfighter-quiz",
      "video-game-quiz",
      "zelda-quiz",
    ],
  },
  {
    id: "trivial-pursuit",
    label: "Trivial Pursuit",
    description: "Themed Trivial Pursuit decks — Disney, Star Wars, Potter, Friends.",
    memberIds: [
      "trivial-pursuit-disney-quiz",
      "trivial-pursuit-eighties-quiz",
      "trivial-pursuit-friends-quiz",
      "trivial-pursuit-genus-quiz",
      "trivial-pursuit-nineties-quiz",
      "trivial-pursuit-office-quiz",
      "trivial-pursuit-potter-quiz",
      "trivial-pursuit-starwars-quiz",
      "trivial-pursuit-team-quiz",
    ],
  },
  {
    id: "jackbox-trivia",
    label: "Jackbox Trivia",
    description: "Jackbox party games — Fibbage, Drawful, Quiplash, Telestrations.",
    memberIds: [
      "drawful-2-quiz",
      "drawful-quiz",
      "fibbage-2-quiz",
      "fibbage-3-quiz",
      "fibbage-quiz",
      "fibbage-xl-quiz",
      "jackbox-pack-1-quiz",
      "jackbox-pack-7-quiz",
      "quiplash-quiz",
      "telestrations-after-dark-quiz",
      "telestrations-quiz",
      "telestrations-upside-quiz",
    ],
  },

  // ---------- Mythology, religion, philosophy ----------
  {
    id: "mythology-trivia",
    label: "Mythology Trivia",
    description: "Greek, Norse, Egyptian, Hindu, Celtic and world myth quizzes.",
    memberIds: [
      "celtic-myth-quiz",
      "egyptian-myth-quiz",
      "greek-myth-quiz",
      "hindu-myth-quiz",
      "mythology-quiz",
      "norse-myth-quiz",
    ],
  },
  {
    id: "religion-philosophy-trivia",
    label: "Religion & Philosophy Trivia",
    description: "World religions, philosophers, ethics and symbol systems.",
    memberIds: [
      "buddhism-quiz",
      "eastern-philosophy-quiz",
      "ethics-quiz",
      "philosopher-views-quiz",
      "philosophers-quiz",
      "religions-quiz",
      "religions-symbols-quiz",
      "western-philosophy-quiz",
      "world-religions-quiz",
    ],
  },
  {
    id: "festivals-trivia",
    label: "Festivals & Holidays Trivia",
    description: "Christmas, Halloween, Easter, Diwali, Hanukkah and more.",
    memberIds: [
      "chinese-new-year-quiz",
      "christmas-quiz",
      "diwali-quiz",
      "easter-quiz",
      "festivals-quiz",
      "halloween-quiz",
      "hanukkah-quiz",
      "mardi-gras-quiz",
      "new-year-quiz",
      "thanksgiving-quiz",
      "valentines-quiz",
    ],
  },

  // ---------- Science ----------
  {
    id: "natural-sciences-trivia",
    label: "Natural Sciences Trivia",
    description: "Physics, chemistry, biology, astronomy, geology and meteorology.",
    memberIds: [
      "anatomy-quiz",
      "astronomy-quiz",
      "biology-quiz",
      "botany-quiz",
      "chemistry-lab-quiz",
      "chemistry-quiz",
      "geology-quiz",
      "marine-bio-quiz",
      "meteorology-quiz",
      "physics-quiz",
      "space-quiz",
      "zoology-quiz",
    ],
  },
  {
    id: "discoveries-trivia",
    label: "Discoveries Trivia",
    description: "Medical, scientific and inventive breakthroughs.",
    memberIds: [
      "communication-inventions-quiz",
      "food-inventions-quiz",
      "inventors-quiz",
      "inventors-tools-quiz",
      "medical-discoveries-quiz",
      "physics-discoveries-quiz",
      "space-discoveries-quiz",
      "transport-inventions-quiz",
      "weapon-inventions-quiz",
    ],
  },
  {
    id: "scientists-trivia",
    label: "Scientists Trivia",
    description: "Famous scientists, mathematicians and explorers.",
    memberIds: [
      "explorers-quiz",
      "mathematicians-quiz",
      "nasa-astronauts-quiz",
      "scientists-quiz",
    ],
  },
  {
    id: "math-logic-trivia",
    label: "Math & Logic Trivia",
    description: "Mental math, geometry, algebra, statistics and probability.",
    memberIds: [
      "algebra-quiz",
      "geometry-quiz",
      "logic-puzzles-quiz",
      "mental-math-quiz",
      "number-theory-quiz",
      "probability-quiz",
      "puzzle-mind-quiz",
      "statistics-quiz",
    ],
  },

  // ---------- Nature & animals ----------
  {
    id: "animal-care-trivia",
    label: "Animal Care Trivia",
    description: "Cats, dogs, birds, horses, reptiles — care quizzes for pet keepers.",
    memberIds: [
      "bird-care-quiz",
      "cat-care-quiz",
      "cats-breeds-quiz",
      "dog-care-quiz",
      "dogs-breeds-quiz",
      "horse-care-quiz",
      "reptile-care-quiz",
    ],
  },
  {
    id: "wildlife-trivia",
    label: "Wildlife Trivia",
    description: "Animals, mammals, birds, fish, reptiles, insects and primates.",
    memberIds: [
      "animal-quiz",
      "animal-tracks-quiz",
      "aquarium-quiz",
      "bear-species-quiz",
      "bird-songs-quiz",
      "birds-quiz",
      "birds-world-quiz",
      "endangered-species-quiz",
      "farm-animal-quiz",
      "fish-quiz",
      "insects-quiz",
      "insects-world-quiz",
      "mammals-quiz",
      "primates-quiz",
      "reptiles-quiz",
      "reptiles-world-quiz",
      "snakes-quiz",
      "spiders-quiz",
      "whales-dolphins-quiz",
      "wild-cats-quiz",
      "wildlife-quiz",
    ],
  },
  {
    id: "nature-trivia",
    label: "Nature Trivia",
    description: "Weather, oceans, rivers, deserts, dinosaurs, plants and trees.",
    memberIds: [
      "deep-sea-quiz",
      "desert-quiz",
      "deserts-quiz",
      "desert-trek-quiz",
      "dinosaurs-quiz",
      "fruits-quiz",
      "gardening-quiz",
      "gemstones-quiz",
      "herbs-quiz",
      "plants-quiz",
      "polar-quiz",
      "sakura-quiz",
      "snacks-quiz",
      "spices-quiz",
      "survival-quiz",
      "trees-quiz",
      "vegetables-quiz",
      "volcano-quiz",
      "weather-quiz",
    ],
  },

  // ---------- Language ----------
  {
    id: "wordplay-trivia",
    label: "Wordplay Trivia",
    description: "Synonyms, idioms, palindromes, spoonerisms and other wordplay.",
    memberIds: [
      "alliteration-quiz",
      "antonym-quiz",
      "capitonym-quiz",
      "cliche-quiz",
      "eponym-quiz",
      "heteronym-quiz",
      "homonym-quiz",
      "hyperbole-quiz",
      "idiom-quiz",
      "malapropism-quiz",
      "metaphor-quiz",
      "mondegreen-quiz",
      "neologism-quiz",
      "onomatopoeia-quiz",
      "oxymoron-quiz",
      "palindrome-quiz",
      "portmanteau-quiz",
      "proverb-quiz",
      "rhyme-quiz",
      "simile-quiz",
      "spoonerism-quiz",
      "synonym-quiz",
      "tautology-quiz",
      "toponym-quiz",
    ],
  },
  {
    id: "grammar-trivia",
    label: "Grammar Trivia",
    description: "Parts of speech, tenses, plurals, prefixes, suffixes and more.",
    memberIds: [
      "abbreviation-quiz",
      "acronym-define-quiz",
      "acronym-quiz",
      "adjective-quiz",
      "adverb-quiz",
      "article-quiz",
      "collocation-quiz",
      "comparative-quiz",
      "consonant-quiz",
      "contraction-quiz",
      "double-letter-quiz",
      "hyphen-quiz",
      "noun-quiz",
      "plurals-quiz",
      "prefix-quiz",
      "preposition-quiz",
      "pronoun-quiz",
      "silent-e-quiz",
      "silent-letter-quiz",
      "spelling-quiz",
      "suffix-quiz",
      "superlative-quiz",
      "tenses-quiz",
      "verb-quiz",
      "vowel-quiz",
      "word-roots-quiz",
    ],
  },
  {
    id: "literature-trivia",
    label: "Literature Trivia",
    description: "Classic novels, sci-fi, fantasy, mystery and Shakespeare.",
    memberIds: [
      "american-lit-quiz",
      "british-lit-quiz",
      "classic-novels-quiz",
      "fantasy-novels-quiz",
      "literature-genres-quiz",
      "mystery-novels-quiz",
      "russian-lit-quiz",
      "sci-fi-novels-quiz",
      "shakespeare-quiz",
    ],
  },

  // ---------- Art ----------
  {
    id: "visual-art-trivia",
    label: "Visual Art Trivia",
    description: "Painters, sculpture, art movements, architecture and photography.",
    memberIds: [
      "architecture-quiz",
      "art-movements-quiz",
      "fashion-eras-quiz",
      "hairstyles-quiz",
      "modern-art-quiz",
      "painters-quiz",
      "painting-techniques-quiz",
      "photography-quiz",
      "pottery-quiz",
      "sculpture-quiz",
      "street-art-quiz",
    ],
  },
  {
    id: "performance-arts-trivia",
    label: "Performance Arts Trivia",
    description: "Ballet, opera, Broadway, dance styles and instruments.",
    memberIds: [
      "ballet-quiz",
      "broadway-quiz",
      "dance-quiz",
      "dance-styles-quiz",
      "opera-quiz",
    ],
  },

  // ---------- Vehicles & transit ----------
  {
    id: "vehicles-trivia",
    label: "Vehicles Trivia",
    description: "Cars, trucks, ships, trains, planes and submarines.",
    memberIds: [
      "aircraft-quiz",
      "bullet-trains-quiz",
      "cars-history-quiz",
      "cruise-ships-quiz",
      "helicopters-quiz",
      "motorcycles-quiz",
      "muscle-cars-quiz",
      "school-buses-quiz",
      "ships-quiz",
      "space-vehicles-quiz",
      "submarines-quiz",
      "subways-quiz",
      "supercars-quiz",
      "trains-quiz",
      "transportation-quiz",
      "trucks-history-quiz",
      "vintage-cars-quiz",
    ],
  },

  // ---------- Chess (non-trivia) variants ----------
  {
    id: "chess-variants",
    label: "Chess Variants",
    description: "Antichess, atomic, crazyhouse, horde, three-check and more.",
    memberIds: [
      "antichess",
      "atomic-chess",
      "bughouse",
      "bughouse-puzzle",
      "chess960",
      "chess-back-rank",
      "chess-endgame-kqk",
      "chess-endgame-kr",
      "chess-puzzle-fork",
      "chess-tactics",
      "crazyhouse",
      "crazyhouse-chess",
      "crazyhouse-puzzle",
      "fischer-crazyhouse",
      "fog-of-war-chess",
      "horde-chess",
      "king-of-hill-chess",
      "knightmate-chess",
      "losing-chess",
      "racing-kings",
      "racing-kings-chess",
      "three-check",
      "three-check-chess",
      "xiangqi-blind",
      "xiangqi-chess",
    ],
  },
  {
    id: "shogi",
    label: "Shogi & Variants",
    description: "Japanese chess from mini to chu, tori, kyoto and more.",
    memberIds: [
      "animal-shogi",
      "annan-shogi",
      "chu-shogi-board",
      "dai-shogi",
      "heian-shogi",
      "kyoto-shogi",
      "micro-shogi",
      "micro-shogi-4",
      "mini-shogi",
      "mini-shogi-5",
      "minishogi-5x5",
      "shogi",
      "tori-shogi",
      "wa-shogi",
    ],
  },
  {
    id: "shogi-trivia",
    label: "Shogi Trivia",
    description: "Quizzes for every shogi variant — annan, chu, tori, wa and more.",
    memberIds: [
      "annan-shogi-quiz",
      "chu-shogi-board-quiz",
      "chu-shogi-quiz",
      "hasami-shogi-quiz",
      "heian-shogi-quiz",
      "kyoto-shogi-quiz",
      "micro-shogi-quiz",
      "mini-shogi-quiz",
      "shogi-quiz",
      "tori-shogi-quiz",
      "wa-shogi-quiz",
    ],
  },
  {
    id: "go-variants",
    label: "Go & Variants",
    description: "Go on 9×9, 13×13, 19×19 boards plus capture-go and ponnuki-go.",
    memberIds: [
      "go-13-quiz",
      "go-13x13",
      "go-19-quiz",
      "go-19x19",
      "go-9",
      "go-9-quiz",
      "go-9x9",
      "baduk-board-quiz",
      "baduk-quiz",
      "capture-go-quiz",
      "ponnuki-go-quiz",
      "tozan-go-quiz",
    ],
  },
  {
    id: "gomoku-renju",
    label: "Gomoku & Renju",
    description: "Five-in-a-row variants — gomoku, renju, ninuki-renju and pente.",
    memberIds: [
      "gomoku",
      "gomoku-classic",
      "gomoku-mini",
      "gomoku-pro",
      "gomoku-tactic",
      "ninuki-renju",
      "ninuki-renju-quiz",
      "pente",
      "pente-capture",
      "renju",
      "renju-game",
      "renju-quiz",
    ],
  },
  {
    id: "tic-tac-toe",
    label: "Tic-Tac-Toe",
    description: "Classic to 4×4, 3D, blitz and toroidal tic-tac-toe.",
    memberIds: [
      "3d-tic-tac-toe-3",
      "3d-tic-tac-toe-3x3x3",
      "tic-tac-toe",
      "tic-tac-toe-3-in-row",
      "tic-tac-toe-3x3-classic",
      "tic-tac-toe-4x4",
      "tic-tac-toe-4x4-cl",
      "tic-tac-toe-blitz",
      "tic-tac-toe-cards",
      "tic-tac-toe-corners-win",
      "tic-tac-toe-large",
      "tic-tac-toe-poker",
      "tic-tac-toe-toroidal",
      "tictactoe-3d",
    ],
  },
  {
    id: "reversi-othello",
    label: "Reversi / Othello",
    description: "Flip-disc strategy classic in every rule variation.",
    memberIds: [
      "reversi",
      "reversi-anti-quiz",
      "reversi-random-quiz",
      "reversi-random-start",
      "reversi-timed",
    ],
  },
  {
    id: "checkers-draughts",
    label: "Checkers & Draughts",
    description: "Checkers, dameo, frisian, international and breakthrough.",
    memberIds: [
      "breakthrough",
      "breakthrough-checkers-quiz",
      "checkers",
      "dameo",
      "dameo-freeling",
      "dameo-pos",
      "frisian-draughts",
      "international-draughts",
      "losing-checkers",
      "russian-checkers-flying",
      "suicide-checkers-quiz",
    ],
  },
  {
    id: "tafl-games",
    label: "Tafl Games",
    description: "Hnefatafl, brandub, tablut and other Norse/Celtic siege games.",
    memberIds: [
      "brandub",
      "brandubh",
      "hnefatafl",
      "hnefatafl-mini",
      "magpie-tafl",
      "sea-battle-tafl",
      "tablut",
    ],
  },

  // ---------- Big publisher boardgame families ----------
  {
    id: "carcassonne",
    label: "Carcassonne",
    description: "Tile-laying medieval landscapes — base game and every expansion.",
    memberIds: [
      "carcassonne-abbey-mayor",
      "carcassonne-amazonas",
      "carcassonne-base",
      "carcassonne-big-top",
      "carcassonne-german-castles",
      "carcassonne-hills-sheep",
      "carcassonne-inns-cathedrals",
      "carcassonne-princess-dragon",
      "carcassonne-river",
      "carcassonne-safari",
      "carcassonne-south-seas",
      "carcassonne-star-wars",
      "carcassonne-tower",
      "carcassonne-tower-build",
      "carcassonne-traders-builders",
    ],
  },
  {
    id: "seven-wonders",
    label: "7 Wonders",
    description: "Card-drafting civilization-builder and every official expansion.",
    memberIds: [
      "seven-wonders-architects-draft",
      "seven-wonders-armada",
      "seven-wonders-babel",
      "seven-wonders-cities",
      "seven-wonders-draft",
      "seven-wonders-duel-pyramid",
      "seven-wonders-edifice",
      "seven-wonders-leaders",
      "seven-wonders-pyramid-extra",
    ],
  },
  {
    id: "splendor",
    label: "Splendor",
    description: "Gem trading and tableau building across all themes.",
    memberIds: [
      "splendor-cities",
      "splendor-dune",
      "splendor-gems",
      "splendor-marvel",
      "splendor-merchant",
      "splendor-trade-routes",
    ],
  },
  {
    id: "wingspan",
    label: "Wingspan",
    description: "Engine-building bird sanctuary — full lineup of expansions.",
    memberIds: [
      "wingspan-asia-flock",
      "wingspan-asia-rw",
      "wingspan-aviary",
      "wingspan-dice-game",
      "wingspan-dice-roll",
      "wingspan-european-draft",
      "wingspan-nesting",
      "wingspan-oceania-draft",
    ],
  },
  {
    id: "kingdomino-family",
    label: "Kingdomino Family",
    description: "Domino-style kingdom-building — Kingdomino and Queendomino.",
    memberIds: [
      "kingdomino",
      "kingdomino-base",
      "kingdomino-duel",
      "kingdomino-giants",
      "kingdomino-origins",
      "queendomino",
      "queendomino-base",
      "queendomino-tax",
    ],
  },
  {
    id: "dominion-deck",
    label: "Dominion",
    description: "Original deckbuilder across Adventures, Intrigue, Seaside and more.",
    memberIds: [
      "dominion-adventures",
      "dominion-deck",
      "dominion-intrigue",
      "dominion-prosperity",
      "dominion-seaside",
    ],
  },
  {
    id: "patchwork-family",
    label: "Patchwork",
    description: "Quilting puzzle — base game, doodle, express and quilt versions.",
    memberIds: [
      "patchwork",
      "patchwork-base",
      "patchwork-doodle",
      "patchwork-doodle-quilt",
      "patchwork-express-game",
    ],
  },
  {
    id: "trek-12",
    label: "Trek 12",
    description: "Roll-and-write mountain climbing — Himalaya, jungle and arctic.",
    memberIds: [
      "trek-12-arctic",
      "trek-12-himalaya",
      "trek-12-jungle",
    ],
  },
  {
    id: "cartographers",
    label: "Cartographers",
    description: "Map-drawing roll-and-write — every Cartographers edition.",
    memberIds: [
      "cartographer-heroes",
      "cartographers-base",
      "cartographers-desert",
      "cartographers-heroes",
      "cartographers-monsters",
      "cartographers-neque",
      "cartographers-roll-player",
      "cartographers-tundra",
    ],
  },
  {
    id: "magic-maze",
    label: "Magic Maze",
    description: "Real-time silent cooperative heist game and expansions.",
    memberIds: [
      "magic-maze-coop",
      "magic-maze-max-security",
      "magic-maze-pawn",
    ],
  },
  {
    id: "forbidden-coop",
    label: "Forbidden Series",
    description: "Forbidden Island, Desert, Jungle and Sky cooperative games.",
    memberIds: [
      "forbidden-desert-coop",
      "forbidden-island-coop",
      "forbidden-jungle-coop",
      "forbidden-sky-coop",
    ],
  },
  {
    id: "hanabi-family",
    label: "Hanabi",
    description: "Cooperative fireworks card game and its expansions.",
    memberIds: [
      "hanabi",
      "hanabi-avenue-bonus",
      "hanabi-deluxe-coop",
      "hanabi-extra-coop",
    ],
  },
  {
    id: "spirit-island-family",
    label: "Spirit Island",
    description: "Cooperative anti-colonial spirit defense — every expansion.",
    memberIds: [
      "spirit-island-coop",
      "spirit-island-jagged",
      "spirit-island-nature",
    ],
  },
  {
    id: "tokaido-family",
    label: "Tokaido",
    description: "Stroll across Edo Japan — Tokaido and Crossroads expansion.",
    memberIds: [
      "tokaido",
      "tokaido-base",
      "tokaido-crossroads",
    ],
  },
  {
    id: "munchkin-family",
    label: "Munchkin",
    description: "Dungeon-romp parody card game — base, mini and zombies.",
    memberIds: [
      "munchkin-base-quiz",
      "munchkin-mini",
      "munchkin-zombies-quiz",
    ],
  },
  {
    id: "exploding-kittens",
    label: "Exploding Kittens",
    description: "The party card game and its kittens, minions and streakers.",
    memberIds: [
      "exploding-kittens-quiz",
      "exploding-minions-quiz",
      "imploding-kittens-quiz",
      "streaking-kittens-quiz",
    ],
  },
  {
    id: "sushi-go",
    label: "Sushi Go",
    description: "Conveyor-belt sushi drafting — Go, Deluxe and Party.",
    memberIds: [
      "sushi-conveyor",
      "sushi-go-conveyor",
      "sushi-go-deluxe",
      "sushi-go-party-menu",
      "sushi-roll-toss",
    ],
  },
  {
    id: "wonderful-world",
    label: "It's a Wonderful World",
    description: "Drafting empire-builder — base game, war and corruption packs.",
    memberIds: [
      "wonder-pack-extra",
      "wonderful-world-corruption",
      "wonderful-world-draft",
      "wonderful-world-war",
    ],
  },

  // ---------- Cards: trick-taking, rummy, shedding ----------
  {
    id: "rummy-family",
    label: "Rummy",
    description: "Gin, Continental, Contract, 500, Pinochle Rummy and more.",
    memberIds: [
      "basic-rummy",
      "continental-rummy",
      "contract-rummy",
      "deals-rummy-r",
      "gin-rummy",
      "kalooki",
      "knock-rummy-r",
      "mini-rummy",
      "persian-rummy-r",
      "pinochle-rummy-r",
      "points-rummy-r",
      "pool-rummy-r",
      "progressive-rummy-r",
      "quick-rummy-r",
      "rummy-500",
      "rummy-500-classic-r",
      "rummy-royale-r",
      "rummy-tiles-r",
      "shed-rummy-r",
      "tonk",
      "tonk-r",
      "wild-card-rummy-r",
    ],
  },
  {
    id: "canasta-family",
    label: "Canasta",
    description: "Caliente, Junior, Mexicana and Speed canasta variants.",
    memberIds: [
      "canasta",
      "canasta-caliente-r",
      "canasta-junior-r",
      "canasta-mexicana-r",
      "canasta-speed-r",
    ],
  },
  {
    id: "cribbage-family",
    label: "Cribbage",
    description: "Standard and themed cribbage — skunk, lurch, shotgun, square.",
    memberIds: [
      "cribbage-crash",
      "cribbage-double-skunk",
      "cribbage-lurch",
      "cribbage-mini",
      "cribbage-muggins-var",
      "cribbage-shotgun",
      "cribbage-skunk",
      "cribbage-skunked-rubber",
      "cribbage-square",
      "cribbage-squares-soli",
      "seven-card-cribbage",
      "speed-cribbage",
    ],
  },
  {
    id: "napoleon-family",
    label: "Napoleon Card Games",
    description: "Napoleon and St. Helena variants — historical trick games.",
    memberIds: [
      "napoleon-at-saint-helena",
      "napoleon-at-st-helena",
      "napoleon-card",
      "napoleon-nap",
      "napoleons-shoulder",
      "napoleons-square",
      "napoleon-st-helena",
      "napoleons-tomb",
    ],
  },
  {
    id: "uno-family",
    label: "Uno & Skip-Bo",
    description: "Uno-likes, Skip-Bo and the family of shedding card games.",
    memberIds: [
      "skip-bo",
      "skip-bo-shed",
      "uno-attack-quiz",
      "uno-flip-quiz",
      "uno-like",
      "uno-stacko",
    ],
  },
  {
    id: "spit-family",
    label: "Spit & Speed",
    description: "Spit, Speed, Slapjack and Egyptian Ratscrew — fast slap games.",
    memberIds: [
      "egyptian-rat-screw",
      "egyptian-ratscrew",
      "slapjack",
      "speed",
      "speed-pairs",
      "speed-snap",
      "spit",
      "spit-in-ocean",
      "spit-in-the-ocean",
      "spit-ocean-cas",
      "spit-ocean-cl",
      "spit-ocean-wild",
      "spit-speed",
    ],
  },

  // ---------- Casino specialty card games ----------
  {
    id: "baccarat-family",
    label: "Baccarat",
    description: "Punto Banco, Mini Baccarat, Chemin de Fer, EZ and Banque.",
    memberIds: [
      "baccarat",
      "banque-cas",
      "chemin-de-fer-cas",
      "ez-baccarat-cas",
      "mini-baccarat-cas",
    ],
  },
  {
    id: "video-poker-family",
    label: "Video Poker",
    description: "Jacks or Better, Deuces Wild, multi-hand and bonus video poker.",
    memberIds: [
      "all-american-vp-cas",
      "deuces",
      "deuces-wild",
      "deuces-wild-draw",
      "deuces-wild-vp",
      "double-double-bonus-cas",
      "jacks-or-better",
      "joker-poker-cas",
      "loose-deuces-wild",
      "multi-hand-vp-five",
      "multi-hand-vp-ten",
      "multi-hand-vp-three",
      "super-times-pay-cas",
      "tens-or-better-cas",
      "video-poker",
      "video-poker-jacks",
    ],
  },
  {
    id: "roulette-family",
    label: "Roulette",
    description: "American, European, mini and card-based roulette variants.",
    memberIds: [
      "card-roulette",
      "diceland-roulette",
      "dice-roulette",
      "mini-roulette",
      "poker-roulette",
      "red-roulette",
      "roulette",
    ],
  },
  {
    id: "casino-table-poker",
    label: "Casino Poker Tables",
    description: "Three-Card, Four-Card, Mississippi, Let It Ride and other table pokers.",
    memberIds: [
      "caribbean-stud",
      "flop-poker-cas",
      "flush-poker-cas",
      "four-card-poker",
      "four-card-poker-cas",
      "let-it-ride",
      "let-it-ride-cas",
      "mississippi-stud",
      "mississippi-stud-cas",
      "red-dog",
      "red-dog-card",
      "red-dog-cas",
      "red-dog-progressive-cas",
      "three-card-poker",
      "three-card-poker-cas",
      "ultimate-texas-cas",
    ],
  },
  {
    id: "asian-casino",
    label: "Asian Casino",
    description: "Pai Gow, Andar Bahar, Dragon Tiger, Teen Patti and Pusoy.",
    memberIds: [
      "andar-bahar-cas",
      "dragon-tiger-cas",
      "fortune-pai-gow-cas",
      "pai-gow-poker",
      "pai-gow-tiles-cas",
      "pusoy-cas",
      "pusoy-poker-quiz",
      "teen-patti-cas",
    ],
  },

  // ---------- Asian card families ----------
  {
    id: "hanafuda-family",
    label: "Hanafuda Games",
    description: "Koi-Koi and traditional Japanese flower-card games.",
    memberIds: [
      "hanafuda-koi-koi",
      "hawaiian-hanafuda-quiz",
      "kabu-hanafuda-quiz",
      "koi-koi-quiz",
      "nabeshima-hanafuda-quiz",
    ],
  },
  {
    id: "karuta-family",
    label: "Karuta & Menko",
    description: "Iroha, Hyakunin Isshu, Obake, Tensho and other Japanese cards.",
    memberIds: [
      "hyakunin-isshu-quiz",
      "iroha-karuta-quiz",
      "kyogi-karuta-quiz",
      "menko-quiz",
      "obake-karuta-quiz",
      "tensho-karuta-quiz",
      "uta-garuta-quiz",
    ],
  },
  {
    id: "asian-card-trivia",
    label: "Asian Card Trivia",
    description: "Sheng Ji, Tien Len, Go-Stop, Hwatu, Sutda and friends.",
    memberIds: [
      "dou-di-zhu-quiz",
      "dou-dizhu-quiz",
      "go-stop-quiz",
      "hwatu-quiz",
      "japanese-snap-quiz",
      "kabufuda-quiz",
      "mushifuda-quiz",
      "seotda-quiz",
      "sheng-ji-quiz",
      "sutda-quiz",
      "tehonbiki-quiz",
      "tien-len-quiz",
      "tongits-quiz",
      "zheng-shangyou-quiz",
    ],
  },
  {
    id: "mahjong-trivia",
    label: "Mahjong Trivia",
    description: "Cantonese, Riichi, Singapore and other regional mahjong quizzes.",
    memberIds: [
      "cantonese-mahjong-quiz",
      "mcr-mahjong-quiz",
      "riichi-mahjong-quiz",
      "singapore-mahjong-quiz",
      "taiwanese-mahjong-quiz",
    ],
  },

  // ---------- Solitaire (more) ----------
  {
    id: "more-solitaires",
    label: "Other Solitaires",
    description: "Accordion, Crescent, Calculation, Frog, Sultan and more patiences.",
    memberIds: [
      "accordion",
      "accordion-solitaire",
      "addiction-soli",
      "addiction-solitaire",
      "calculation-solitaire",
      "corners-solitaire",
      "crescent-solitaire",
      "decade-solitaire",
      "deuces-soli",
      "deuces-solitaire",
      "fortress-solitaire",
      "frog-solitaire",
      "golf-solitaire",
      "hopscotch-solitaire",
      "rainbow-solitaire",
      "sultan-solitaire",
      "tower-london-soli",
      "tower-of-london",
    ],
  },
  {
    id: "peg-solitaire",
    label: "Peg Solitaire",
    description: "European peg, card-version and plus board peg solitaires.",
    memberIds: [
      "european-peg-solitaire",
      "peg-solitaire",
      "peg-solitaire-card-version",
      "peg-solitaire-plus",
    ],
  },

  // ---------- Backgammon-likes already covered. Connect/board strategy more ----------
  {
    id: "abalone-family",
    label: "Abalone",
    description: "Push-the-marble strategy classic and trivia.",
    memberIds: [
      "abalone",
      "abalone-quiz",
    ],
  },
  {
    id: "halma-family",
    label: "Halma",
    description: "Halma and quiz on hopping piece-jumping classics.",
    memberIds: [
      "halma",
      "halma-quiz",
    ],
  },

  // ---------- Word puzzles ----------
  {
    id: "wordle-family",
    label: "Wordle Variants",
    description: "Wordle, Dordle, Quordle, Squardle, Nerdle and friends.",
    memberIds: [
      "absurdle-mini",
      "crosswordle-mini",
      "dordle-mini",
      "nerdle-equation",
      "quordle",
      "squardle-mini",
      "wordle-mini",
    ],
  },
  {
    id: "word-puzzles",
    label: "Word Puzzles",
    description: "Crosswords, anagrams, ladders, hunts and word grids.",
    memberIds: [
      "anagram",
      "anagram-magic",
      "anagram-pair",
      "bananagrams",
      "boggle",
      "boggle-4x4",
      "boggle-5x5",
      "boggle-pro",
      "crossword-mini",
      "crossword-mini-3x3",
      "crossword-pro",
      "ghost-word-spell",
      "mini-crossword",
      "panagram",
      "spelling-bee",
      "spelltower-mini",
      "word-association",
      "word-bingo-mini",
      "word-chain",
      "word-chains",
      "word-construction",
      "word-cookies",
      "word-flower",
      "word-guess",
      "word-hunt",
      "word-hunt-mini",
      "word-ladder",
      "word-ladder-mini",
      "word-pyramid",
      "word-scramble",
      "word-search",
      "word-search-mini",
      "word-wheel",
      "wordament-mini",
      "wordscapes-mini",
    ],
  },
  {
    id: "wordlikes-extras",
    label: "Wordle-likes Extras",
    description: "Connections, Globle, Worldle, semantic and contextual word puzzles.",
    memberIds: [
      "connections-clone",
      "connections-mini",
      "globle-country",
      "worldle-country",
    ],
  },

  // ---------- Match-3 / falling-block / merge ----------
  {
    id: "match-3-arcade",
    label: "Match-3 Arcade",
    description: "Bejeweled, Candy Crush, Jewel Quest and other tile-matchers.",
    memberIds: [
      "bejeweled-blitz",
      "bejeweled-classic-mini",
      "bejeweled-stars-mini",
      "bejeweled-twist",
      "candy-crush-mini",
      "candy-soda-mini",
      "hex-match-3",
      "jewel-quest-arcade",
      "match-3",
    ],
  },
  {
    id: "falling-block",
    label: "Falling Block Puzzles",
    description: "Tetris, Puyo Puyo, Columns, Lumines and Magical Drop variants.",
    memberIds: [
      "columns",
      "columns-mini",
      "dr-mario-like",
      "lumines-mini",
      "magical-drop-mini",
      "puyo-fever-mini",
      "puyo-pop-like",
      "puyo-sun-mini",
      "puyo-tsu-mini",
      "super-columns-mini",
      "tetris-like",
    ],
  },
  {
    id: "samegame-family",
    label: "SameGame & Clickomania",
    description: "Tap matching coloured groups to clear the board.",
    memberIds: [
      "clickomania-mini",
      "samegame-mini",
    ],
  },
  {
    id: "merge-puzzles",
    label: "Merge & 2048",
    description: "2048, Threes, Triple Town and other merging puzzles.",
    memberIds: [
      "game-1024",
      "game-2048",
      "merge-dragons-mini",
      "merge-mansion-mini",
      "money-idol-exchanger",
      "money-idol-mini",
      "threes-puzzle",
      "triple-town-merge",
      "triple-town-mini",
    ],
  },

  // ---------- Arcade ----------
  {
    id: "endless-runner",
    label: "Endless Runners",
    description: "Canabalt, doodle-jump, icy tower, helicopters and side-scrollers.",
    memberIds: [
      "3d-tunnel-runner",
      "bat-flyer",
      "canabalt-mini",
      "cave-flyer",
      "cave-runner",
      "doodle-jump-arcade",
      "doodle-jump-like",
      "endless-runner",
      "flappy-bird-like",
      "helicopter-flyer",
      "helicopter-game",
      "icy-tower-arcade",
      "ninja-wall-arcade",
      "ninja-wall-mini",
      "paper-plane-mini",
      "pixel-runner",
      "side-scroll-runner",
      "tap-runner",
      "tunnel-runner",
      "ufo-flyer",
      "wall-jumper",
    ],
  },
  {
    id: "tap-arcades",
    label: "Tap Arcades",
    description: "Reaction-tap minigames spanning fruit, fireworks and beyond.",
    memberIds: [
      "acorn-tap",
      "apple-tap",
      "baseball-tap",
      "bird-tap",
      "bowling-pin-tap",
      "bpm-tap",
      "candy-tap",
      "eraser-tap",
      "firework-tap",
      "golf-ball-tap",
      "hammer-tap",
      "honey-tap",
      "lightning-tap",
      "lime-tap",
      "mango-tap",
      "meteor-tap",
      "moon-tap",
      "morse-tap",
      "nail-tap",
      "octopus-tap",
      "orange-tap",
      "puppy-tap",
      "rhythm-tap",
      "snowflake-tap",
      "soccer-ball-tap",
      "spark-tap",
      "spike-tap",
      "taffy-tap",
      "tea-time-tap",
      "tempura-tap",
      "tennis-ball-tap",
      "train-tap",
      "truck-tap",
      "wave-tap",
    ],
  },
  {
    id: "catch-arcades",
    label: "Catch Arcades",
    description: "Falling-object catch games — eggs, frogs, comets and more.",
    memberIds: [
      "alphabet-catch",
      "caramel-catch",
      "caterpillar-catch",
      "comet-catch",
      "confetti-catch",
      "crab-catch",
      "croissant-catch",
      "cucumber-catch",
      "egg-catch",
      "egg-catcher",
      "endless-catch",
      "falling-catcher",
      "frog-catcher",
    ],
  },
  {
    id: "tower-stacker",
    label: "Tower Stacker",
    description: "Stack-tap towers, hanoi, builders and stacker arcades.",
    memberIds: [
      "card-tower-fall",
      "card-tower-stack",
      "stack-tower",
      "tower-builder",
      "tower-of-hanoi",
      "tower-of-hanoi-7",
      "tower-of-hanoi-mini",
      "tower-stacker",
      "tower-stacker-mini",
    ],
  },
  {
    id: "maze-puzzles",
    label: "Maze Puzzles",
    description: "Mazes from classic to laser, gravity, ghost and tilt mazes.",
    memberIds: [
      "classic-maze",
      "colored-tile-maze",
      "fog-maze",
      "ghost-maze",
      "gravity-maze",
      "ice-slide-maze",
      "key-maze",
      "laser-maze",
      "maze-chase",
      "mirror-maze",
      "number-maze",
      "perplexus-maze",
      "teleport-maze",
      "tilt-maze",
    ],
  },
  {
    id: "memory-arcades",
    label: "Memory Arcades",
    description: "Pairs, Simon, image and number memory recall games.",
    memberIds: [
      "animals-memory",
      "disney-memory",
      "flags-memory",
      "image-memory",
      "map-memory",
      "memory-match",
      "memory-pairs-kids",
      "monet-memory",
      "national-flags-memory",
      "number-memory",
      "presidents-memory",
      "simon",
      "simon-air",
      "simon-pattern",
      "simon-swipe",
      "simple-simon",
      "tray-memory",
      "verbal-memory",
      "visual-memory-grid",
    ],
  },
  {
    id: "cellular-automata",
    label: "Cellular Automata",
    description: "Conway's Life, Brian's Brain, 1D life and Langton's ant.",
    memberIds: [
      "brain-of-brian",
      "game-of-life-classic",
      "game-of-life-conway",
      "game-of-life-race",
      "langtons-ant-mini",
      "life-1d",
    ],
  },

  // ---------- Number / math puzzles ----------
  {
    id: "number-puzzles",
    label: "Number Puzzles",
    description: "Bonds, chains, ordering, primes and number ladders.",
    memberIds: [
      "countdown-321",
      "find-composite",
      "find-prime",
      "math-bingo",
      "math-challenge",
      "number-bonds",
      "number-chain",
      "number-guesser",
      "number-link-mini",
      "number-order",
      "number-recall",
      "prime-climb",
      "prime-factor",
    ],
  },

  // ---------- Dice grouped families ----------
  {
    id: "dice-bowling",
    label: "Dice Bowling",
    description: "Tenpin, ninepin, candlepin, duckpin and other dice bowling.",
    memberIds: [
      "dice-bowl",
      "dice-bowling",
      "dice-candlepin",
      "dice-duckpin",
      "dice-five-pin",
      "dice-kegeln",
      "dice-ninepin-bowl",
      "dice-skittles",
      "dice-tenpin-bowl",
    ],
  },
  {
    id: "dice-darts",
    label: "Dice Darts",
    description: "301, 701, killer, halve-it and around-the-clock dice darts.",
    memberIds: [
      "dice-301",
      "dice-301-darts",
      "dice-701",
      "dice-around-clock",
      "dice-cricket-darts",
      "dice-darts",
      "dice-fat-boy-darts",
      "dice-gulf-darts",
      "dice-halve-it",
      "dice-killer-darts",
      "dice-shanghai-darts",
    ],
  },
  {
    id: "dice-team-sports",
    label: "Dice Team Sports",
    description: "Dice baseball, basketball, football, hockey and soccer simulators.",
    memberIds: [
      "dice-apba-basketball",
      "dice-baseball",
      "dice-baseball-highlights",
      "dice-basketball",
      "dice-fantasy-baseball-draft",
      "dice-fantasy-basketball-draft",
      "dice-fantasy-football-draft",
      "dice-football",
      "dice-gridiron",
      "dice-hockey",
      "dice-replay-baseball-detail",
      "dice-soccer",
      "dice-strat-arena",
      "dice-strat-basketball",
      "dice-strat-football",
      "dice-strat-hockey",
    ],
  },
  {
    id: "dice-target-sports",
    label: "Dice Target Sports",
    description: "Bocce, curling, petanque, mölkky, kubb and other lawn-target dice.",
    memberIds: [
      "dice-bocce",
      "dice-boccia",
      "dice-curling-stones",
      "dice-eisstock",
      "dice-kaisa",
      "dice-kanjam",
      "dice-kubb",
      "dice-molkky",
      "dice-novuss",
      "dice-petanque",
      "dice-russian-pyramid",
      "dice-sjoelbak",
      "dice-washer-toss",
    ],
  },
  {
    id: "dice-racket-sports",
    label: "Dice Racket Sports",
    description: "Tennis, badminton, table tennis, squash and pickup paddles in dice.",
    memberIds: [
      "dice-badminton",
      "dice-paddle",
      "dice-pickup",
      "dice-squash",
      "dice-table-tennis",
      "dice-tennis",
      "dice-volleyball",
    ],
  },
  {
    id: "dice-racing",
    label: "Dice Racing",
    description: "Formula racing, derby, velodrome and grand prix dice games.",
    memberIds: [
      "dice-belmont-stakes",
      "dice-bicycle-velodrome",
      "dice-derby",
      "dice-formula-de",
      "dice-grand-prix-f1",
      "dice-horse-racing-card",
      "dice-marathon",
      "dice-rallyman-dirt",
      "dice-relay",
      "dice-relay-mini",
      "dice-runner",
      "dice-tour-de-france",
    ],
  },
  {
    id: "dice-fishing-hunting",
    label: "Dice Fishing & Hunting",
    description: "Deep-sea, fly, ice and shore fishing — plus archery and hunts.",
    memberIds: [
      "dice-archery",
      "dice-deep-sea-fishing",
      "dice-fishery",
      "dice-fly-fishing",
      "dice-ice-fishing",
    ],
  },
  {
    id: "dice-themed-jobs",
    label: "Dice Themed Sims",
    description: "Bake, blacksmith, cook, hospital, museum and other themed dice.",
    memberIds: [
      "dice-bake",
      "dice-bakery",
      "dice-bazaar",
      "dice-blacksmith",
      "dice-cooking",
      "dice-courtroom",
      "dice-farm",
      "dice-forge-craft",
      "dice-harvest",
      "dice-hospital-admit",
      "dice-laboratory",
      "dice-museum",
      "dice-orchestra",
      "dice-painting",
      "dice-photography",
      "dice-shipping",
      "dice-shrine",
      "dice-temple",
      "dice-trade-route",
      "dice-village",
    ],
  },
  {
    id: "dice-fantasy",
    label: "Dice Fantasy",
    description: "Dragons, knights, wizards, dungeons and questing dice games.",
    memberIds: [
      "dice-archeology",
      "dice-arena",
      "dice-castle",
      "dice-castle-siege",
      "dice-dragon-fight",
      "dice-dungeon",
      "dice-knight-quest",
      "dice-mine",
      "dice-monster-mash",
      "dice-mystic",
      "dice-pirate",
      "dice-portal",
      "dice-quest",
      "dice-quest-mini",
      "dice-throne-battle",
      "dice-treasure",
      "dice-treasure-map",
      "dice-typhoon",
      "dice-wizard-spell",
    ],
  },
  {
    id: "dice-gambling",
    label: "Dice Gambling",
    description: "Craps, baccarat, blackjack, keno and bingo — all dice-driven.",
    memberIds: [
      "dice-baccarat",
      "dice-bingo",
      "dice-bingo-line",
      "dice-bingo-mini",
      "dice-blackjack",
      "dice-bridge",
      "dice-craps-mini",
      "dice-domino",
      "dice-hand-poker",
      "dice-keno",
      "dice-monopoly",
      "dice-poker",
    ],
  },
  {
    id: "dice-betting",
    label: "Dice Betting",
    description: "Pip, pop, snap and streak betting dice mini-games.",
    memberIds: [
      "dice-add-bet",
      "dice-coin-bet",
      "dice-color-bet",
      "dice-double-pair",
      "dice-flush-bet",
      "dice-low-roll",
      "dice-high-roll",
      "dice-pair-roll",
      "dice-pip-add",
      "dice-pop-roll",
      "dice-quad-bet",
      "dice-skip-bet",
      "dice-snap-roll",
      "dice-spike-bet",
      "dice-spin-bet",
      "dice-stash-roll",
      "dice-step-bet",
      "dice-streak",
      "dice-streak-9",
      "dice-streak-bet",
      "dice-trip-bet",
      "dice-twin-bet",
    ],
  },

  // ---------- Real-life sports ----------
  {
    id: "darts-classic",
    label: "Darts",
    description: "301, 501, 701, cricket, killer and around-the-clock darts.",
    memberIds: [
      "darts-301-classic",
      "darts-501",
      "darts-701-classic",
      "darts-around-clock",
      "darts-baseball-classic",
      "darts-cricket-classic",
      "darts-golf-classic",
      "darts-halve-it",
      "darts-killer-classic",
    ],
  },
  {
    id: "bowling-real",
    label: "Bowling",
    description: "Standard, ninepin, candlepin and duckpin bowling minigames.",
    memberIds: [
      "bowling",
      "bowling-9pin",
      "bowling-candlepin",
      "bowling-duckpin",
      "bowling-pin-tap",
    ],
  },
  {
    id: "ludo-family",
    label: "Ludo & Snakes",
    description: "Ludo, Pachisi-likes, Chutes and Ladders, Snakes and Ladders.",
    memberIds: [
      "chutes-and-ladders-classic",
      "chutes-ladders-kids",
      "ludo",
      "ludo-mini-race",
      "ludo-quick-play",
      "snakes-and-ladders",
    ],
  },

  // ---------- Tycoon / sim ----------
  {
    id: "tycoon-sims",
    label: "Tycoon Sims",
    description: "Farm, food truck, hotel, oil and restaurant tycoon sims.",
    memberIds: [
      "airline-sim",
      "farm-tycoon",
      "food-truck-tycoon",
      "hotel-tycoon",
      "logic-gates-sim",
      "oil-tycoon",
      "restaurant-tycoon",
      "tycoon",
      "tycoon-shed",
    ],
  },

  // ---------- Hex strategy ----------
  {
    id: "hex-strategy",
    label: "Hex Strategy",
    description: "Hex, Y, Havannah and other hexagonal connect strategy games.",
    memberIds: [
      "havannah",
      "hex",
      "hex-chess-glinski",
      "hex-chess-mccooey",
      "hex-chess-shafran",
      "hex-game",
      "y-connection-quiz",
    ],
  },

  // ---------- Mancala ----------
  {
    id: "mancala-family",
    label: "Mancala",
    description: "Oware, Bao, Wari, Kalah and other African pit-and-stone games.",
    memberIds: [
      "bao-mancala-quiz",
      "kalah-quiz",
      "mancala",
      "oware",
      "oware-mancala-quiz",
      "oware-quiz",
      "wari-awale-quiz",
    ],
  },

  // ---------- Pool / billiards ----------
  {
    id: "pool-billiards",
    label: "Pool & Billiards",
    description: "Pool match, snooker, cutthroat and crokinole tabletop games.",
    memberIds: [
      "dice-crokinole",
      "dice-pool-match",
      "dice-snooker-match",
      "pool-cutthroat",
    ],
  },

  // ---------- Brain teasers ----------
  {
    id: "puzzle-mini-games",
    label: "Puzzle Minis",
    description: "Logic grids, jewel quests, slide puzzles and mind challenges.",
    memberIds: [
      "logic-grid",
      "puzzle-box",
      "puzzle-dragons-mini",
      "puzzle-quest-mini",
      "rotate-match",
      "tile-flip",
      "tile-flip-arcade",
    ],
  },
];

/**
 * Compare two strings case-insensitively for sort order. Used by both
 * the lobby (for sorting tiles + variant pickers) and by the families
 * test to verify each family's member list is alphabetisable.
 */
export function compareTitles(a: string, b: string): number {
  return a.localeCompare(b, undefined, { sensitivity: "base" });
}
