import { lazy } from "react";
import type * as React from "react";
import type { GamePlugin, SettingsOf } from "../../platform/game-plugin/types.js";
import type { LightsOutMiniState, LightsOutMiniAction, LightsOutMiniSettings } from "./state.js";
import { initialState, reducer, isTerminal } from "./state.js";
const LightsOutMiniGame = /* @__PURE__ */ lazy(() => import("./Game.js").then((mod) => ({ default: mod.LightsOutMiniGame as unknown as React.ComponentType<unknown> })));
const settings = { dummy: { kind:"boolean" as const, label:"dummy", default:false } } as const;
type S = SettingsOf<typeof settings>;
export const lightsOutMiniPlugin: GamePlugin<LightsOutMiniState, LightsOutMiniAction, typeof settings> = {
  id:"lights-out-mini", title:"Lights Out Mini", category:"board",
  players:{ min:1, max:1, multiplayer:false },
  description:"Tiny 3x3 Lights Out: tap cells to toggle them and their neighbors until all lights are off.",
  howToPlay:`Lights Out Mini is a 3x3 version of the classic 1995 Tiger Electronics puzzle. Each cell is either lit (yellow) or unlit (dark). When you tap a cell, that cell AND each of its orthogonal neighbors flip state — on becomes off, off becomes on. Your goal is to turn every light off.

The starting board is generated by pressing 4–6 random cells, which guarantees the puzzle is solvable. The smaller 3x3 grid makes the math gentler than full 5x5 Lights Out, but the parity rules still apply: every solution exists as a fixed combination of presses, so order doesn't matter — only which cells you tap.

Your score rewards efficient solving: 400 points minus 10 per move, with a 50-point floor. Quick solvers can complete the board in 3–4 taps; longer toggle-fests still earn at least the floor.

If you get stuck, press Play Again to generate a fresh board. Master the patterns and you'll become a Lights Out lightning bolt.`,
  settings,
  initialState:(seed:number,s:S)=>initialState(seed,s as LightsOutMiniSettings),
  reducer, isTerminal, component: LightsOutMiniGame,
};
