// Spelling Bee word list — valid answers for generated puzzles
export const SPELLING_BEE_WORDS: readonly string[] = [
  "AARDVARK","ABANDON","ABILITY","ABOVE","ABSENCE","ABSTRACT","ACCEPT","ACCLAIM",
  "ACCOUNT","ACHIEVE","ACROSS","ACTION","ACTIVE","ADAPT","ADDITION","ADEQUATE",
  "ADORE","ADVANCE","AFFECT","AFFORD","AFRAID","AGAIN","AGENT","AGREE",
  "AHEAD","ALARM","ALBUM","ALERT","ALIKE","ALIVE","ALLAY","ALLOW",
  "ALONE","ALONG","ALOOF","ALTO","ANGEL","ANGLE","ANIMAL","ANKLE",
  "ANNOY","ANSWER","APART","APPEAR","APPLY","AREA","ARENA","ARGUE",
  "ARISE","ARRIVE","ARROW","ASSET","ATLAS","ATONE","ATTIC","AVOID",
  "AWARE","BABEL","BACON","BADGE","BADLY","BANAL","BASIC","BASIN",
  "BATCH","BEACH","BEGAN","BEGIN","BEING","BELOW","BENCH","BLAND",
  "BLANK","BLAST","BLAZE","BLEND","BLESS","BLIND","BLOCK","BLOOD",
  "BLOOM","BLOWN","BOARD","BONUS","BOOST","BOOTH","BOUND","BRAIN",
  "BRAND","BRAVE","BREAD","BREAK","BREED","BRIBE","BRICK","BRIDE",
  "BRIEF","BRING","BROAD","BUILD","BUNCH","BURST","CABIN","CABLE",
  "CAMEL","CANAL","CANDY","CARRY","CARVE","CATCH","CAUSE","CEASE",
  "CHAIR","CHARM","CHART","CHASE","CHEAP","CHECK","CHEER","CHIEF",
  "CHILD","CHINA","CIVIL","CLAIM","CLASH","CLASS","CLEAN","CLEAR",
  "CLIMB","CLING","CLOCK","CLOSE","CLOUD","CLOWN","COACH","COLOR",
  "CORAL","COUNT","COURT","COVER","CRAFT","CRASH","CRAZY","CREAM",
  "CREEK","CRIME","CRISP","CROSS","CROWD","CROWN","CRUDE","CRUSH",
  "CURVE","CYCLE","DANCE","DEATH","DEBUT","DECAY","DELAY","DEPOT",
  "DEPTH","DERBY","DETOX","DEVIL","DIARY","DIGIT","DIRTY","DISCO",
  "DIVERT","DIZZY","DOUBT","DRAFT","DRAIN","DRAMA","DRANK","DRAWN",
  "DREAM","DRESS","DRIFT","DRINK","DRIVE","DROWN","DRYER","DUSKY",
  "EAGLE","EARLY","EARTH","EIGHT","ELECT","ELEGY","EMPTY","ENTER",
  "ENTRY","EQUIP","EXACT","EXCEL","EXIST","EXTRA","FAINT","FAITH",
  "FALSE","FANCY","FEAST","FENCE","FERRY","FEVER","FIBER","FIELD",
  "FIERY","FIFTH","FIGHT","FINAL","FIRST","FIXED","FLAME","FLASH",
  "FLESH","FLOOR","FLOUR","FOCUS","FOGGY","FORCE","FORGE","FORTH",
  "FOUND","FRAME","FRANK","FRAUD","FRESH","FRONT","FROST","FROTH",
  "FRUIT","FULLY","FUNNY","GIANT","GIVEN","GRACE","GRADE","GRAIN",
  "GRAND","GRANT","GRASP","GRASS","GREAT","GREED","GREET","GRIEF",
  "GRILL","GRIND","GROAN","GROSS","GROUP","GROVE","GROWL","GUIDE",
  "GUILD","GUILT","GUISE","GUMMY","HAUNT","HEART","HEAVY","HENCE",
  "HERBS","HONOR","HOTEL","HOUSE","HOVER","HUMAN","HURRY","IDEAL",
  "IMAGE","INDEX","INNER","IRONY","JUDGE","JUICE","JUICY","KEEPS",
  "KNEEL","KNIFE","KNOCK","KNOWN","LABEL","LANCE","LARGE","LASER",
  "LATER","LAYER","LEAFY","LEAKY","LEARN","LEAVE","LEVEL","LIGHT",
  "LIMIT","LOCAL","LOOSE","LOVER","LOWER","LUCKY","LUNAR","MAGIC",
  "MAKER","MANOR","MAPLE","MARCH","MATCH","MEANT","MEDAL","MERGE",
  "MERIT","METAL","MIGHT","MINOR","MINUS","MODEL","MONEY","MORAL",
  "MOUNT","MOUSE","MOVIE","MUSIC","NAKED","NERVE","NIGHT","NOBLE",
  "NOISE","NORTH","NOTED","NOVEL","OCCUR","OFFER","OFTEN","OPERA",
  "ORBIT","ORDER","OTHER","OWNED","OZONE","PAINT","PANIC","PAPER",
  "PATCH","PAUSE","PEACE","PEARL","PHASE","PIANO","PILOT","PLACE",
  "PLAIN","PLANE","PLANT","PLATE","PLAZA","PLEAD","PLUME","POLAR",
  "POSED","POWER","PRESS","PRICE","PRIDE","PRIME","PRINT","PRIZE",
  "PROBE","PROOF","PROSE","PROUD","PROVE","PULSE","PUNCH","PUPIL",
  "QUEEN","QUEST","QUEUE","QUICK","QUIET","QUITE","QUOTA","QUOTE",
  "RADIO","RAISE","RALLY","RANGE","RAPID","REACH","REALM","REBEL",
  "REFER","REIGN","RELAX","RENAL","RENEW","REPAY","REPEL","REPAY",
  "RESET","RIDER","RIGHT","RIGID","RISEN","RIVER","ROBOT","ROCKY",
  "ROMAN","ROUGH","ROUND","ROUTE","ROVER","ROYAL","RULER","RURAL",
  "SADLY","SAINT","SALAD","SANDY","SAUCE","SCALE","SCENE","SCENT",
  "SCOPE","SCORE","SCOUT","SENSE","SERVE","SEVEN","SHAPE","SHARE",
  "SHARP","SHELF","SHELL","SHIFT","SHINE","SHIRT","SHOCK","SHORE",
  "SHORT","SHOUT","SIGHT","SILLY","SINCE","SIXTH","SKILL","SLASH",
  "SLEEP","SLIDE","SLOPE","SMALL","SMART","SMELL","SMILE","SMOKE",
  "SOLID","SOLVE","SORRY","SOUND","SOUTH","SPACE","SPARE","SPARK",
  "SPEAK","SPEED","SPELL","SPEND","SPLIT","SPOKE","SPOON","SPORT",
  "SPRAY","STACK","STAFF","STAGE","STAIN","STALE","STAND","START",
  "STATE","STEAM","STEEL","STEER","STERN","STICK","STILL","STING",
  "STOCK","STONE","STORE","STORM","STORY","STUCK","STUDY","STYLE",
  "SUGAR","SUNNY","SUPER","SURGE","SWEEP","SWEET","SWIFT","SWORD",
  "TABLE","TASTE","TEACH","TENSE","TERMS","THINK","THOSE","THROW",
  "TIGER","TIGHT","TIMER","TIRED","TITLE","TODAY","TOKEN","TOTAL",
  "TOUCH","TOUGH","TOWER","TRACK","TRADE","TRAIL","TRAIN","TREAT",
  "TREND","TRIAL","TRICK","TRIED","TRULY","TRUST","TRUTH","TUMOR",
  "UNCLE","UNDER","UNITY","UNTIL","UPPER","URBAN","USAGE","USUAL",
  "VALID","VALUE","VALVE","VERSE","VIDEO","VIGOR","VIRAL","VITAL",
  "VIVID","VOICE","VOTER","VOWEL","VISTA","WASTE","WATCH","WATER",
  "WEIGH","WHILE","WHITE","WHOLE","WHOSE","WIDER","YOUNG","ZEALOT",
  "ABACK","ABIDE","ABODE","ABOVE","ABHOR","ACORN","ADEPT","ADMIT",
  "ALOFT","AMBER","AMEND","AMISS","AMPLE","AMUSE","ANNEX","ANNOY",
  "ANVIL","ARDOR","ARDENT","ARSON","ASSAY","ATOP","ATOLL","AVERT",
  "AXIOM","BABEL","BAGEL","BAKED","BALER","BANJO","BARGE","BELLY",
  "BIRCH","BIRDY","BLURT","BOWER","BOXER","BULGE","BULLY","BUYER",
  "CABBY","CADET","CAIRN","CAKEY","CAROB","CEDAR","CELLO","CHAFE",
  "CHANT","CHARD","CHESS","CHOSE","CHUCK","CHUMP","CHUNK","CLAMP",
  "CLANG","CLEAT","CLEFT","CLICK","CLING","CLOAK","CLONE","CLOTH",
  "CLOUT","CLOVE","CLUNG","FLICK","FLOCK","FLUNG","FLUTE","FONDLE",
  "FORTE","FOYER","FRAUD","FREAK","FRILL","FRISK","FROND","FUNGI",
  "GAUDY","GAVEL","GAUZE","GIDDY","GLAZE","GLEAM","GLEAN","GLINT",
  "GLOAT","GLOOM","GLOSS","GLOVE","GLYPH","GNOME","GORGE","GOUGE",
  "GOURD","GUILD","GUILE","GUSTO","HAYDN","HELLO","HERBY","HEIST",
  "HIPPO","HOARY","HOLLY","HOMER","HUNKY","HUSTLE","IDYLL","IGLOO",
  "INEPT","INFER","INGOT","IRKED","IVORY","JERKY","JEWEL","JOUST",
  "KAYAK","KNACK","KNAVE","KNELT","KNOLL","LANKY","LAPEL","LAPSE",
  "LARCH","LARVA","LATCH","LAVE","LLAMA","LARDER","LINGO","LINER",
  "LOFTY","LOGIC","LUSTY","MAFIA","MAXIM","MELEE","MELON","MICRO",
  "MIDDAY","MILKY","MISER","MOIST","MOODY","MOOSE","MORPH","MOTTO",
  "MUDDY","MUTED","NAIVE","NAVEL","NEGRO","NICELY","NIFTY","NINETY",
  "NITRO","NOOKS","NOTCH","NOVEL","NYMPH","OASIS","OBESE","OCTET",
  "OFFAL","ONSET","OPTIC","ORCHID","OUTDO","OUTGO","OVEN","OVARY",
] as const;

export function filterByDifficulty(words: readonly string[], letters: readonly string[], centerLetter: string, difficulty: "easy" | "medium" | "hard"): readonly string[] {
  const letterSet = new Set(letters.map(l => l.toUpperCase()));
  const center = centerLetter.toUpperCase();
  const valid = words.filter(w => {
    const upper = w.toUpperCase();
    if (!upper.includes(center)) return false;
    for (const ch of upper) {
      if (!letterSet.has(ch)) return false;
    }
    return true;
  });
  if (difficulty === "easy") return valid.filter(w => w.length <= 6);
  if (difficulty === "medium") return valid;
  return valid.filter(w => w.length >= 4);
}

export function isPangram(word: string, letters: readonly string[]): boolean {
  const letterSet = new Set(letters.map(l => l.toUpperCase()));
  const wordSet = new Set(word.toUpperCase().split(""));
  for (const l of letterSet) {
    if (!wordSet.has(l)) return false;
  }
  return true;
}
